// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import {
  PaginatedAsyncGenerator,
  DeepReadonly,
  HydratePage,
} from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link AccountTypesResource["list"] | list}. */
export interface ListAccountTypesQuery {
  /**
   * Use to specify the next set of results with the string returned in the `nextPageToken` field of the previous response.
   */
  pageToken?: string;
  /** Number of results to return per page, with a maximum of 1000. Defaults to 50. */
  pageSize?: number;
}

/** Query parameters for {@link AccountTypesResource["delete"] | delete}. */
export interface DeleteAccountTypeQuery {
  /**
   * The unique identifier of the account type to reassign users to. Users currently assigned the deleted account type will be reassigned this account type.
   */
  reassignToAccountTypeId?: string;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link AccountTypesResource["create"] | create}. */
export interface CreateAccountTypeBody {
  /** The name of the account type. */
  name: string;
  /** A description of the account type. */
  description: string;
  /**
   * An array of permissions to enable for this account type. Use the permission names from the [/v2/accountTypes/:accountTypeId/permissions](listaccounttypepermissions) endpoint.
   */
  permissions: string[];
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link AccountTypesResource["list"] | list}. */
export interface ListAccountTypesResponse {
  /** Array of results returned by the endpoint */
  entries: {
    accountTypeId: string;
    accountTypeName: string;
    description: string;
    isCustom: boolean;
  }[];
  /**
   * A string that can be passed to the `pageToken` parameter in the next request to fetch the next page of results. Not present in the last page of results.
   * **Must be treated as an opaque string.**
   */
  nextPageToken?: string;
}

/** Response from {@link AccountTypesResource["create"] | create}. */
export interface CreateAccountTypeResponse {
  /** The unique identifier of the account type. */
  accountTypeId: string;
  /** The name of the account type. */
  accountTypeName: string;
  /** A human-readable description of the permissions and capabilities provided by this account type. */
  description: string;
  /**
   * Whether this is a custom account type created by the organization (true) or a default Sigma account type (false).
   */
  isCustom: boolean;
}

/** Response from {@link AccountTypesResource["delete"] | delete}. */
export type DeleteAccountTypeResponse = Record<string, never>;

/** Response from {@link AccountTypesResource["listPermissions"] | listPermissions}. */
export type ListAccountTypePermissionsResponse = {
  permission: string;
  description: string;
}[];

// ---------------------------------------------------------------------------
// Sub-resource accessors (hydration)
// ---------------------------------------------------------------------------

/** Sub-resource accessors available on hydrated accounttype entries. */
export interface AccountTypeSubResources {
  permissions: {
    /**
     * List account type permissions
     *
     * Source docs: https://help.sigmacomputing.com/reference/listaccounttypepermissions
     *
     * Returns all feature permissions for a specific account type.
     *
     *   ### Usage notes
     *   - Retrieve the **accountTypeId** by calling the [/v2/accountTypes](listaccounttypes) endpoint.
     *   - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
     *
     *   ### Usage scenarios
     *   - Display permission details in an admin interface.
     *   - Validate user capabilities based on account type.
     *   - Compare permissions across different account types.
     * @returns ListAccountTypePermissionsResponse
     */
    list(): Promise<DeepReadonly<ListAccountTypePermissionsResponse>>;
  };
}

/** A accounttype entry with sub-resource accessor methods. Response data properties are deeply readonly. */
export type HydratedAccountType<T> = DeepReadonly<T> & AccountTypeSubResources;

// ---------------------------------------------------------------------------
// AccountTypesResource
// ---------------------------------------------------------------------------

/** @internal Attach sub-resource accessors to a accounttype entry. */
function _hydrateAccountType<T extends object>(
  entry: T,
  resource: AccountTypesResource,
): HydratedAccountType<T> {
  return Object.assign(entry, {
    permissions: {
      list: () => resource.listPermissions((entry as any).accountTypeId),
    },
  }) as HydratedAccountType<T>;
}

export class AccountTypesResource {
  constructor(private client: Client<paths>) {}

  /**
   * List account types
   *
   * Source docs: https://help.sigmacomputing.com/reference/listaccounttypes
   *
   * Returns a list of all account types available in the organization.
   *
   *   ### Usage notes
   *   - Use the **accountTypeId** with the [/v2/accountTypes/:accountTypeId/permissions](listaccounttypepermissions) endpoint to retrieve more detailed permissions.
   *   - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   *
   *   ### Usage scenarios
   *   - Display available account types in an admin interface.
   *   - Show an overview of account types for management.
   *
   * @param query - Query parameters
   * @returns ListAccountTypesResponse
   */
  async list(
    query?: ListAccountTypesQuery,
  ): Promise<HydratePage<ListAccountTypesResponse, AccountTypeSubResources>> {
    const { data, error, response } = await this.client.GET(
      '/v2/accountTypes',
      { params: { query } },
    );
    if (error) throw new SigmaApiError(error, response);
    const result = data! as any;
    if (Array.isArray(result)) {
      return result.map((e: any) => _hydrateAccountType(e, this)) as any;
    }
    if (result.entries && Array.isArray(result.entries)) {
      result.entries = result.entries.map((e: any) =>
        _hydrateAccountType(e, this),
      );
    }
    return result;
  }

  /**
   * List account types (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listaccounttypes
   *
   * Returns a list of all account types available in the organization.
   *
   *   ### Usage notes
   *   - Use the **accountTypeId** with the [/v2/accountTypes/:accountTypeId/permissions](listaccounttypepermissions) endpoint to retrieve more detailed permissions.
   *   - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   *
   *   ### Usage scenarios
   *   - Display available account types in an admin interface.
   *   - Show an overview of account types for management.
   *
   * @param query - Query parameters
   * @yields ListAccountTypesResponse
   */
  listAll(
    query?: ListAccountTypesQuery,
  ): PaginatedAsyncGenerator<
    HydratePage<ListAccountTypesResponse, AccountTypeSubResources>
  > {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list({
          ...query,
          pageToken: cursor,
        } as ListAccountTypesQuery);
        yield page;
        cursor = (page as { nextPageToken?: string | null })[
          'nextPageToken'
        ] as string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create an account type
   *
   * Source docs: https://help.sigmacomputing.com/reference/createaccounttype
   *
   * Create a custom account type with specified permissions.
   *
   *   ### Usage notes
   *   - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   *   - Use the permission names from the [/v2/accountTypes/:accountTypeId/permissions](listaccounttypepermissions) endpoint.
   *
   *   ### Usage scenarios
   *   - Create custom account types to define specific permission sets for your organization's users.
   *
   * @param body - The request body.
   * @returns CreateAccountTypeResponse
   */
  async create(
    body: CreateAccountTypeBody,
  ): Promise<HydratedAccountType<CreateAccountTypeResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/accountTypes',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return _hydrateAccountType(data! as any, this);
  }

  /**
   * Delete an account type
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteaccounttype
   *
   * Delete a custom account type and reassign its users to another account type.
   *
   *   ### Usage notes
   *   - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   *   - Default Sigma account types cannot be deleted.
   *   - All users assigned to the deleted account type will be reassigned to the specified **reassignToAccountTypeId**.
   *   - Retrieve account type IDs by calling the [/v2/accountTypes](listaccounttypes) endpoint.
   *
   *   ### Usage scenarios
   *   - Remove custom account types that are no longer needed.
   *   - Consolidate account types by moving users to a different account type before deletion.
   *
   * @param accountTypeId - The unique identifier of the account type to delete.
   * @param query - Query parameters
   * @returns DeleteAccountTypeResponse
   */
  async delete(
    accountTypeId: string,
    query?: DeleteAccountTypeQuery,
  ): Promise<DeepReadonly<DeleteAccountTypeResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/accountTypes/{accountTypeId}',
      { params: { path: { accountTypeId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List account type permissions
   *
   * Source docs: https://help.sigmacomputing.com/reference/listaccounttypepermissions
   *
   * Returns all feature permissions for a specific account type.
   *
   *   ### Usage notes
   *   - Retrieve the **accountTypeId** by calling the [/v2/accountTypes](listaccounttypes) endpoint.
   *   - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   *
   *   ### Usage scenarios
   *   - Display permission details in an admin interface.
   *   - Validate user capabilities based on account type.
   *   - Compare permissions across different account types.
   *
   * @param accountTypeId - The unique identifier of the account type.
   * @returns ListAccountTypePermissionsResponse
   */
  async listPermissions(
    accountTypeId: string,
  ): Promise<DeepReadonly<ListAccountTypePermissionsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/accountTypes/{accountTypeId}/permissions',
      { params: { path: { accountTypeId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
