// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths, operations } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { PaginatedAsyncGenerator, DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link AllowedIpsResource["listV3Alpha"] | listV3Alpha}. */
export interface V3alpha_listIpAllowlistEntriesQuery {
  /**
   * Use to specify the next set of results with the string returned in the `nextPageToken` field of the previous response.
   */
  pageToken?: string;
  /** Number of results to return per page, with a maximum of 1000. Defaults to 50. */
  pageSize?: number;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link AllowedIpsResource["createV3Alpha"] | createV3Alpha}. */
export type V3alpha_createIpAllowlistEntriesBody = NonNullable<
  operations['v3alpha_createIpAllowlistEntries']['requestBody']
>['content']['application/json'];

/** Request body for {@link AllowedIpsResource["deleteV3Alpha"] | deleteV3Alpha}. */
export interface V3alpha_deleteIpAllowlistEntriesBody {
  /** Array of IP allowlist entry IDs to remove */
  ipAllowlistEntryIds: string[];
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link AllowedIpsResource["listV3Alpha"] | listV3Alpha}. */
export interface V3alpha_listIpAllowlistEntriesResponse {
  /** Array of results returned by the endpoint */
  entries: {
    ipAllowlistEntryId: string;
    ip: string;
    scope: 'public-api' | 'ui' | 'both';
    description?: string;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
  }[];
  /**
   * A string that can be passed to the `pageToken` parameter in the next request to fetch the next page of results. Not present in the last page of results.
   * **Must be treated as an opaque string.**
   */
  nextPageToken?: string;
}

/** Response from {@link AllowedIpsResource["createV3Alpha"] | createV3Alpha}. */
export interface V3alpha_createIpAllowlistEntriesResponse {
  /** Array of created IP allowlist entries */
  entries: {
    ipAllowlistEntryId: string;
    ip: string;
    scope: 'public-api' | 'ui' | 'both';
    description?: string;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
  }[];
}

/** Response from {@link AllowedIpsResource["deleteV3Alpha"] | deleteV3Alpha}. */
export type V3alpha_deleteIpAllowlistEntriesResponse = Record<string, never>;

// ---------------------------------------------------------------------------
// AllowedIpsResource
// ---------------------------------------------------------------------------

export class AllowedIpsResource {
  constructor(private client: Client<paths>) {}

  /**
   * List IP allowlist entries (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/v3alpha_listipallowlistentries
   *
   * Retrieve a paginated list of all IP addresses and CIDR ranges in your organization's IP allowlist.
   *
   * **Beta**: This documentation describes a private beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Returns the IP allowlist entries.
   *   - Results are sorted by creation date in descending order (newest first).
   *
   * @param query - Query parameters
   * @returns V3alpha_listIpAllowlistEntriesResponse
   */
  async listV3Alpha(
    query?: V3alpha_listIpAllowlistEntriesQuery,
  ): Promise<DeepReadonly<V3alpha_listIpAllowlistEntriesResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v3alpha/allowedIps',
      { params: { query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List IP allowlist entries (Beta) (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/v3alpha_listipallowlistentries
   *
   * Retrieve a paginated list of all IP addresses and CIDR ranges in your organization's IP allowlist.
   *
   * **Beta**: This documentation describes a private beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Returns the IP allowlist entries.
   *   - Results are sorted by creation date in descending order (newest first).
   *
   * @param query - Query parameters
   * @yields V3alpha_listIpAllowlistEntriesResponse
   */
  listV3AlphaAll(
    query?: V3alpha_listIpAllowlistEntriesQuery,
  ): PaginatedAsyncGenerator<
    DeepReadonly<V3alpha_listIpAllowlistEntriesResponse>
  > {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listV3Alpha({
          ...query,
          pageToken: cursor,
        } as V3alpha_listIpAllowlistEntriesQuery);
        yield page;
        cursor = (page as { nextPageToken?: string | null })[
          'nextPageToken'
        ] as string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create IP allowlist entries (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/v3alpha_createipallowlistentries
   *
   * Add new IP address entries to your organization's IP allowlist.
   *
   * **Beta**: This documentation describes a private beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Supports IPv4, IPv6, and CIDR ranges (e.g., `192.168.1.0/24`, `2001:db8::/32`).
   *   - Maximum of 200 total IP entries allowed per organization.
   *   - Duplicate IP addresses are not allowed. If a request contains an IP address already on the list, the request fails.
   *
   *   ### Usage scenarios
   *   - Add IP ranges for new locations or employees.
   *   - Bulk import IP addresses from a list.
   *
   * @param body - The request body.
   * @returns V3alpha_createIpAllowlistEntriesResponse
   */
  async createV3Alpha(
    body: V3alpha_createIpAllowlistEntriesBody,
  ): Promise<DeepReadonly<V3alpha_createIpAllowlistEntriesResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v3alpha/allowedIps:batchCreate',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete IP allowlist entries (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/v3alpha_deleteipallowlistentries
   *
   * Remove existing IP address entries from your organization's IP allowlist.
   *
   * **Beta**: This documentation describes a private beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Retrieve the `ipAllowlistEntryId` values with the [/v3alpha/allowedIps](v3alpha_listipallowlistentries) endpoint or from the response of the [/v3alpha/allowedIps:batchCreate](v3alpha_createipallowlistentries) endpoint.
   *   - Entries are identified by their unique IDs, not by IP addresses.
   *
   *   ### Usage scenarios
   *   - Remove compromised or outdated IP addresses from access.
   *   - Clean up unused IP allowlist entries.
   *
   * @param body - The request body.
   * @returns V3alpha_deleteIpAllowlistEntriesResponse
   */
  async deleteV3Alpha(
    body: V3alpha_deleteIpAllowlistEntriesBody,
  ): Promise<DeepReadonly<V3alpha_deleteIpAllowlistEntriesResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v3alpha/allowedIps:batchDelete',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
