// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths, operations } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { PaginatedAsyncGenerator, DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link ApiCredentialsResource["list"] | list}. */
export interface ListApiCredentialsQuery {
  /**
   * Use to specify the next set of results with the string returned in the `nextPageToken` field of the previous response.
   */
  pageToken?: string;
  /** Number of results to return per page, with a maximum of 1000. Defaults to 50. */
  pageSize?: number;
  /**
   * Sort order. Supported fields: `name`, `description`. Append ` desc` for descending (e.g. `name desc`). Defaults to `name` ascending.
   */
  orderBy?: string;
  /** Filter results to credentials whose name contains this substring. */
  name?: string;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link ApiCredentialsResource["create"] | create}. */
export type CreateApiCredentialBody = NonNullable<
  operations['createApiCredential']['requestBody']
>['content']['application/json'];

/** Request body for {@link ApiCredentialsResource["update"] | update}. */
export type UpdateApiCredentialBody = NonNullable<
  operations['updateApiCredential']['requestBody']
>['content']['application/json'];

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link ApiCredentialsResource["list"] | list}. */
export interface ListApiCredentialsResponse {
  /** Array of results returned by the endpoint */
  entries: {
    apiCredentialId: string;
    name: string;
    authMethod:
      | 'basic'
      | 'bearer'
      | 'apiKey'
      | 'oAuthClientCredentials'
      | 'oAuthAuthorizationCode'
      | 'oAuthPasswordCredentials'
      | 'awsSigV4';
    allowlist: string[];
    description?: string;
  }[];
  /**
   * A string that can be passed to the `pageToken` parameter in the next request to fetch the next page of results. Not present in the last page of results.
   * **Must be treated as an opaque string.**
   */
  nextPageToken?: string;
}

/** Response from {@link ApiCredentialsResource["create"] | create}. */
export interface CreateApiCredentialResponse {
  /** Unique identifier of the API credential. */
  apiCredentialId: string;
  /** Display name of the credential. */
  name: string;
  /** Authentication method the credential uses. */
  authMethod:
    | 'basic'
    | 'bearer'
    | 'apiKey'
    | 'oAuthClientCredentials'
    | 'oAuthAuthorizationCode'
    | 'oAuthPasswordCredentials'
    | 'awsSigV4';
  /** Hostname glob patterns (e.g. `*.example.com`) that the credential is authorized to be used against. */
  allowlist: string[];
  /**
   * Nonsensitive projection of the credential, discriminated by `authMethod`. Secret fields (password, token, clientSecret, secretAccessKey) are never returned.
   */
  credential:
    | {
        authMethod: 'basic';
        basic?: {
          username: string;
        };
      }
    | {
        authMethod: 'bearer';
      }
    | {
        authMethod: 'apiKey';
        apiKey?: {
          key: string;
          isQueryParam: boolean;
        };
      }
    | {
        authMethod: 'oAuthClientCredentials';
        oAuthClientCredentials?: {
          clientId: string;
          accessTokenUrl: string;
          scopes: string[];
          accessTokenAuthMethod: 'httpBasic' | 'requestBody';
        };
      }
    | {
        authMethod: 'oAuthAuthorizationCode';
        oAuthAuthorizationCode?: {
          clientId: string;
          authorizationUrl: string;
          accessTokenUrl: string;
          scopes: string[];
          accessTokenAuthMethod: 'httpBasic' | 'requestBody';
        };
      }
    | {
        authMethod: 'oAuthPasswordCredentials';
        oAuthPasswordCredentials?: {
          username: string;
          accessTokenUrl: string;
          scopes: string[];
          accessTokenAuthMethod: 'httpBasic' | 'requestBody';
          clientId?: string;
        };
      }
    | {
        authMethod: 'awsSigV4';
        awsSigV4?: {
          accessKeyId: string;
          region?: string;
          service?: string;
          temporaryCredentialsUrl?: string;
          temporaryCredentialsResponseMapping?: {
            accessKeyField?: string;
            secretKeyField?: string;
            sessionTokenField?: string;
            expirationField?: string;
          };
          temporaryCredentialsRequestParams?: {
            key: string;
            value: string;
            sendIn: 'queryParam' | 'body' | 'header';
          }[];
        };
      };
  /** The identifier of the user who created this object. */
  createdBy: string;
  /** The identifier of the user or process that last updated this object. */
  updatedBy: string;
  /** When the object was created. */
  createdAt: string;
  /** When the object was last updated. */
  updatedAt: string;
  /** Human-readable description. */
  description?: string;
}

/** Response from {@link ApiCredentialsResource["get"] | get}. */
export interface GetApiCredentialResponse {
  /** Unique identifier of the API credential. */
  apiCredentialId: string;
  /** Display name of the credential. */
  name: string;
  /** Authentication method the credential uses. */
  authMethod:
    | 'basic'
    | 'bearer'
    | 'apiKey'
    | 'oAuthClientCredentials'
    | 'oAuthAuthorizationCode'
    | 'oAuthPasswordCredentials'
    | 'awsSigV4';
  /** Hostname glob patterns (e.g. `*.example.com`) that the credential is authorized to be used against. */
  allowlist: string[];
  /**
   * Nonsensitive projection of the credential, discriminated by `authMethod`. Secret fields (password, token, clientSecret, secretAccessKey) are never returned.
   */
  credential:
    | {
        authMethod: 'basic';
        basic?: {
          username: string;
        };
      }
    | {
        authMethod: 'bearer';
      }
    | {
        authMethod: 'apiKey';
        apiKey?: {
          key: string;
          isQueryParam: boolean;
        };
      }
    | {
        authMethod: 'oAuthClientCredentials';
        oAuthClientCredentials?: {
          clientId: string;
          accessTokenUrl: string;
          scopes: string[];
          accessTokenAuthMethod: 'httpBasic' | 'requestBody';
        };
      }
    | {
        authMethod: 'oAuthAuthorizationCode';
        oAuthAuthorizationCode?: {
          clientId: string;
          authorizationUrl: string;
          accessTokenUrl: string;
          scopes: string[];
          accessTokenAuthMethod: 'httpBasic' | 'requestBody';
        };
      }
    | {
        authMethod: 'oAuthPasswordCredentials';
        oAuthPasswordCredentials?: {
          username: string;
          accessTokenUrl: string;
          scopes: string[];
          accessTokenAuthMethod: 'httpBasic' | 'requestBody';
          clientId?: string;
        };
      }
    | {
        authMethod: 'awsSigV4';
        awsSigV4?: {
          accessKeyId: string;
          region?: string;
          service?: string;
          temporaryCredentialsUrl?: string;
          temporaryCredentialsResponseMapping?: {
            accessKeyField?: string;
            secretKeyField?: string;
            sessionTokenField?: string;
            expirationField?: string;
          };
          temporaryCredentialsRequestParams?: {
            key: string;
            value: string;
            sendIn: 'queryParam' | 'body' | 'header';
          }[];
        };
      };
  /** The identifier of the user who created this object. */
  createdBy: string;
  /** The identifier of the user or process that last updated this object. */
  updatedBy: string;
  /** When the object was created. */
  createdAt: string;
  /** When the object was last updated. */
  updatedAt: string;
  /** Human-readable description. */
  description?: string;
}

/** Response from {@link ApiCredentialsResource["update"] | update}. */
export interface UpdateApiCredentialResponse {
  /** Unique identifier of the API credential. */
  apiCredentialId: string;
  /** Display name of the credential. */
  name: string;
  /** Authentication method the credential uses. */
  authMethod:
    | 'basic'
    | 'bearer'
    | 'apiKey'
    | 'oAuthClientCredentials'
    | 'oAuthAuthorizationCode'
    | 'oAuthPasswordCredentials'
    | 'awsSigV4';
  /** Hostname glob patterns (e.g. `*.example.com`) that the credential is authorized to be used against. */
  allowlist: string[];
  /**
   * Nonsensitive projection of the credential, discriminated by `authMethod`. Secret fields (password, token, clientSecret, secretAccessKey) are never returned.
   */
  credential:
    | {
        authMethod: 'basic';
        basic?: {
          username: string;
        };
      }
    | {
        authMethod: 'bearer';
      }
    | {
        authMethod: 'apiKey';
        apiKey?: {
          key: string;
          isQueryParam: boolean;
        };
      }
    | {
        authMethod: 'oAuthClientCredentials';
        oAuthClientCredentials?: {
          clientId: string;
          accessTokenUrl: string;
          scopes: string[];
          accessTokenAuthMethod: 'httpBasic' | 'requestBody';
        };
      }
    | {
        authMethod: 'oAuthAuthorizationCode';
        oAuthAuthorizationCode?: {
          clientId: string;
          authorizationUrl: string;
          accessTokenUrl: string;
          scopes: string[];
          accessTokenAuthMethod: 'httpBasic' | 'requestBody';
        };
      }
    | {
        authMethod: 'oAuthPasswordCredentials';
        oAuthPasswordCredentials?: {
          username: string;
          accessTokenUrl: string;
          scopes: string[];
          accessTokenAuthMethod: 'httpBasic' | 'requestBody';
          clientId?: string;
        };
      }
    | {
        authMethod: 'awsSigV4';
        awsSigV4?: {
          accessKeyId: string;
          region?: string;
          service?: string;
          temporaryCredentialsUrl?: string;
          temporaryCredentialsResponseMapping?: {
            accessKeyField?: string;
            secretKeyField?: string;
            sessionTokenField?: string;
            expirationField?: string;
          };
          temporaryCredentialsRequestParams?: {
            key: string;
            value: string;
            sendIn: 'queryParam' | 'body' | 'header';
          }[];
        };
      };
  /** The identifier of the user who created this object. */
  createdBy: string;
  /** The identifier of the user or process that last updated this object. */
  updatedBy: string;
  /** When the object was created. */
  createdAt: string;
  /** When the object was last updated. */
  updatedAt: string;
  /** Human-readable description. */
  description?: string;
}

/** Response from {@link ApiCredentialsResource["delete"] | delete}. */
export type DeleteApiCredentialResponse = Record<string, never>;

// ---------------------------------------------------------------------------
// ApiCredentialsResource
// ---------------------------------------------------------------------------

export class ApiCredentialsResource {
  constructor(private client: Client<paths>) {}

  /**
   * List API credentials
   *
   * Source docs: https://help.sigmacomputing.com/reference/listapicredentials
   *
   * This endpoint returns a paginated list of API credentials. For more information on API credentials, see [Configure API credentials and connectors in Sigma](https://help.sigmacomputing.com/docs/configure-api-credentials-and-connectors-in-sigma).
   *
   * ### Usage notes
   * - The user making this request must be assigned an account type with the **Manage API connectors** permission enabled.
   * - Only returns [API credentials](https://help.sigmacomputing.com/docs/configure-api-credentials-and-connectors-in-sigma#add-a-new-api-credential-to-sigma) that the user making this request has at least **Can view** access to.
   * - Secret fields such as passwords, tokens, and client secrets are never included in the response.
   * - Use the `name` query parameter to filter by credential name.
   * - Use the `orderBy` query parameter to set sort order.
   *
   * ### Usage scenarios
   * - **Credential management:** View and audit the credentials used by API connectors in your Sigma organization.
   * - **API connector creation:** Retrieve available credentials to present as options when creating an API connector.
   *
   * @param query - Query parameters
   * @returns ListApiCredentialsResponse
   */
  async list(
    query?: ListApiCredentialsQuery,
  ): Promise<DeepReadonly<ListApiCredentialsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/api-credentials',
      { params: { query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List API credentials (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listapicredentials
   *
   * This endpoint returns a paginated list of API credentials. For more information on API credentials, see [Configure API credentials and connectors in Sigma](https://help.sigmacomputing.com/docs/configure-api-credentials-and-connectors-in-sigma).
   *
   * ### Usage notes
   * - The user making this request must be assigned an account type with the **Manage API connectors** permission enabled.
   * - Only returns [API credentials](https://help.sigmacomputing.com/docs/configure-api-credentials-and-connectors-in-sigma#add-a-new-api-credential-to-sigma) that the user making this request has at least **Can view** access to.
   * - Secret fields such as passwords, tokens, and client secrets are never included in the response.
   * - Use the `name` query parameter to filter by credential name.
   * - Use the `orderBy` query parameter to set sort order.
   *
   * ### Usage scenarios
   * - **Credential management:** View and audit the credentials used by API connectors in your Sigma organization.
   * - **API connector creation:** Retrieve available credentials to present as options when creating an API connector.
   *
   * @param query - Query parameters
   * @yields ListApiCredentialsResponse
   */
  listAll(
    query?: ListApiCredentialsQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListApiCredentialsResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list({
          ...query,
          pageToken: cursor,
        } as ListApiCredentialsQuery);
        yield page;
        cursor = (page as { nextPageToken?: string | null })[
          'nextPageToken'
        ] as string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create an API credential
   *
   * Source docs: https://help.sigmacomputing.com/reference/createapicredential
   *
   * This endpoint creates a new API credential for use with API connectors and the **Call API** action in Sigma. For more information on API credentials, see [Configure API credentials and connectors in Sigma](https://help.sigmacomputing.com/docs/configure-api-credentials-and-connectors-in-sigma).
   *
   * ### Usage notes
   * - The user making this request must be assigned an account type with the **Manage API connectors** permission enabled.
   * - The `allowlist` parameter is required and must contain at least one hostname glob pattern. Use `["*"]` to allow the credential to be used against any host.
   * - The following authentication methods are supported: `basic`, `bearer`, `apiKey`, `oAuthClientCredentials`, `oAuthAuthorizationCode`, `oAuthPasswordCredentials`, `awsSigV4`.
   * - Secret fields are encrypted at rest and are never returned in subsequent read responses.
   *
   * ### Usage scenarios
   * - **Credential provisioning:** Automate credential creation as part of environment setup or onboarding.
   * - **Multi-service authentication:** Create separate credentials for each external service, with allowlists scoped to only that service's domains.
   *
   * @param body - The request body.
   * @returns CreateApiCredentialResponse
   */
  async create(
    body: CreateApiCredentialBody,
  ): Promise<DeepReadonly<CreateApiCredentialResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/api-credentials',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get an API credential
   *
   * Source docs: https://help.sigmacomputing.com/reference/getapicredential
   *
   * This endpoint returns nonsensitive details for a single API credential. For more information on API credentials, see [Configure API credentials and connectors in Sigma](https://help.sigmacomputing.com/docs/configure-api-credentials-and-connectors-in-sigma).
   *
   * ### Usage notes
   * - The user making this request must be assigned an account type with the **Manage API connectors** permission enabled and have at least **Can view** access on the credential.
   * - Retrieve the **apiCredentialId** by calling the [/v2/api-credentials](listapicredentials) endpoint.
   * - Secret fields (passwords, tokens, client secrets, secret access keys) are never returned.
   *
   * ### Usage scenarios
   * - **Credential inspection:** Retrieve the configuration of a credential to verify its settings before using it with a connector.
   *
   * @param apiCredentialId
   * @returns GetApiCredentialResponse
   */
  async get(
    apiCredentialId: string,
  ): Promise<DeepReadonly<GetApiCredentialResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/api-credentials/{apiCredentialId}',
      { params: { path: { apiCredentialId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Update an API credential
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateapicredential
   *
   * This endpoint updates one or more fields on an existing API credential. For more information on API credentials, see [Configure API credentials and connectors in Sigma](https://help.sigmacomputing.com/docs/configure-api-credentials-and-connectors-in-sigma).
   *
   * ### Usage notes
   * - The user making this request must be assigned an account type with the **Manage API connectors** permission enabled and have **Can edit** access to the API credential.
   * - Retrieve the **apiCredentialId** by calling the [/v2/api-credentials](listapicredentials) endpoint.
   * - Omitted fields are left unchanged.
   * - If a `credential` is provided, the provided authentication details (ID, secret, etc.) replace the previous values. To leave secrets unchanged, omit the `credential` parameter.
   *
   * ### Usage scenarios
   * - **Secret rotation:** Update the secret fields for a credential automatically for an external service.
   * - **Allowlist updates:** Expand or restrict the set of hostnames the credential can be used against.
   *
   * @param apiCredentialId
   * @param body - The request body.
   * @returns UpdateApiCredentialResponse
   */
  async update(
    apiCredentialId: string,
    body: UpdateApiCredentialBody,
  ): Promise<DeepReadonly<UpdateApiCredentialResponse>> {
    const { data, error, response } = await this.client.PATCH(
      '/v2/api-credentials/{apiCredentialId}',
      { params: { path: { apiCredentialId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete an API credential
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteapicredential
   *
   * This endpoint archives an API credential so it can no longer be associated with new API connectors. For more information on API credentials, see [Configure API credentials and connectors in Sigma](https://help.sigmacomputing.com/docs/configure-api-credentials-and-connectors-in-sigma).
   *
   * ### Usage notes
   * - The user making this request must be assigned an account type with the **Manage API connectors** permission enabled and have **Can edit** access to the API credential.
   * - Retrieve the **apiCredentialId** by calling the [/v2/api-credentials](listapicredentials) endpoint.
   * - Archiving a credential does not automatically unbind any API connectors that reference it.
   *
   * ### Usage scenarios
   * - **Credential decommissioning:** Remove credentials for decommissioned services or expired tokens.
   * - **Security cleanup:** Archive compromised or rotated credentials to prevent accidental reuse.
   *
   * @param apiCredentialId
   * @returns DeleteApiCredentialResponse
   */
  async delete(
    apiCredentialId: string,
  ): Promise<DeepReadonly<DeleteApiCredentialResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/api-credentials/{apiCredentialId}',
      { params: { path: { apiCredentialId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
