// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

export interface PostTokenBody_AccessToken {
  /** Set to `client_credentials` to retrieve an access token. */
  grant_type: 'client_credentials';
}

export interface PostTokenBody_RefreshToken {
  /** Set to `refresh_token` to refresh your access token.  */
  grant_type: 'refresh_token';
  refresh_token: string;
}

/** (Beta) Generate an access token as a specific user using a JSON Web Token (JWT). */
export interface PostTokenBody_BetaImpersonation {
  /** Set to `urn:ietf:params:oauth:grant-type:token-exchange` to get an impersonated token. */
  grant_type: 'urn:ietf:params:oauth:grant-type:token-exchange';
  /**
   * A self-signed JWT token with the following claims: `kid` (the client ID), and either `sub` (the email of the user to impersonate), `tenant` (the organization ID of the tenant to impersonate), or both. When `tenant` is provided without `sub`, the tenant admin user will be impersonated. When both are provided, the specified user will be impersonated within the context of that tenant organization.
   */
  subject_token: string;
  subject_token_type: 'urn:ietf:params:oauth:token-type:jwt';
  /**
   * An access token owned by a Sigma user assigned the Admin account type. This token must match the bearer token in the request authorization header.
   */
  actor_token: string;
  actor_token_type: 'urn:ietf:params:oauth:token-type:access_token';
}

/** Request body for {@link AuthResource["postToken"] | postToken}. */
export type PostTokenBody =
  | PostTokenBody_AccessToken
  | PostTokenBody_RefreshToken
  | PostTokenBody_BetaImpersonation;

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

export interface PostTokenResponse_AccessRefreshToken {
  /** Token used to access the API and make requests. */
  access_token: string;
  /** Refresh token used to refresh access token. */
  refresh_token: string;
  token_type: 'bearer';
  /** Number of seconds in which the token expires. */
  expires_in: number;
}

export interface PostTokenResponse_BetaImpersonation {
  /** Access token used to access the API and make requests as the impersonated user. */
  access_token: string;
  issued_token_type: 'urn:ietf:params:oauth:token-type:access_token';
  token_type: 'Bearer';
  /** Number of seconds in which the token expires. */
  expires_in: number;
}

/** Response from {@link AuthResource["postToken"] | postToken}. */
export type PostTokenResponse =
  PostTokenResponse_AccessRefreshToken | PostTokenResponse_BetaImpersonation;

// ---------------------------------------------------------------------------
// AuthResource
// ---------------------------------------------------------------------------

export class AuthResource {
  constructor(private client: Client<paths>) {}

  /**
   * Get access token
   *
   * Source docs: https://help.sigmacomputing.com/reference/posttoken
   *
   * Use your Sigma client ID and secret with this endpoint to generate an access token valid for one hour, or to refresh your token. You can then use the access token to authenticate requests made to the Sigma API.
   *
   * To make any API call with the Sigma API, including calls from the API documentation, you must have a valid bearer token. To generate a token, you must have a valid **Client ID** and **Secret**. See [Generate Sigma API client credentials](generate-client-credentials).
   *
   * You make all API calls to a specific URL that corresponds to the cloud where your Sigma environment is hosted. Set the **Base URL** to the relevant URL for your environment. For details, see [Identify your API request URL](get-started-sigma-api#identify-your-api-request-url).
   *
   * Generate a token by sending a POST request to this `/v2/auth/token` endpoint, or use the **Try It!** option on this page.
   *
   * ### Usage notes
   *
   * - The API token is valid for 1 hour. When the token expires, an endpoint response returns an unauthorized error.
   * - Refresh your access token before it expires using the `refresh_token` option.
   * - If your client credentials are owned by a user assigned the Admin account type, you can generate an access token as a specific user using impersonation.
   *
   * @param body - The request body.
   * @returns PostTokenResponse
   */
  async postToken(
    body: PostTokenBody,
  ): Promise<DeepReadonly<PostTokenResponse>> {
    const { data, error, response } = await this.client.POST('/v2/auth/token', {
      body: body as never,
    });
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
