// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths, operations } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import {
  PaginatedAsyncGenerator,
  DeepReadonly,
  HydratePage,
} from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link ConnectionsResource["list"] | list}. */
export interface ListConnectionsQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
  includeArchived?: boolean;
  /** Search filter for the name of the connection. */
  search?: string;
}

/** Query parameters for {@link ConnectionsResource["listGrants"] | listGrants}. */
export interface ListConnectionGrantsQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

/** Query parameters for {@link ConnectionsResource["syncPath"] | syncPath}. */
export interface SyncConnectionPathQuery {
  /** Whether to use the OAuth connection's service account to perform the sync. */
  useServiceAccount?: boolean;
}

/** Query parameters for {@link ConnectionsResource["listPaths"] | listPaths}. */
export interface ListConnectionPathsQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

/** Query parameters for {@link ConnectionsResource["listPathGrants"] | listPathGrants}. */
export interface ListConnectionPathGrantsQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

/** Query parameters for {@link ConnectionsResource["listTableColumns"] | listTableColumns}. */
export interface ListConnectionTableColumnsQuery {
  /**
   * Use to specify the next set of results with the string returned in the `nextPageToken` field of the previous response.
   */
  pageToken?: string;
  /** Number of results to return per page, with a maximum of 1000. Defaults to 50. */
  pageSize?: number;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link ConnectionsResource["lookup"] | lookup}. */
export interface LookupConnectionBody {
  path: string[] | string[] | string[];
}

/** Request body for {@link ConnectionsResource["create"] | create}. */
export type CreateConnectionBody = NonNullable<
  operations['createConnection']['requestBody']
>['content']['application/json'];

/** Request body for {@link ConnectionsResource["update"] | update}. */
export type UpdateConnectionBody = NonNullable<
  operations['updateConnection']['requestBody']
>['content']['application/json'];

/** Request body for {@link ConnectionsResource["updateDeprecated"] | updateDeprecated}. */
export interface UpdateConnectionDeprecatedBody {
  name?: string;
  useOauth?: boolean;
}

/** Request body for {@link ConnectionsResource["postDbtArtifacts"] | postDbtArtifacts}. */
export type PostConnectionDbtArtifactsBody = FormData;

/** Request body for {@link ConnectionsResource["createGrant"] | createGrant}. */
export interface CreateConnectionGrantBody {
  grants: {
    grantee:
      | {
          memberId: string;
        }
      | {
          teamId: string;
        };
    permission: 'annotate' | 'usage';
  }[];
}

/** Request body for {@link ConnectionsResource["syncPath"] | syncPath}. */
export interface SyncConnectionPathBody {
  path: string[] | string[] | string[];
}

/** Request body for {@link ConnectionsResource["createPathGrant"] | createPathGrant}. */
export interface CreateConnectionPathGrantBody {
  grants: {
    grantee:
      | {
          memberId: string;
        }
      | {
          teamId: string;
        };
    permission: 'annotate' | 'usage';
  }[];
}

/** Request body for {@link ConnectionsResource["createV3Alpha"] | createV3Alpha}. */
export type V3alpha_createConnectionBody = NonNullable<
  operations['v3alpha_createConnection']['requestBody']
>['content']['application/json'];

/** Request body for {@link ConnectionsResource["patchV3Alpha"] | patchV3Alpha}. */
export type V3alpha_patchConnectionBody = NonNullable<
  operations['v3alpha_patchConnection']['requestBody']
>['content']['application/json'];

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link ConnectionsResource["lookup"] | lookup}. */
export interface LookupConnectionResponse {
  kind: 'scope' | 'table' | 'semanticView' | 'metricView' | 'stored-procedure';
  inodeId: string;
  url: string;
}

/** Response from {@link ConnectionsResource["list"] | list}. */
export interface ListConnectionsResponse {
  /** Array of results returned by the endpoint */
  entries: {
    organizationId: string;
    connectionId: string;
    isSample: boolean;
    isAuditLog: boolean;
    lastActiveAt: string;
    name: string;
    type: string;
    useOauth: boolean;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
    isArchived?: boolean;
    account?: string;
    warehouse?: string;
    user?: string;
    role?: string;
    timeout?: {
      default: number;
      worksheet?: number;
      dashboard?: number;
      download?: number;
    };
    poolSizes?: {
      isPoolConfigured?: boolean;
      adhocPoolSize?: number;
      catalogPoolSize?: number;
      resultPoolSize?: number;
      schedulePoolSize?: number;
    };
    writeAccess?: boolean;
    friendlyName?: boolean;
    writebacks?: {
      database: string;
      schema: string;
      writebackSchemaId?: string;
    }[];
    writebackSchemas?: {
      database: string;
      schema: string;
      writebackSchemaId?: string;
    }[];
    inputTableAuditLogSchema?: {
      database: string;
      schema: string;
      writebackSchemaId?: string;
    };
    materializationWarehouse?: string;
    exportsWarehouse?: string;
    oauthMetadataUrl?: string;
    oauthClientId?: string;
    oauthScopes?: string[];
    oauthIdpType?:
      | 'aws_databricks'
      | 'azure_databricks'
      | 'gcp_databricks'
      | 'azuread'
      | 'auth0'
      | 'adfs'
      | 'okta'
      | 'ping'
      | 'snowflake'
      | 'unknown';
    oauthUsePkce?: boolean | null;
    oauthUseJwt?: boolean | null;
    oauthAudience?: string;
    isIndependentOAuth?: boolean;
    userAttributes?: {
      role?: string;
      warehouse?: string;
    };
  }[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link ConnectionsResource["create"] | create}. */
export interface CreateConnectionResponse {
  /** Unique identifier of the organization */
  organizationId: string;
  /** Unique identifier of the connection */
  connectionId: string;
  /** Whether the connection is the Sigma sample data connection */
  isSample: boolean;
  /** Whether audit logging is enabled */
  isAuditLog: boolean;
  /** Last activity date and time */
  lastActiveAt: string;
  /** Name of the connection */
  name: string;
  /** Type of the connection (e.g., "bigQuery") */
  type: string;
  /** Whether OAuth is used */
  useOauth: boolean;
  /** Identifier of the user who created this connection */
  createdBy: string;
  /** Identifier of the user or process that last updated this connection */
  updatedBy: string;
  /** When the connection was created */
  createdAt: string;
  /** When the connection was last updated */
  updatedAt: string;
  /** Whether the connection is archived */
  isArchived?: boolean;
  /** Account associated with the connection */
  account?: string;
  /** Warehouse associated with the connection */
  warehouse?: string;
  /** User associated with the connection */
  user?: string;
  /** Role used by the connection user */
  role?: string;
  /** Timeout settings for the connection, with a default value in seconds */
  timeout?: {
    default: number;
    worksheet?: number;
    dashboard?: number;
    download?: number;
  };
  /** Pool sizes for the connection, such as for adhocPoolSize or schedulePoolSize */
  poolSizes?: {
    isPoolConfigured?: boolean;
    adhocPoolSize?: number;
    catalogPoolSize?: number;
    resultPoolSize?: number;
    schedulePoolSize?: number;
  };
  writeAccess?: boolean;
  /** Whether friendly names are enabled for this connection */
  friendlyName?: boolean;
  /** Configure write-back for non-OAuth connections */
  writebacks?: {
    database: string;
    schema: string;
    writebackSchemaId?: string;
  }[];
  /** Configure write-back for OAuth connections */
  writebackSchemas?: {
    database: string;
    schema: string;
    writebackSchemaId?: string;
  }[];
  /**
   * Schema to use for the input table write-ahead log (WAL). Cannot be changed without breaking write behavior on this connection.
   */
  inputTableAuditLogSchema?: {
    database: string;
    schema: string;
    writebackSchemaId?: string;
  };
  /** Warehouse used to run materialization jobs */
  materializationWarehouse?: string;
  /** Warehouse used to run export jobs */
  exportsWarehouse?: string;
  /** OAuth metadata URL configured directly on this connection. */
  oauthMetadataUrl?: string;
  /** Client ID configured directly on this connection. */
  oauthClientId?: string;
  /** OAuth scopes configured directly on this connection. */
  oauthScopes?: string[];
  /** OAuth provider type configured or inferred for this connection. */
  oauthIdpType?:
    | 'aws_databricks'
    | 'azure_databricks'
    | 'gcp_databricks'
    | 'azuread'
    | 'auth0'
    | 'adfs'
    | 'okta'
    | 'ping'
    | 'snowflake'
    | 'unknown';
  /** Whether this connection-level OAuth configuration uses PKCE. */
  oauthUsePkce?: boolean | null;
  /** Whether this connection-level OAuth configuration uses JWT bearer token authentication. */
  oauthUseJwt?: boolean | null;
  /**
   * Audience used for OAuth federation, such as the Google workforce identity federation audience for BigQuery.
   */
  oauthAudience?: string;
  /** Whether this connection uses connection-level OAuth instead of organization-level OAuth. */
  isIndependentOAuth?: boolean;
  /** User attributes associated with the connection */
  userAttributes?: {
    role?: string;
    warehouse?: string;
  };
}

/** Response from {@link ConnectionsResource["get"] | get}. */
export interface GetConnectionResponse {
  /** Unique identifier of the organization */
  organizationId: string;
  /** Unique identifier of the connection */
  connectionId: string;
  /** Whether the connection is the Sigma sample data connection */
  isSample: boolean;
  /** Whether audit logging is enabled */
  isAuditLog: boolean;
  /** Last activity date and time */
  lastActiveAt: string;
  /** Name of the connection */
  name: string;
  /** Type of the connection (e.g., "bigQuery") */
  type: string;
  /** Whether OAuth is used */
  useOauth: boolean;
  /** Identifier of the user who created this connection */
  createdBy: string;
  /** Identifier of the user or process that last updated this connection */
  updatedBy: string;
  /** When the connection was created */
  createdAt: string;
  /** When the connection was last updated */
  updatedAt: string;
  /** Whether the connection is archived */
  isArchived?: boolean;
  /** Account associated with the connection */
  account?: string;
  /** Warehouse associated with the connection */
  warehouse?: string;
  /** User associated with the connection */
  user?: string;
  /** Role used by the connection user */
  role?: string;
  /** Timeout settings for the connection, with a default value in seconds */
  timeout?: {
    default: number;
    worksheet?: number;
    dashboard?: number;
    download?: number;
  };
  /** Pool sizes for the connection, such as for adhocPoolSize or schedulePoolSize */
  poolSizes?: {
    isPoolConfigured?: boolean;
    adhocPoolSize?: number;
    catalogPoolSize?: number;
    resultPoolSize?: number;
    schedulePoolSize?: number;
  };
  writeAccess?: boolean;
  /** Whether friendly names are enabled for this connection */
  friendlyName?: boolean;
  /** Configure write-back for non-OAuth connections */
  writebacks?: {
    database: string;
    schema: string;
    writebackSchemaId?: string;
  }[];
  /** Configure write-back for OAuth connections */
  writebackSchemas?: {
    database: string;
    schema: string;
    writebackSchemaId?: string;
  }[];
  /**
   * Schema to use for the input table write-ahead log (WAL). Cannot be changed without breaking write behavior on this connection.
   */
  inputTableAuditLogSchema?: {
    database: string;
    schema: string;
    writebackSchemaId?: string;
  };
  /** Warehouse used to run materialization jobs */
  materializationWarehouse?: string;
  /** Warehouse used to run export jobs */
  exportsWarehouse?: string;
  /** OAuth metadata URL configured directly on this connection. */
  oauthMetadataUrl?: string;
  /** Client ID configured directly on this connection. */
  oauthClientId?: string;
  /** OAuth scopes configured directly on this connection. */
  oauthScopes?: string[];
  /** OAuth provider type configured or inferred for this connection. */
  oauthIdpType?:
    | 'aws_databricks'
    | 'azure_databricks'
    | 'gcp_databricks'
    | 'azuread'
    | 'auth0'
    | 'adfs'
    | 'okta'
    | 'ping'
    | 'snowflake'
    | 'unknown';
  /** Whether this connection-level OAuth configuration uses PKCE. */
  oauthUsePkce?: boolean | null;
  /** Whether this connection-level OAuth configuration uses JWT bearer token authentication. */
  oauthUseJwt?: boolean | null;
  /**
   * Audience used for OAuth federation, such as the Google workforce identity federation audience for BigQuery.
   */
  oauthAudience?: string;
  /** Whether this connection uses connection-level OAuth instead of organization-level OAuth. */
  isIndependentOAuth?: boolean;
  /** User attributes associated with the connection */
  userAttributes?: {
    role?: string;
    warehouse?: string;
  };
}

/** Response from {@link ConnectionsResource["update"] | update}. */
export interface UpdateConnectionResponse {
  /** Unique identifier of the organization */
  organizationId: string;
  /** Unique identifier of the connection */
  connectionId: string;
  /** Whether the connection is the Sigma sample data connection */
  isSample: boolean;
  /** Whether audit logging is enabled */
  isAuditLog: boolean;
  /** Last activity date and time */
  lastActiveAt: string;
  /** Name of the connection */
  name: string;
  /** Type of the connection (e.g., "bigQuery") */
  type: string;
  /** Whether OAuth is used */
  useOauth: boolean;
  /** Identifier of the user who created this connection */
  createdBy: string;
  /** Identifier of the user or process that last updated this connection */
  updatedBy: string;
  /** When the connection was created */
  createdAt: string;
  /** When the connection was last updated */
  updatedAt: string;
  /** Whether the connection is archived */
  isArchived?: boolean;
  /** Account associated with the connection */
  account?: string;
  /** Warehouse associated with the connection */
  warehouse?: string;
  /** User associated with the connection */
  user?: string;
  /** Role used by the connection user */
  role?: string;
  /** Timeout settings for the connection, with a default value in seconds */
  timeout?: {
    default: number;
    worksheet?: number;
    dashboard?: number;
    download?: number;
  };
  /** Pool sizes for the connection, such as for adhocPoolSize or schedulePoolSize */
  poolSizes?: {
    isPoolConfigured?: boolean;
    adhocPoolSize?: number;
    catalogPoolSize?: number;
    resultPoolSize?: number;
    schedulePoolSize?: number;
  };
  writeAccess?: boolean;
  /** Whether friendly names are enabled for this connection */
  friendlyName?: boolean;
  /** Configure write-back for non-OAuth connections */
  writebacks?: {
    database: string;
    schema: string;
    writebackSchemaId?: string;
  }[];
  /** Configure write-back for OAuth connections */
  writebackSchemas?: {
    database: string;
    schema: string;
    writebackSchemaId?: string;
  }[];
  /**
   * Schema to use for the input table write-ahead log (WAL). Cannot be changed without breaking write behavior on this connection.
   */
  inputTableAuditLogSchema?: {
    database: string;
    schema: string;
    writebackSchemaId?: string;
  };
  /** Warehouse used to run materialization jobs */
  materializationWarehouse?: string;
  /** Warehouse used to run export jobs */
  exportsWarehouse?: string;
  /** OAuth metadata URL configured directly on this connection. */
  oauthMetadataUrl?: string;
  /** Client ID configured directly on this connection. */
  oauthClientId?: string;
  /** OAuth scopes configured directly on this connection. */
  oauthScopes?: string[];
  /** OAuth provider type configured or inferred for this connection. */
  oauthIdpType?:
    | 'aws_databricks'
    | 'azure_databricks'
    | 'gcp_databricks'
    | 'azuread'
    | 'auth0'
    | 'adfs'
    | 'okta'
    | 'ping'
    | 'snowflake'
    | 'unknown';
  /** Whether this connection-level OAuth configuration uses PKCE. */
  oauthUsePkce?: boolean | null;
  /** Whether this connection-level OAuth configuration uses JWT bearer token authentication. */
  oauthUseJwt?: boolean | null;
  /**
   * Audience used for OAuth federation, such as the Google workforce identity federation audience for BigQuery.
   */
  oauthAudience?: string;
  /** Whether this connection uses connection-level OAuth instead of organization-level OAuth. */
  isIndependentOAuth?: boolean;
  /** User attributes associated with the connection */
  userAttributes?: {
    role?: string;
    warehouse?: string;
  };
}

/** Response from {@link ConnectionsResource["updateDeprecated"] | updateDeprecated}. */
export interface UpdateConnectionDeprecatedResponse {
  /** Unique identifier of the organization */
  organizationId: string;
  /** Unique identifier of the connection */
  connectionId: string;
  /** Whether the connection is the Sigma sample data connection */
  isSample: boolean;
  /** Whether audit logging is enabled */
  isAuditLog: boolean;
  /** Last activity date and time */
  lastActiveAt: string;
  /** Name of the connection */
  name: string;
  /** Type of the connection (e.g., "bigQuery") */
  type: string;
  /** Whether OAuth is used */
  useOauth: boolean;
  /** Identifier of the user who created this connection */
  createdBy: string;
  /** Identifier of the user or process that last updated this connection */
  updatedBy: string;
  /** When the connection was created */
  createdAt: string;
  /** When the connection was last updated */
  updatedAt: string;
  /** Whether the connection is archived */
  isArchived?: boolean;
  /** Account associated with the connection */
  account?: string;
  /** Warehouse associated with the connection */
  warehouse?: string;
  /** User associated with the connection */
  user?: string;
  /** Role used by the connection user */
  role?: string;
  /** Timeout settings for the connection, with a default value in seconds */
  timeout?: {
    default: number;
    worksheet?: number;
    dashboard?: number;
    download?: number;
  };
  /** Pool sizes for the connection, such as for adhocPoolSize or schedulePoolSize */
  poolSizes?: {
    isPoolConfigured?: boolean;
    adhocPoolSize?: number;
    catalogPoolSize?: number;
    resultPoolSize?: number;
    schedulePoolSize?: number;
  };
  writeAccess?: boolean;
  /** Whether friendly names are enabled for this connection */
  friendlyName?: boolean;
  /** Configure write-back for non-OAuth connections */
  writebacks?: {
    database: string;
    schema: string;
    writebackSchemaId?: string;
  }[];
  /** Configure write-back for OAuth connections */
  writebackSchemas?: {
    database: string;
    schema: string;
    writebackSchemaId?: string;
  }[];
  /**
   * Schema to use for the input table write-ahead log (WAL). Cannot be changed without breaking write behavior on this connection.
   */
  inputTableAuditLogSchema?: {
    database: string;
    schema: string;
    writebackSchemaId?: string;
  };
  /** Warehouse used to run materialization jobs */
  materializationWarehouse?: string;
  /** Warehouse used to run export jobs */
  exportsWarehouse?: string;
  /** OAuth metadata URL configured directly on this connection. */
  oauthMetadataUrl?: string;
  /** Client ID configured directly on this connection. */
  oauthClientId?: string;
  /** OAuth scopes configured directly on this connection. */
  oauthScopes?: string[];
  /** OAuth provider type configured or inferred for this connection. */
  oauthIdpType?:
    | 'aws_databricks'
    | 'azure_databricks'
    | 'gcp_databricks'
    | 'azuread'
    | 'auth0'
    | 'adfs'
    | 'okta'
    | 'ping'
    | 'snowflake'
    | 'unknown';
  /** Whether this connection-level OAuth configuration uses PKCE. */
  oauthUsePkce?: boolean | null;
  /** Whether this connection-level OAuth configuration uses JWT bearer token authentication. */
  oauthUseJwt?: boolean | null;
  /**
   * Audience used for OAuth federation, such as the Google workforce identity federation audience for BigQuery.
   */
  oauthAudience?: string;
  /** Whether this connection uses connection-level OAuth instead of organization-level OAuth. */
  isIndependentOAuth?: boolean;
  /** User attributes associated with the connection */
  userAttributes?: {
    role?: string;
    warehouse?: string;
  };
}

/** Response from {@link ConnectionsResource["delete"] | delete}. */
export type DeleteConnectionResponse = Record<string, never>;

/** Response from {@link ConnectionsResource["postDbtArtifacts"] | postDbtArtifacts}. */
export type PostConnectionDbtArtifactsResponse = Record<string, never>;

/** Response from {@link ConnectionsResource["listGrants"] | listGrants}. */
export interface ListConnectionGrantsResponse {
  /** Array of results returned by the endpoint */
  entries: {
    grantId: string;
    inodeId: string;
    organizationId: string;
    memberId: string | null;
    teamId: string | null;
    permission:
      | 'admin'
      | 'annotate'
      | 'update'
      | 'usage'
      | 'writeback'
      | 'create'
      | 'organize'
      | 'explore'
      | 'view'
      | 'edit'
      | 'apply';
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
  }[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link ConnectionsResource["createGrant"] | createGrant}. */
export type CreateConnectionGrantResponse = Record<string, never>;

/** Response from {@link ConnectionsResource["deleteGrant"] | deleteGrant}. */
export type DeleteConnectionGrantResponse = Record<string, never>;

/** Response from {@link ConnectionsResource["syncPath"] | syncPath}. */
export type SyncConnectionPathResponse = Record<string, never>;

/** Response from {@link ConnectionsResource["test"] | test}. */
export interface TestConnectionResponse {
  read: 'SUCCESS' | 'FAILED';
  write: 'DISABLED' | 'SUCCESS' | 'FAILED';
}

/** Response from {@link ConnectionsResource["listPaths"] | listPaths}. */
export interface ListConnectionPathsResponse {
  /** Array of results returned by the endpoint */
  entries: {
    connectionId: string;
    urlId: string;
    path: string[] | string[] | string[];
  }[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link ConnectionsResource["listPathGrants"] | listPathGrants}. */
export interface ListConnectionPathGrantsResponse {
  entries: {
    grantId: string;
    inodeId: string;
    organizationId: string;
    memberId: string | null;
    teamId: string | null;
    permission:
      | 'admin'
      | 'annotate'
      | 'update'
      | 'usage'
      | 'writeback'
      | 'create'
      | 'organize'
      | 'explore'
      | 'view'
      | 'edit'
      | 'apply';
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
  }[];
  nextPage: string | null;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link ConnectionsResource["createPathGrant"] | createPathGrant}. */
export type CreateConnectionPathGrantResponse = Record<string, never>;

/** Response from {@link ConnectionsResource["deletePathGrant"] | deletePathGrant}. */
export type DeleteConnectionPathGrantResponse = Record<string, never>;

/** Response from {@link ConnectionsResource["getInodePath"] | getInodePath}. */
export interface GetInodeConnectionPathResponse {
  connectionId: string;
  path: string[] | string[] | string[];
}

/** Response from {@link ConnectionsResource["listTableColumns"] | listTableColumns}. */
export interface ListConnectionTableColumnsResponse {
  /** Array of results returned by the endpoint */
  entries: {
    name: string;
    type: Record<string, unknown>;
    visibility: 'included' | 'hidden' | 'removed';
    description?: string;
  }[];
  /**
   * A string that can be passed to the `pageToken` parameter in the next request to fetch the next page of results. Not present in the last page of results.
   * **Must be treated as an opaque string.**
   */
  nextPageToken?: string;
}

/** Response from {@link ConnectionsResource["createV3Alpha"] | createV3Alpha}. */
export interface V3alpha_createConnectionResponse {
  /** Unique identifier of the connection */
  connectionId: string;
  name: string;
  details: {
    type: 'databricks';
    serverHostname: string;
    httpPath: string;
    authentication:
      | {
          type: 'service-account';
          serviceAccount: {
            type: 'basic-auth';
          };
        }
      | {
          type: 'oauth';
          userCredential: {
            oauthConfig:
              | {
                  type: 'organization';
                }
              | {
                  type: 'connection';
                  scopes: string[];
                  metadataUri: string;
                  clientId: string;
                  usePkce: boolean;
                  useJwt: boolean;
                };
          };
          serviceAccount?: {
            type: 'basic-auth';
          };
        };
    writeAccess?: {
      writeDestinations: {
        destination: {
          catalog: string;
          schema: string;
        };
        description?: string;
      }[];
      inputTableAuditLogDestination?: {
        catalog: string;
        schema: string;
      };
    };
    settings?: {
      connectionTimeoutSecs?: number;
      connectionQueueSize?: number;
      useFriendlyNames?: boolean;
      enableHiveMetastore?: boolean;
    };
    python?: {
      computeClusterId: string;
    };
    sourceSwap?: {
      sourceSwapPolicyId: string;
    };
  };
}

/** Response from {@link ConnectionsResource["getV3Alpha"] | getV3Alpha}. */
export interface V3alpha_getConnectionResponse {
  /** Unique identifier of the connection */
  connectionId: string;
  name: string;
  details: {
    type: 'databricks';
    serverHostname: string;
    httpPath: string;
    authentication:
      | {
          type: 'service-account';
          serviceAccount: {
            type: 'basic-auth';
          };
        }
      | {
          type: 'oauth';
          userCredential: {
            oauthConfig:
              | {
                  type: 'organization';
                }
              | {
                  type: 'connection';
                  scopes: string[];
                  metadataUri: string;
                  clientId: string;
                  usePkce: boolean;
                  useJwt: boolean;
                };
          };
          serviceAccount?: {
            type: 'basic-auth';
          };
        };
    writeAccess?: {
      writeDestinations: {
        destination: {
          catalog: string;
          schema: string;
        };
        description?: string;
      }[];
      inputTableAuditLogDestination?: {
        catalog: string;
        schema: string;
      };
    };
    settings?: {
      connectionTimeoutSecs?: number;
      connectionQueueSize?: number;
      useFriendlyNames?: boolean;
      enableHiveMetastore?: boolean;
    };
    python?: {
      computeClusterId: string;
    };
    sourceSwap?: {
      sourceSwapPolicyId: string;
    };
  };
}

/** Response from {@link ConnectionsResource["patchV3Alpha"] | patchV3Alpha}. */
export interface V3alpha_patchConnectionResponse {
  /** Unique identifier of the connection */
  connectionId: string;
  name: string;
  details: {
    type: 'databricks';
    serverHostname: string;
    httpPath: string;
    authentication:
      | {
          type: 'service-account';
          serviceAccount: {
            type: 'basic-auth';
          };
        }
      | {
          type: 'oauth';
          userCredential: {
            oauthConfig:
              | {
                  type: 'organization';
                }
              | {
                  type: 'connection';
                  scopes: string[];
                  metadataUri: string;
                  clientId: string;
                  usePkce: boolean;
                  useJwt: boolean;
                };
          };
          serviceAccount?: {
            type: 'basic-auth';
          };
        };
    writeAccess?: {
      writeDestinations: {
        destination: {
          catalog: string;
          schema: string;
        };
        description?: string;
      }[];
      inputTableAuditLogDestination?: {
        catalog: string;
        schema: string;
      };
    };
    settings?: {
      connectionTimeoutSecs?: number;
      connectionQueueSize?: number;
      useFriendlyNames?: boolean;
      enableHiveMetastore?: boolean;
    };
    python?: {
      computeClusterId: string;
    };
    sourceSwap?: {
      sourceSwapPolicyId: string;
    };
  };
}

// ---------------------------------------------------------------------------
// Sub-resource accessors (hydration)
// ---------------------------------------------------------------------------

/** Sub-resource accessors available on hydrated connection entries. */
export interface ConnectionSubResources {
  grants: {
    /**
     * List grants for a connection
     *
     * Source docs: https://help.sigmacomputing.com/reference/listconnectiongrants
     *
     * Get a list of permissions granted to users or teams on a specific connection.
     *
     * ### Usage notes
     * - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
     *
     * @param query - Query parameters
     * @returns ListConnectionGrantsResponse
     */
    list(
      query?: ListConnectionGrantsQuery,
    ): Promise<DeepReadonly<ListConnectionGrantsResponse>>;
    /**
     * List grants for a connection (auto-paginate all pages)
     *
     * Source docs: https://help.sigmacomputing.com/reference/listconnectiongrants
     *
     * Get a list of permissions granted to users or teams on a specific connection.
     *
     * ### Usage notes
     * - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
     *
     * @param query - Query parameters
     * @yields ListConnectionGrantsResponse
     */
    listAll(
      query?: ListConnectionGrantsQuery,
    ): PaginatedAsyncGenerator<DeepReadonly<ListConnectionGrantsResponse>>;
    /**
     * Add grants to a connection
     *
     * Source docs: https://help.sigmacomputing.com/reference/createconnectiongrant
     *
     * Add grants to grant permissions on a connection to specific users or teams.
     *
     *   ### Usage notes
     *   - See [Data permissions overview](https://help.sigmacomputing.com/docs/data-permissions-overview) for details about permissions that can be granted on a connection.
     *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
     *   - Specify the team or user IDs to grant permissions:
     *
     *     - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
     *     - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
     *
     *   ### Usage scenarios
     *   - Grant a specific team `Can use` access to a connection.
     *
     * @param body - The request body.
     * @returns CreateConnectionGrantResponse
     */
    create(
      body: CreateConnectionGrantBody,
    ): Promise<DeepReadonly<CreateConnectionGrantResponse>>;
  };
  /**
   * Look up connections by path
   *
   * Source docs: https://help.sigmacomputing.com/reference/lookupconnection
   *
   * This endpoint returns details about the fully qualified path to an object in a specific connection by connection ID.
   *
   *   ### Usage notes
   *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *
   *   Different connections support different paths:
   *
   *   - For a Snowflake connection, you can specify `DATABASE.SCHEMA.TABLE`, `DATABASE.SCHEMA.STORED_PROCEDURE`, or a less-specific path.
   *   - For Amazon Redshift, you can specify `SCHEMA.TABLE`, `SCHEMA.STORED_PROCEDURE`, or a less-specific path.
   *   - For Databricks, you can specify `CATALOG.SCHEMA.TABLE` or a less-specific path.
   *
   *   Connection path details include the connection path ID, called the `inodeId` in the response, and the type of object in the connection path, either a table or a scope (database, schema, catalog, or other higher-level object).
   *
   * @param body - The request body.
   * @returns LookupConnectionResponse
   */
  lookup(
    body: LookupConnectionBody,
  ): Promise<DeepReadonly<LookupConnectionResponse>>;
  /**
   * Update a connection
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateconnectiondeprecated
   *
   * Update the metadata of a specific connection. This endpoint is deprecated. Instead, use the [PUT endpoint](https://help.sigmacomputing.com/reference/updateconnection).
   *
   * @param body - The request body.
   * @returns UpdateConnectionDeprecatedResponse
   */
  updateDeprecated(
    body: UpdateConnectionDeprecatedBody,
  ): Promise<DeepReadonly<UpdateConnectionDeprecatedResponse>>;
  /**
   * Add dbt metadata for a connection
   *
   * Source docs: https://help.sigmacomputing.com/reference/postconnectiondbtartifacts
   *
   * Add dbt run artifacts for a given connection. For more details, see [Configure dbt Core integration](doc:manage-dbt-integration#configure-dbt-core-integration-beta).
   *
   *   ### Usage notes
   *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *   - Create a tar.gz file containing the target directory of your dbt project that contains run artifacts.
   *   - Provide the file in the request with the field name 'artifacts'.
   *
   * @param body - The request body.
   * @returns PostConnectionDbtArtifactsResponse
   */
  postDbtArtifacts(
    body: PostConnectionDbtArtifactsBody,
  ): Promise<DeepReadonly<PostConnectionDbtArtifactsResponse>>;
  /**
   * Sync a connection by path
   *
   * Source docs: https://help.sigmacomputing.com/reference/syncconnectionpath
   *
   *
   *   Sync the connection for a data source to retrieve any changes from the data warehouse.
   *
   *   ### Usage notes
   *   - Specify the path to a table, stored procedure, schema, or database in your data warehouse that you want to sync.
   *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *   - Different connections support different paths:
   *
   *     - For a Snowflake connection, you can specify `DATABASE.SCHEMA.TABLE`, `DATABASE.SCHEMA.STORED_PROCEDURE`, or a less-specific path.
   *     - For Amazon Redshift, you can specify `SCHEMA.TABLE`, `SCHEMA.STORED_PROCEDURE`, or a less-specific path.
   *     - For Databricks, you can specify `CATALOG.SCHEMA.TABLE` or a less-specific path.
   *
   * @param body - The request body.
   * @param query - Query parameters
   * @returns SyncConnectionPathResponse
   */
  syncPath(
    body: SyncConnectionPathBody,
    query?: SyncConnectionPathQuery,
  ): Promise<DeepReadonly<SyncConnectionPathResponse>>;
  /**
   * Test a connection
   *
   * Source docs: https://help.sigmacomputing.com/reference/testconnection
   *
   * Test whether an existing connection allows read and write operations for the user associated with the API credentials.
   *
   *   ### Usage notes
   *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   * @returns TestConnectionResponse
   */
  test(): Promise<DeepReadonly<TestConnectionResponse>>;
}

/** A connection entry with sub-resource accessor methods. Response data properties are deeply readonly. */
export type HydratedConnection<T> = DeepReadonly<T> & ConnectionSubResources;

// ---------------------------------------------------------------------------
// ConnectionsResource
// ---------------------------------------------------------------------------

/** @internal Attach sub-resource accessors to a connection entry. */
function _hydrateConnection<T extends object>(
  entry: T,
  resource: ConnectionsResource,
): HydratedConnection<T> {
  return Object.assign(entry, {
    grants: {
      list: (query?: ListConnectionGrantsQuery) =>
        resource.listGrants((entry as any).connectionId, query),
      listAll: (query?: ListConnectionGrantsQuery) =>
        resource.listGrantsAll((entry as any).connectionId, query),
      create: (body: CreateConnectionGrantBody) =>
        resource.createGrant((entry as any).connectionId, body),
    },
    lookup: (body: LookupConnectionBody) =>
      resource.lookup((entry as any).connectionId, body),
    updateDeprecated: (body: UpdateConnectionDeprecatedBody) =>
      resource.updateDeprecated((entry as any).connectionId, body),
    postDbtArtifacts: (body: PostConnectionDbtArtifactsBody) =>
      resource.postDbtArtifacts((entry as any).connectionId, body),
    syncPath: (body: SyncConnectionPathBody, query?: SyncConnectionPathQuery) =>
      resource.syncPath((entry as any).connectionId, body, query),
    test: () => resource.test((entry as any).connectionId),
  }) as HydratedConnection<T>;
}

export class ConnectionsResource {
  constructor(private client: Client<paths>) {}

  /**
   * Look up connections by path
   *
   * Source docs: https://help.sigmacomputing.com/reference/lookupconnection
   *
   * This endpoint returns details about the fully qualified path to an object in a specific connection by connection ID.
   *
   *   ### Usage notes
   *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *
   *   Different connections support different paths:
   *
   *   - For a Snowflake connection, you can specify `DATABASE.SCHEMA.TABLE`, `DATABASE.SCHEMA.STORED_PROCEDURE`, or a less-specific path.
   *   - For Amazon Redshift, you can specify `SCHEMA.TABLE`, `SCHEMA.STORED_PROCEDURE`, or a less-specific path.
   *   - For Databricks, you can specify `CATALOG.SCHEMA.TABLE` or a less-specific path.
   *
   *   Connection path details include the connection path ID, called the `inodeId` in the response, and the type of object in the connection path, either a table or a scope (database, schema, catalog, or other higher-level object).
   *
   * @param connectionId
   * @param body - The request body.
   * @returns LookupConnectionResponse
   */
  async lookup(
    connectionId: string,
    body: LookupConnectionBody,
  ): Promise<DeepReadonly<LookupConnectionResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/connection/{connectionId}/lookup',
      { params: { path: { connectionId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List connections
   *
   * Source docs: https://help.sigmacomputing.com/reference/listconnections
   *
   * Get a list of available connections and the connection IDs.
   *
   * @param query - Query parameters
   * @returns ListConnectionsResponse
   */
  async list(
    query?: ListConnectionsQuery,
  ): Promise<HydratePage<ListConnectionsResponse, ConnectionSubResources>> {
    const { data, error, response } = await this.client.GET('/v2/connections', {
      params: { query },
    });
    if (error) throw new SigmaApiError(error, response);
    const result = data! as any;
    if (Array.isArray(result)) {
      return result.map((e: any) => _hydrateConnection(e, this)) as any;
    }
    if (result.entries && Array.isArray(result.entries)) {
      result.entries = result.entries.map((e: any) =>
        _hydrateConnection(e, this),
      );
    }
    return result;
  }

  /**
   * List connections (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listconnections
   *
   * Get a list of available connections and the connection IDs.
   *
   * @param query - Query parameters
   * @yields ListConnectionsResponse
   */
  listAll(
    query?: ListConnectionsQuery,
  ): PaginatedAsyncGenerator<
    HydratePage<ListConnectionsResponse, ConnectionSubResources>
  > {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list({
          ...query,
          page: cursor,
        } as ListConnectionsQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create a connection
   *
   * Source docs: https://help.sigmacomputing.com/reference/createconnection
   *
   * Create a connection to a cloud data warehouse from Sigma. For additional details, see [Connect to data sources](https://help.sigmacomputing.com/docs/connect-to-data-sources).
   *
   * @param body - The request body.
   * @returns CreateConnectionResponse
   */
  async create(
    body: CreateConnectionBody,
  ): Promise<HydratedConnection<CreateConnectionResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/connections',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return _hydrateConnection(data! as any, this);
  }

  /**
   * Get connection details
   *
   * Source docs: https://help.sigmacomputing.com/reference/getconnection
   *
   * Get the metadata of a specific connection by connection ID.
   *
   * ### Usage notes
   * - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *
   * @param connectionId
   * @returns GetConnectionResponse
   */
  async get(
    connectionId: string,
  ): Promise<HydratedConnection<GetConnectionResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/connections/{connectionId}',
      { params: { path: { connectionId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return _hydrateConnection(data! as any, this);
  }

  /**
   * Update a connection
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateconnection
   *
   * Update a specific connection by connection ID. When updating the connection, send any connection details that you want to keep. Retrieve the current state of a connection by calling the [/v2/connections/{connectionId}](getconnection) endpoint.
   *
   *   ### Usage notes
   *   - To restore a deleted connection, pass the `restore` parameter.
   *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *
   * @param connectionId
   * @param body - The request body.
   * @returns UpdateConnectionResponse
   */
  async update(
    connectionId: string,
    body: UpdateConnectionBody,
  ): Promise<HydratedConnection<UpdateConnectionResponse>> {
    const { data, error, response } = await this.client.PUT(
      '/v2/connections/{connectionId}',
      { params: { path: { connectionId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return _hydrateConnection(data! as any, this);
  }

  /**
   * Update a connection
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateconnectiondeprecated
   *
   * Update the metadata of a specific connection. This endpoint is deprecated. Instead, use the [PUT endpoint](https://help.sigmacomputing.com/reference/updateconnection).
   *
   * @param connectionId
   * @param body - The request body.
   * @returns UpdateConnectionDeprecatedResponse
   */
  async updateDeprecated(
    connectionId: string,
    body: UpdateConnectionDeprecatedBody,
  ): Promise<DeepReadonly<UpdateConnectionDeprecatedResponse>> {
    const { data, error, response } = await this.client.PATCH(
      '/v2/connections/{connectionId}',
      { params: { path: { connectionId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete a connection
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteconnection
   *
   * Delete a specific connection by connection ID.
   *
   *   ### Usage notes
   *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *
   * @param connectionId
   * @returns DeleteConnectionResponse
   */
  async delete(
    connectionId: string,
  ): Promise<DeepReadonly<DeleteConnectionResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/connections/{connectionId}',
      { params: { path: { connectionId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Add dbt metadata for a connection
   *
   * Source docs: https://help.sigmacomputing.com/reference/postconnectiondbtartifacts
   *
   * Add dbt run artifacts for a given connection. For more details, see [Configure dbt Core integration](doc:manage-dbt-integration#configure-dbt-core-integration-beta).
   *
   *   ### Usage notes
   *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *   - Create a tar.gz file containing the target directory of your dbt project that contains run artifacts.
   *   - Provide the file in the request with the field name 'artifacts'.
   *
   * @param connectionId - Unique identifier of the connection
   * @param body - The request body.
   * @returns PostConnectionDbtArtifactsResponse
   */
  async postDbtArtifacts(
    connectionId: string,
    body: PostConnectionDbtArtifactsBody,
  ): Promise<DeepReadonly<PostConnectionDbtArtifactsResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/connections/{connectionId}/dbtArtifacts',
      {
        params: { path: { connectionId } },
        body: body as never,
        bodySerializer: (b: unknown) => b,
      },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List grants for a connection
   *
   * Source docs: https://help.sigmacomputing.com/reference/listconnectiongrants
   *
   * Get a list of permissions granted to users or teams on a specific connection.
   *
   * ### Usage notes
   * - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *
   * @param connectionId
   * @param query - Query parameters
   * @returns ListConnectionGrantsResponse
   */
  async listGrants(
    connectionId: string,
    query?: ListConnectionGrantsQuery,
  ): Promise<DeepReadonly<ListConnectionGrantsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/connections/{connectionId}/grants',
      { params: { path: { connectionId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List grants for a connection (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listconnectiongrants
   *
   * Get a list of permissions granted to users or teams on a specific connection.
   *
   * ### Usage notes
   * - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *
   * @param connectionId
   * @param query - Query parameters
   * @yields ListConnectionGrantsResponse
   */
  listGrantsAll(
    connectionId: string,
    query?: ListConnectionGrantsQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListConnectionGrantsResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listGrants(connectionId, {
          ...query,
          page: cursor,
        } as ListConnectionGrantsQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Add grants to a connection
   *
   * Source docs: https://help.sigmacomputing.com/reference/createconnectiongrant
   *
   * Add grants to grant permissions on a connection to specific users or teams.
   *
   *   ### Usage notes
   *   - See [Data permissions overview](https://help.sigmacomputing.com/docs/data-permissions-overview) for details about permissions that can be granted on a connection.
   *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *   - Specify the team or user IDs to grant permissions:
   *
   *     - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *     - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *
   *   ### Usage scenarios
   *   - Grant a specific team `Can use` access to a connection.
   *
   * @param connectionId
   * @param body - The request body.
   * @returns CreateConnectionGrantResponse
   */
  async createGrant(
    connectionId: string,
    body: CreateConnectionGrantBody,
  ): Promise<DeepReadonly<CreateConnectionGrantResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/connections/{connectionId}/grants',
      { params: { path: { connectionId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete a grant for a connection
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteconnectiongrant
   *
   * Deletes a specific permission granted on a specific connection.
   *
   *   ### Usage notes
   *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *
   *   ### Usage scenarios
   *   - **Principle of least privilege**: Reduce the permissions granted to specific users and teams on a connection to only what is needed.
   *   - **User offboarding**: Remove connection permissions granted to a user that will be deactivated.
   *
   * @param connectionId
   * @param grantId
   * @returns DeleteConnectionGrantResponse
   */
  async deleteGrant(
    connectionId: string,
    grantId: string,
  ): Promise<DeepReadonly<DeleteConnectionGrantResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/connections/{connectionId}/grants/{grantId}',
      { params: { path: { connectionId, grantId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Sync a connection by path
   *
   * Source docs: https://help.sigmacomputing.com/reference/syncconnectionpath
   *
   *
   *   Sync the connection for a data source to retrieve any changes from the data warehouse.
   *
   *   ### Usage notes
   *   - Specify the path to a table, stored procedure, schema, or database in your data warehouse that you want to sync.
   *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *   - Different connections support different paths:
   *
   *     - For a Snowflake connection, you can specify `DATABASE.SCHEMA.TABLE`, `DATABASE.SCHEMA.STORED_PROCEDURE`, or a less-specific path.
   *     - For Amazon Redshift, you can specify `SCHEMA.TABLE`, `SCHEMA.STORED_PROCEDURE`, or a less-specific path.
   *     - For Databricks, you can specify `CATALOG.SCHEMA.TABLE` or a less-specific path.
   *
   * @param connectionId
   * @param body - The request body.
   * @param query - Query parameters
   * @returns SyncConnectionPathResponse
   */
  async syncPath(
    connectionId: string,
    body: SyncConnectionPathBody,
    query?: SyncConnectionPathQuery,
  ): Promise<DeepReadonly<SyncConnectionPathResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/connections/{connectionId}/sync',
      { params: { path: { connectionId }, query }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Test a connection
   *
   * Source docs: https://help.sigmacomputing.com/reference/testconnection
   *
   * Test whether an existing connection allows read and write operations for the user associated with the API credentials.
   *
   *   ### Usage notes
   *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *
   * @param connectionId
   * @returns TestConnectionResponse
   */
  async test(
    connectionId: string,
  ): Promise<DeepReadonly<TestConnectionResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/connections/{connectionId}/test',
      { params: { path: { connectionId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List connection paths
   *
   * Source docs: https://help.sigmacomputing.com/reference/listconnectionpaths
   *
   * List all paths for all connections available to the user.
   *
   *   ### Usage notes
   *   - Call this endpoint to retrieve the specific databases, catalogs, schemas, and tables available to the user associated with the API credentials.
   *
   * @param query - Query parameters
   * @returns ListConnectionPathsResponse
   */
  async listPaths(
    query?: ListConnectionPathsQuery,
  ): Promise<DeepReadonly<ListConnectionPathsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/connections/paths',
      { params: { query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List connection paths (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listconnectionpaths
   *
   * List all paths for all connections available to the user.
   *
   *   ### Usage notes
   *   - Call this endpoint to retrieve the specific databases, catalogs, schemas, and tables available to the user associated with the API credentials.
   *
   * @param query - Query parameters
   * @yields ListConnectionPathsResponse
   */
  listPathsAll(
    query?: ListConnectionPathsQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListConnectionPathsResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listPaths({
          ...query,
          page: cursor,
        } as ListConnectionPathsQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * List grants for a connection path
   *
   * Source docs: https://help.sigmacomputing.com/reference/listconnectionpathgrants
   *
   * Get a list of permissions granted to a specific connection path.
   *
   *   ### Usage notes
   *   - Retrieve the **connectionPathId** by calling the [/v2/connection/{connectionId}/lookup](lookupconnection) endpoint and using the `inodeId` included in the response, or by calling the [/v2/connections/paths](listconnectionpaths) endpoint and using the `urlId` included in the response.
   *
   * @param connectionPathId
   * @param query - Query parameters
   * @returns ListConnectionPathGrantsResponse
   */
  async listPathGrants(
    connectionPathId: string,
    query?: ListConnectionPathGrantsQuery,
  ): Promise<DeepReadonly<ListConnectionPathGrantsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/connections/paths/{connectionPathId}/grants',
      { params: { path: { connectionPathId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List grants for a connection path (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listconnectionpathgrants
   *
   * Get a list of permissions granted to a specific connection path.
   *
   *   ### Usage notes
   *   - Retrieve the **connectionPathId** by calling the [/v2/connection/{connectionId}/lookup](lookupconnection) endpoint and using the `inodeId` included in the response, or by calling the [/v2/connections/paths](listconnectionpaths) endpoint and using the `urlId` included in the response.
   *
   * @param connectionPathId
   * @param query - Query parameters
   * @yields ListConnectionPathGrantsResponse
   */
  listPathGrantsAll(
    connectionPathId: string,
    query?: ListConnectionPathGrantsQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListConnectionPathGrantsResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listPathGrants(connectionPathId, {
          ...query,
          page: cursor,
        } as ListConnectionPathGrantsQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Add grants to a connection path
   *
   * Source docs: https://help.sigmacomputing.com/reference/createconnectionpathgrant
   *
   * Add a grant to a specific connection path to grant permissions for users or teams.
   *
   *   ### Usage notes
   *   - Retrieve the **connectionPathId** by calling the [/v2/connection/{connectionId}/lookup](lookupconnection) endpoint and using the `inodeId` included in the response, or by calling the [/v2/connections/paths](listconnectionpaths) endpoint and using the `urlId` included in the response.
   *   - Specify the team or user IDs to grant permissions:
   *
   *     - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *     - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *
   * @param connectionPathId
   * @param body - The request body.
   * @returns CreateConnectionPathGrantResponse
   */
  async createPathGrant(
    connectionPathId: string,
    body: CreateConnectionPathGrantBody,
  ): Promise<DeepReadonly<CreateConnectionPathGrantResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/connections/paths/{connectionPathId}/grants',
      { params: { path: { connectionPathId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete a grant for a connection path
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteconnectionpathgrant
   *
   * Delete a specific permission granted to a specific connection path for a user or team.
   *
   *   ### Usage notes
   *   - Retrieve the **connectionPathId** by calling the [/v2/connection/{connectionId}/lookup](lookupconnection) endpoint and using the `inodeId` included in the response, or by calling the [/v2/connections/paths](listconnectionpaths) endpoint and using the `urlId` included in the response.
   *   - Retrieve the **grantId** by calling the [/v2/connections/paths/{connectionPathId}/grants](listconnectionpathgrants) endpoint.
   *
   * @param connectionPathId
   * @param grantId
   * @returns DeleteConnectionPathGrantResponse
   */
  async deletePathGrant(
    connectionPathId: string,
    grantId: string,
  ): Promise<DeepReadonly<DeleteConnectionPathGrantResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/connections/paths/{connectionPathId}/grants/{grantId}',
      { params: { path: { connectionPathId, grantId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get connection path for a table
   *
   * Source docs: https://help.sigmacomputing.com/reference/getinodeconnectionpath
   *
   * Get the connection path for a specific table. If the inodeId is not for a table, this endpoint returns an error.
   *
   *   ### Usage notes
   *   - Retrieve the **inodeId** by calling the [/v2/workbooks/{workbookId}/sources](getworkbooksources) or [/v2/datasets/{datasetId}/source](getdatasetsources) endpoint.
   *
   * @param inodeId
   * @returns GetInodeConnectionPathResponse
   */
  async getInodePath(
    inodeId: string,
  ): Promise<DeepReadonly<GetInodeConnectionPathResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/connections/paths/{inodeId}',
      { params: { path: { inodeId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List columns for a warehouse table
   *
   * Source docs: https://help.sigmacomputing.com/reference/listconnectiontablecolumns
   *
   * Returns column names, types, and other details for a table in a data warehouse connection.
   *
   * ### Usage notes
   * - Retrieve the **tableId** by first calling the [/v2/connections/paths](listconnectionpaths) endpoint to discover available paths, then calling the [/v2/connection/{connectionId}/lookup](lookupconnection) endpoint with the path to the desired table and using the `inodeId` included in the response.
   *
   * @param tableId
   * @param query - Query parameters
   * @returns ListConnectionTableColumnsResponse
   */
  async listTableColumns(
    tableId: string,
    query?: ListConnectionTableColumnsQuery,
  ): Promise<DeepReadonly<ListConnectionTableColumnsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/connections/tables/{tableId}/columns',
      { params: { path: { tableId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List columns for a warehouse table (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listconnectiontablecolumns
   *
   * Returns column names, types, and other details for a table in a data warehouse connection.
   *
   * ### Usage notes
   * - Retrieve the **tableId** by first calling the [/v2/connections/paths](listconnectionpaths) endpoint to discover available paths, then calling the [/v2/connection/{connectionId}/lookup](lookupconnection) endpoint with the path to the desired table and using the `inodeId` included in the response.
   *
   * @param tableId
   * @param query - Query parameters
   * @yields ListConnectionTableColumnsResponse
   */
  listTableColumnsAll(
    tableId: string,
    query?: ListConnectionTableColumnsQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListConnectionTableColumnsResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listTableColumns(tableId, {
          ...query,
          pageToken: cursor,
        } as ListConnectionTableColumnsQuery);
        yield page;
        cursor = (page as { nextPageToken?: string | null })[
          'nextPageToken'
        ] as string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create a connection (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/v3alpha_createconnection
   *
   * Create a connection to a cloud data warehouse from Sigma. For additional details, see [Connect to data sources](https://help.sigmacomputing.com/docs/connect-to-data-sources).
   *
   * **Beta**: This documentation describes a private beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage Notes
   * - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *
   * @param body - The request body.
   * @returns V3alpha_createConnectionResponse
   */
  async createV3Alpha(
    body: V3alpha_createConnectionBody,
  ): Promise<HydratedConnection<V3alpha_createConnectionResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v3alpha/connections',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return _hydrateConnection(data! as any, this);
  }

  /**
   * Get connection details (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/v3alpha_getconnection
   *
   * Get the metadata of a specific connection by connection ID.
   *
   * **Beta**: This documentation describes a private beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *
   * @param connectionId - Unique identifier of the connection
   * @returns V3alpha_getConnectionResponse
   */
  async getV3Alpha(
    connectionId: string,
  ): Promise<HydratedConnection<V3alpha_getConnectionResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v3alpha/connections/{connectionId}',
      { params: { path: { connectionId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return _hydrateConnection(data! as any, this);
  }

  /**
   * Update a connection (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/v3alpha_patchconnection
   *
   * Update a connection to a cloud data warehouse from Sigma. Only the options specified in your request are updated. Other options remain the same.
   *
   * **Beta**: This documentation describes a private beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *
   * ### Usage scenarios
   * - Remove an optional parameter by setting it to `null`. If the field has a default value, the field resets to the default.
   * - Update a field value by providing a new value.
   * - Leave a field unchanged by omitting it from the request.
   *
   * @param connectionId - Unique identifier of the connection
   * @param body - The request body.
   * @returns V3alpha_patchConnectionResponse
   */
  async patchV3Alpha(
    connectionId: string,
    body: V3alpha_patchConnectionBody,
  ): Promise<DeepReadonly<V3alpha_patchConnectionResponse>> {
    const { data, error, response } = await this.client.PATCH(
      '/v3alpha/connections/{connectionId}',
      { params: { path: { connectionId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
