// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link CredentialsResource["create"] | create}. */
export interface CreateCredentialsBody {
  /** Unique identifier of the user. */
  ownerId: string;
  /** Name of the credentials. */
  name: string;
  /** Description of the credentials */
  description?: string;
  /** Scopes to assign to the credentials. If not provided, defaults to "api". */
  scopes?: ('api' | 'embed')[];
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link CredentialsResource["create"] | create}. */
export interface CreateCredentialsResponse {
  clientId: string;
  clientSecret: string;
}

/** Response from {@link CredentialsResource["delete"] | delete}. */
export type DeleteCredentialsResponse = Record<string, never>;

// ---------------------------------------------------------------------------
// CredentialsResource
// ---------------------------------------------------------------------------

export class CredentialsResource {
  constructor(private client: Client<paths>) {}

  /**
   * Create API credentials
   *
   * Source docs: https://help.sigmacomputing.com/reference/createcredentials
   *
   * Create API client credentials for a given user. To make this request, your API client credentials must be associated with a Sigma admin user for the same Sigma organization.
   *
   *   **Important:** The response includes sensitive information. Ensure that you securely store and handle the returned `clientId` and `clientSecret`. These credentials grant access to your Sigma account and should never be exposed publicly or shared unnecessarily.
   *
   *   ### Usage Notes:
   *   - Retrieve the **ownerId** by calling the [/v2/members](listmembers) endpoint and using the `memberId` included in the response.
   *
   * @param body - The request body.
   * @returns CreateCredentialsResponse
   */
  async create(
    body: CreateCredentialsBody,
  ): Promise<DeepReadonly<CreateCredentialsResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/credentials',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete API credentials
   *
   * Source docs: https://help.sigmacomputing.com/reference/deletecredentials
   *
   * Revoke the API client credentials associated with a given client ID. To make this request, your API client credentials must be associated with a Sigma admin user for the same Sigma organization.
   *
   * @param clientId - Client ID of the credentials.
   * @returns DeleteCredentialsResponse
   */
  async delete(
    clientId: string,
  ): Promise<DeepReadonly<DeleteCredentialsResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/credentials/{clientId}',
      { params: { path: { clientId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
