// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { PaginatedAsyncGenerator, DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link DeploymentPoliciesResource["list"] | list}. */
export interface ListDeploymentsQuery {
  /**
   * Use to specify the next set of results with the string returned in the `nextPageToken` field of the previous response.
   */
  pageToken?: string;
  /** Number of results to return per page, with a maximum of 500. Defaults to 50. */
  pageSize?: number;
}

/** Query parameters for {@link DeploymentPoliciesResource["listInodesForDeployment"] | listInodesForDeployment}. */
export interface ListInodesForDeploymentQuery {
  /**
   * Use to specify the next set of results with the string returned in the `nextPageToken` field of the previous response.
   */
  pageToken?: string;
  /** Number of results to return per page, with a maximum of 500. Defaults to 50. */
  pageSize?: number;
}

/** Query parameters for {@link DeploymentPoliciesResource["listTenantsForDeployment"] | listTenantsForDeployment}. */
export interface ListTenantsForDeploymentQuery {
  /**
   * Use to specify the next set of results with the string returned in the `nextPageToken` field of the previous response.
   */
  pageToken?: string;
  /** Number of results to return per page, with a maximum of 500. Defaults to 50. */
  pageSize?: number;
}

/** Query parameters for {@link DeploymentPoliciesResource["listDeployableTenants"] | listDeployableTenants}. */
export interface ListDeployableTenantsQuery {
  /**
   * Use to specify the next set of results with the string returned in the `nextPageToken` field of the previous response.
   */
  pageToken?: string;
  /** Number of results to return per page, with a maximum of 500. Defaults to 50. */
  pageSize?: number;
  /** Search term to filter tenant organizations by name or slug. */
  search?: string;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link DeploymentPoliciesResource["create"] | create}. */
export interface CreateDeploymentBody {
  /** Name of the deployment policy. */
  name: string;
  versionTagId?: string;
  /** Unique identifiers of the source swap policies used to swap connections when deploying documents. */
  sourceSwapPolicies?: string[];
  /** Name to use for the workspace created by the deployment policy in the receiving tenant. */
  nameInTenant?: string;
}

/** Request body for {@link DeploymentPoliciesResource["addInodesToDeployment"] | addInodesToDeployment}. */
export interface AddInodesToDeploymentBody {
  /** Unique identifier of the document. */
  inodeIds: string[];
}

/** Request body for {@link DeploymentPoliciesResource["addTenantToDeployment"] | addTenantToDeployment}. */
export interface AddTenantToDeploymentBody {
  /** Unique identifier of the tenant organization. */
  tenantOrganizationId: string;
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link DeploymentPoliciesResource["list"] | list}. */
export interface ListDeploymentsResponse {
  /** Array of results returned by the endpoint */
  entries: {
    deploymentPolicyId: string;
    name: string;
    nameInTenant: string;
    versionTagId: string | null;
    sourceSwapPolicies: string[];
  }[];
  /**
   * A string that can be passed to the `pageToken` parameter in the next request to fetch the next page of results. Not present in the last page of results.
   * **Must be treated as an opaque string.**
   */
  nextPageToken?: string;
}

/** Response from {@link DeploymentPoliciesResource["create"] | create}. */
export interface CreateDeploymentResponse {
  deploymentPolicyId: string;
}

/** Response from {@link DeploymentPoliciesResource["get"] | get}. */
export interface GetDeploymentResponse {
  deploymentPolicyId: string;
  /** Name of the deployment policy */
  name: string;
  /** Name to use for the workspace created by the deployment policy in the receiving tenant. */
  nameInTenant: string;
  versionTagId: string | null;
  /** Unique identifiers of the source swap policies used to swap connections when deploying documents. */
  sourceSwapPolicies: string[];
}

/** Response from {@link DeploymentPoliciesResource["archive"] | archive}. */
export type ArchiveDeploymentResponse = Record<string, never>;

/** Response from {@link DeploymentPoliciesResource["listInodesForDeployment"] | listInodesForDeployment}. */
export interface ListInodesForDeploymentResponse {
  /** Array of results returned by the endpoint */
  entries: {
    inodeId: string;
    inode:
      | {
          name: string;
          type: 'workbook';
          workbookId: string;
        }
      | {
          name: string;
          type: 'dataModel';
          dataModelId: string;
        }
      | null;
    deploymentPolicyId: string;
  }[];
  /**
   * A string that can be passed to the `pageToken` parameter in the next request to fetch the next page of results. Not present in the last page of results.
   * **Must be treated as an opaque string.**
   */
  nextPageToken?: string;
}

/** Response from {@link DeploymentPoliciesResource["addInodesToDeployment"] | addInodesToDeployment}. */
export type AddInodesToDeploymentResponse = Record<string, never>;

/** Response from {@link DeploymentPoliciesResource["removeInodesFromDeployment"] | removeInodesFromDeployment}. */
export type RemoveInodesFromDeploymentResponse = Record<string, never>;

/** Response from {@link DeploymentPoliciesResource["listTenantsForDeployment"] | listTenantsForDeployment}. */
export interface ListTenantsForDeploymentResponse {
  /** Array of results returned by the endpoint */
  entries: string[];
  /**
   * A string that can be passed to the `pageToken` parameter in the next request to fetch the next page of results. Not present in the last page of results.
   * **Must be treated as an opaque string.**
   */
  nextPageToken?: string;
}

/** Response from {@link DeploymentPoliciesResource["addTenantToDeployment"] | addTenantToDeployment}. */
export type AddTenantToDeploymentResponse = Record<string, never>;

/** Response from {@link DeploymentPoliciesResource["removeTenantFromDeployment"] | removeTenantFromDeployment}. */
export type RemoveTenantFromDeploymentResponse = Record<string, never>;

/** Response from {@link DeploymentPoliciesResource["listDeployableTenants"] | listDeployableTenants}. */
export interface ListDeployableTenantsResponse {
  /** Array of results returned by the endpoint */
  entries: {
    tenantOrganizationId: string;
    tenantOrganizationSlug: string;
    tenantOrganizationName: string;
  }[];
  /**
   * A string that can be passed to the `pageToken` parameter in the next request to fetch the next page of results. Not present in the last page of results.
   * **Must be treated as an opaque string.**
   */
  nextPageToken?: string;
}

// ---------------------------------------------------------------------------
// DeploymentPoliciesResource
// ---------------------------------------------------------------------------

export class DeploymentPoliciesResource {
  constructor(private client: Client<paths>) {}

  /**
   * List deployment policies (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listdeployments
   *
   * List all deployment policies set up for an organization.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * @param query - Query parameters
   * @returns ListDeploymentsResponse
   */
  async list(
    query?: ListDeploymentsQuery,
  ): Promise<DeepReadonly<ListDeploymentsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/deploymentPolicies',
      { params: { query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List deployment policies (Beta) (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listdeployments
   *
   * List all deployment policies set up for an organization.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * @param query - Query parameters
   * @yields ListDeploymentsResponse
   */
  listAll(
    query?: ListDeploymentsQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListDeploymentsResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list({
          ...query,
          pageToken: cursor,
        } as ListDeploymentsQuery);
        yield page;
        cursor = (page as { nextPageToken?: string | null })[
          'nextPageToken'
        ] as string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create a deployment policy (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/createdeployment
   *
   * Create a deployment policy to define what documents to deploy to a tenant organization and how to swap sources for those documents.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the **versionTagId** by calling the [/v2/tags](listversiontag) endpoint.
   * - Retrieve the identifier for `sourceSwapPolicies` by calling the [/v2/sourceSwapPolicies](listsourceswappolicies) endpoint and using the `policyId` in the response.
   *
   * @param body - The request body.
   * @returns CreateDeploymentResponse
   */
  async create(
    body: CreateDeploymentBody,
  ): Promise<DeepReadonly<CreateDeploymentResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/deploymentPolicies',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get a deployment policy (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/getdeployment
   *
   * Get details for a deployment policy.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the `deploymentPolicyId` from the [/v2/deploymentPolicies](listdeployments) endpoint.
   *
   * @param deploymentPolicyId - Unique identifier of the deployment policy.
   * @returns GetDeploymentResponse
   */
  async get(
    deploymentPolicyId: string,
  ): Promise<DeepReadonly<GetDeploymentResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/deploymentPolicies/{deploymentPolicyId}',
      { params: { path: { deploymentPolicyId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Archive a deployment policy (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/archivedeployment
   *
   * Archive a deployment policy.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the `deploymentPolicyId` from the [/v2/deploymentPolicies](listdeployments) endpoint.
   *
   * @param deploymentPolicyId - Unique identifier of the deployment policy.
   * @returns ArchiveDeploymentResponse
   */
  async archive(
    deploymentPolicyId: string,
  ): Promise<DeepReadonly<ArchiveDeploymentResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/deploymentPolicies/{deploymentPolicyId}',
      { params: { path: { deploymentPolicyId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List documents for a deployment policy (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listinodesfordeployment
   *
   * List documents for a deployment policy
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the `deploymentPolicyId` from the [/v2/deploymentPolicies](listdeployments) endpoint.
   * - If the user associated with the API key does not have access to the document, the `inode` field is `null`.
   *
   * ### Usage scenarios
   * - Review and audit documents deployed to specific tenant organizations.
   *
   * @param deploymentPolicyId - Unique identifier of the deployment policy.
   * @param query - Query parameters
   * @returns ListInodesForDeploymentResponse
   */
  async listInodesForDeployment(
    deploymentPolicyId: string,
    query?: ListInodesForDeploymentQuery,
  ): Promise<DeepReadonly<ListInodesForDeploymentResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/deploymentPolicies/{deploymentPolicyId}/files',
      { params: { path: { deploymentPolicyId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List documents for a deployment policy (Beta) (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listinodesfordeployment
   *
   * List documents for a deployment policy
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the `deploymentPolicyId` from the [/v2/deploymentPolicies](listdeployments) endpoint.
   * - If the user associated with the API key does not have access to the document, the `inode` field is `null`.
   *
   * ### Usage scenarios
   * - Review and audit documents deployed to specific tenant organizations.
   *
   * @param deploymentPolicyId - Unique identifier of the deployment policy.
   * @param query - Query parameters
   * @yields ListInodesForDeploymentResponse
   */
  listInodesForDeploymentAll(
    deploymentPolicyId: string,
    query?: ListInodesForDeploymentQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListInodesForDeploymentResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listInodesForDeployment(
          deploymentPolicyId,
          { ...query, pageToken: cursor } as ListInodesForDeploymentQuery,
        );
        yield page;
        cursor = (page as { nextPageToken?: string | null })[
          'nextPageToken'
        ] as string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Add documents to a deployment policy (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/addinodestodeployment
   *
   * Add documents to a deployment policy.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the `deploymentPolicyId` from the [/v2/deploymentPolicies](listdeployments) endpoint.
   * - To add workbooks to a deployment policy, retrieve the relevant `workbookId` from the [/v2/workbooks](listworkbooks) endpoint.
   * - To add data models to a deployment policy, retrieve the relevant `dataModelId` from the [/v2/datamodels](listdatamodels) endpoint.
   *
   * ### Usage scenarios
   * - Centrally manage documents that are deployed to specific tenant organizations.
   *
   * @param deploymentPolicyId - Unique identifier of the deployment policy.
   * @param body - The request body.
   * @returns AddInodesToDeploymentResponse
   */
  async addInodesToDeployment(
    deploymentPolicyId: string,
    body: AddInodesToDeploymentBody,
  ): Promise<DeepReadonly<AddInodesToDeploymentResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/deploymentPolicies/{deploymentPolicyId}/files',
      { params: { path: { deploymentPolicyId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Remove a document from a deployment policy (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/removeinodesfromdeployment
   *
   * Remove a document from a deployment policy.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the `deploymentPolicyId` from the [/v2/deploymentPolicies](listdeployments) endpoint.
   * - To remove workbooks from a deployment policy, retrieve the relevant `workbookId` from the [/v2/workbooks](listworkbooks) endpoint.
   * - To remove data models from a deployment policy, retrieve the relevant `dataModelId` from the [/v2/datamodels](listdatamodels) endpoint.
   *
   * ### Usage scenarios
   * - Revoke access to outdated documents from tenant organizations.
   *
   * @param deploymentPolicyId
   * @param inodeId
   * @returns RemoveInodesFromDeploymentResponse
   */
  async removeInodesFromDeployment(
    deploymentPolicyId: string,
    inodeId: string,
  ): Promise<DeepReadonly<RemoveInodesFromDeploymentResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/deploymentPolicies/{deploymentPolicyId}/files/{inodeId}',
      { params: { path: { deploymentPolicyId, inodeId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List tenants for a deployment policy (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listtenantsfordeployment
   *
   * List tenants for a deployment policy.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the `deploymentPolicyId` from the [/v2/deploymentPolicies](listdeployments) endpoint.
   *
   * ### Usage scenarios
   * - Review and audit documents deployed to specific tenant organizations.
   *
   * @param deploymentPolicyId - Unique identifier of the deployment policy.
   * @param query - Query parameters
   * @returns ListTenantsForDeploymentResponse
   */
  async listTenantsForDeployment(
    deploymentPolicyId: string,
    query?: ListTenantsForDeploymentQuery,
  ): Promise<DeepReadonly<ListTenantsForDeploymentResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/deploymentPolicies/{deploymentPolicyId}/tenants',
      { params: { path: { deploymentPolicyId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List tenants for a deployment policy (Beta) (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listtenantsfordeployment
   *
   * List tenants for a deployment policy.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the `deploymentPolicyId` from the [/v2/deploymentPolicies](listdeployments) endpoint.
   *
   * ### Usage scenarios
   * - Review and audit documents deployed to specific tenant organizations.
   *
   * @param deploymentPolicyId - Unique identifier of the deployment policy.
   * @param query - Query parameters
   * @yields ListTenantsForDeploymentResponse
   */
  listTenantsForDeploymentAll(
    deploymentPolicyId: string,
    query?: ListTenantsForDeploymentQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListTenantsForDeploymentResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listTenantsForDeployment(
          deploymentPolicyId,
          { ...query, pageToken: cursor } as ListTenantsForDeploymentQuery,
        );
        yield page;
        cursor = (page as { nextPageToken?: string | null })[
          'nextPageToken'
        ] as string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Add a tenant to a deployment policy (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/addtenanttodeployment
   *
   * Add a tenant to a deployment policy.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the `deploymentPolicyId` from the [/v2/deploymentPolicies](listdeployments) endpoint.
   * - Retrieve the `tenantId` from the [/v2/tenants](listtenants) endpoint.
   *
   * ### Usage scenarios
   * - Deploy documents in a deployment policy to a specific tenant organization.
   *
   * @param deploymentPolicyId - Unique identifier of a deployment policy.
   * @param body - The request body.
   * @returns AddTenantToDeploymentResponse
   */
  async addTenantToDeployment(
    deploymentPolicyId: string,
    body: AddTenantToDeploymentBody,
  ): Promise<DeepReadonly<AddTenantToDeploymentResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/deploymentPolicies/{deploymentPolicyId}/tenants',
      { params: { path: { deploymentPolicyId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Remove a tenant from a deployment policy (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/removetenantfromdeployment
   *
   * Remove a tenant from a deployment policy.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the `deploymentPolicyId` from the [/v2/deploymentPolicies](listdeployments) endpoint.
   * - Retrieve the `tenantOrganizationId` from the [/v2/tenants](listtenants) endpoint or from the [/v2/deploymentPolicies/{deploymentPolicyId}/tenants](listtenantsfordeployment) endpoint.
   *
   * ### Usage scenarios
   * - Remove documents in a deployment policy from a tenant organization.
   * - Clean up tenant assignments when a tenant is no longer needed.
   *
   * @param deploymentPolicyId - Unique identifier of a deployment policy.
   * @param tenantOrganizationId - Unique identifier of the tenant organization.
   * @returns RemoveTenantFromDeploymentResponse
   */
  async removeTenantFromDeployment(
    deploymentPolicyId: string,
    tenantOrganizationId: string,
  ): Promise<DeepReadonly<RemoveTenantFromDeploymentResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/deploymentPolicies/{deploymentPolicyId}/tenants/{tenantOrganizationId}',
      { params: { path: { deploymentPolicyId, tenantOrganizationId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List deployable tenant organizations (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listdeployabletenants
   *
   * Returns a paginated list of tenant organizations that the calling organization can deploy to.
   *
   * - **Parent organizations**: Returns all tenant organizations.
   * - **Tenant organizations**: Returns tenant organizations that the calling tenant has been granted deployment capabilities to.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned an account type with the **Manage deployment policies** permission enabled.
   *
   * @param query - Query parameters
   * @returns ListDeployableTenantsResponse
   */
  async listDeployableTenants(
    query?: ListDeployableTenantsQuery,
  ): Promise<DeepReadonly<ListDeployableTenantsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/deploymentPolicies/tenants',
      { params: { query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List deployable tenant organizations (Beta) (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listdeployabletenants
   *
   * Returns a paginated list of tenant organizations that the calling organization can deploy to.
   *
   * - **Parent organizations**: Returns all tenant organizations.
   * - **Tenant organizations**: Returns tenant organizations that the calling tenant has been granted deployment capabilities to.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned an account type with the **Manage deployment policies** permission enabled.
   *
   * @param query - Query parameters
   * @yields ListDeployableTenantsResponse
   */
  listDeployableTenantsAll(
    query?: ListDeployableTenantsQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListDeployableTenantsResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listDeployableTenants({
          ...query,
          pageToken: cursor,
        } as ListDeployableTenantsQuery);
        yield page;
        cursor = (page as { nextPageToken?: string | null })[
          'nextPageToken'
        ] as string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }
}
