// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { PaginatedAsyncGenerator, DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link FavoritesResource["list"] | list}. */
export interface ListFavoritesQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link FavoritesResource["add"] | add}. */
export interface AddFavoriteBody {
  /** Unique identifier of the member. */
  memberId: string;
  /** Unique identifier of the document or folder. */
  inodeId: string;
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link FavoritesResource["add"] | add}. */
export type AddFavoriteResponse = Record<string, never>;

/** Response from {@link FavoritesResource["list"] | list}. */
export interface ListFavoritesResponse {
  /** Array of results returned by the endpoint */
  entries: (
    | {
        id: string;
        urlId: string;
        name: string;
        type:
          | 'workspace'
          | 'folder'
          | 'workbook'
          | 'dataset'
          | 'data-model'
          | 'sql'
          | 'worksheet'
          | 'dashboard'
          | 'template'
          | 'table'
          | 'symlink'
          | 'report';
        parentId: string;
        parentUrlId: string;
        permission:
          | 'create'
          | 'annotate'
          | 'organize'
          | 'explore'
          | 'view'
          | 'edit'
          | 'apply';
        path: string;
        badge: string | null;
        isArchived: boolean;
        description?: string;
        ownerId?: string | null;
        parentSourceUrlId?: string;
        createdBy: string;
        updatedBy: string;
        createdAt: string;
        updatedAt: string;
      }
    | {
        code: number;
        message: string;
        requestId: string;
      }
  )[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link FavoritesResource["remove"] | remove}. */
export type RemoveFavoriteResponse = Record<string, never>;

// ---------------------------------------------------------------------------
// FavoritesResource
// ---------------------------------------------------------------------------

export class FavoritesResource {
  constructor(private client: Client<paths>) {}

  /**
   * Favorite a document
   *
   * Source docs: https://help.sigmacomputing.com/reference/addfavorite
   *
   * Favorite a folder or document for a specific user.
   *
   *   ### Usage notes
   *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *   - Retrieve the **inodeId** by calling the [/v2/files](fileslist) endpoint and using the `id` included in the response.
   *
   * @param body - The request body.
   * @returns AddFavoriteResponse
   */
  async add(body: AddFavoriteBody): Promise<DeepReadonly<AddFavoriteResponse>> {
    const { data, error, response } = await this.client.POST('/v2/favorites', {
      body,
    });
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get favorite documents for a user
   *
   * Source docs: https://help.sigmacomputing.com/reference/listfavorites
   *
   * Get the favorite documents for a specific user. This endpoint has the same functionality as the [List all favorite documents of a member](https://help.sigmacomputing.com/reference/listfavoriteinodes) endpoint.
   *
   *   ### Usage notes
   *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *
   * @param memberId - Unique identifier of the member.
   * @param query - Query parameters
   * @returns ListFavoritesResponse
   */
  async list(
    memberId: string,
    query?: ListFavoritesQuery,
  ): Promise<DeepReadonly<ListFavoritesResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/favorites/member/{memberId}',
      { params: { path: { memberId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get favorite documents for a user (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listfavorites
   *
   * Get the favorite documents for a specific user. This endpoint has the same functionality as the [List all favorite documents of a member](https://help.sigmacomputing.com/reference/listfavoriteinodes) endpoint.
   *
   *   ### Usage notes
   *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *
   * @param memberId - Unique identifier of the member.
   * @param query - Query parameters
   * @yields ListFavoritesResponse
   */
  listAll(
    memberId: string,
    query?: ListFavoritesQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListFavoritesResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list(memberId, {
          ...query,
          page: cursor,
        } as ListFavoritesQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Unfavorite a document
   *
   * Source docs: https://help.sigmacomputing.com/reference/removefavorite
   *
   * Unfavorite a folder or document for a specific user.
   *
   *   ### Usage notes
   *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *   - Retrieve the **inodeId** by calling the [/v2/files](fileslist) endpoint and using the **id** included in the response.
   *
   * @param memberId - Unique identifier of the member.
   * @param inodeId - Unique identifier of the document or folder.
   * @returns RemoveFavoriteResponse
   */
  async remove(
    memberId: string,
    inodeId: string,
  ): Promise<DeepReadonly<RemoveFavoriteResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/favorites/member/{memberId}/file/{inodeId}',
      { params: { path: { memberId, inodeId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
