// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { PaginatedAsyncGenerator, DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link FilesResource["list"] | list}. */
export interface FilesListQuery {
  name?: string;
  permissionFilter?: 'view' | 'explore' | 'edit' | 'organize';
  typeFilters?:
    | (
        | 'workspace'
        | 'folder'
        | 'workbook'
        | 'dataset'
        | 'data-model'
        | 'sql'
        | 'worksheet'
        | 'dashboard'
        | 'template'
        | 'table'
        | 'symlink'
        | 'report'
      )[]
    | 'workspace'
    | 'folder'
    | 'workbook'
    | 'dataset'
    | 'data-model'
    | 'sql'
    | 'worksheet'
    | 'dashboard'
    | 'template'
    | 'table'
    | 'symlink'
    | 'report';
  page?: string;
  limit?: number;
  /** Parent folder */
  parentId?: string;
  directChildFilter?: boolean;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Workspace to create */
export interface FilesCreateBody_WorkspaceDetails {
  type: 'workspace';
  name: string;
}

export interface FilesCreateBody_FolderDetails {
  type: 'folder';
  name: string;
  description?: string;
  ownerId?: string;
  parentId?: string;
}

export interface FilesCreateBody_WorkbookDetails {
  type: 'workbook';
  name: string;
  description?: string;
  ownerId?: string;
  parentId?: string;
  source?: {
    inodeId: string;
    version: number;
  };
}

export interface FilesCreateBody_ReportDetails {
  type: 'report';
  name: string;
  description?: string;
  ownerId?: string;
  parentId?: string;
}

/** Request body for {@link FilesResource["create"] | create}. */
export type FilesCreateBody =
  | FilesCreateBody_WorkspaceDetails
  | FilesCreateBody_FolderDetails
  | FilesCreateBody_WorkbookDetails
  | FilesCreateBody_ReportDetails;

/** Request body for {@link FilesResource["update"] | update}. */
export interface FilesUpdateBody {
  name?: string;
  description?: string;
  ownerId?: string;
  /** Folder ID to contain the folder or document */
  parentId?: string;
  restore?: boolean;
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link FilesResource["list"] | list}. */
export interface FilesListResponse {
  /** Array of results returned by the endpoint */
  entries: (
    | {
        id: string;
        urlId: string;
        name: string;
        type:
          | 'workspace'
          | 'folder'
          | 'workbook'
          | 'dataset'
          | 'data-model'
          | 'sql'
          | 'worksheet'
          | 'dashboard'
          | 'template'
          | 'table'
          | 'symlink'
          | 'report';
        parentId: string;
        parentUrlId: string;
        permission:
          | 'create'
          | 'annotate'
          | 'organize'
          | 'explore'
          | 'view'
          | 'edit'
          | 'apply';
        path: string;
        badge: string | null;
        isArchived: boolean;
        description?: string;
        ownerId?: string | null;
        parentSourceUrlId?: string;
        createdBy: string;
        updatedBy: string;
        createdAt: string;
        updatedAt: string;
      }
    | {
        code: number;
        message: string;
        requestId: string;
      }
  )[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link FilesResource["create"] | create}. */
export interface FilesCreateResponse {
  id: string;
  urlId: string;
  name: string;
  type:
    | 'workspace'
    | 'folder'
    | 'workbook'
    | 'dataset'
    | 'data-model'
    | 'sql'
    | 'worksheet'
    | 'dashboard'
    | 'template'
    | 'table'
    | 'symlink'
    | 'report';
  parentId: string;
  parentUrlId: string;
  permission:
    'create' | 'annotate' | 'organize' | 'explore' | 'view' | 'edit' | 'apply';
  path: string;
  badge: string | null;
  isArchived: boolean;
  description?: string;
  ownerId?: string | null;
  /**
   * For a document deployed to a tenant organization, the `urlId` of the source document in the parent organization. Only present when the document was deployed from a parent organization. The source document can be a workbook, template, data model, dataset, or report.
   */
  parentSourceUrlId?: string;
  /** The identifier of the user who created this object. */
  createdBy: string;
  /** The identifier of the user or process that last updated this object. */
  updatedBy: string;
  /** When the object was created. */
  createdAt: string;
  /** When the object was last updated. */
  updatedAt: string;
}

/** Response from {@link FilesResource["get"] | get}. */
export interface FilesGetResponse {
  id: string;
  urlId: string;
  name: string;
  type:
    | 'workspace'
    | 'folder'
    | 'workbook'
    | 'dataset'
    | 'data-model'
    | 'sql'
    | 'worksheet'
    | 'dashboard'
    | 'template'
    | 'table'
    | 'symlink'
    | 'report';
  parentId: string;
  parentUrlId: string;
  permission:
    'create' | 'annotate' | 'organize' | 'explore' | 'view' | 'edit' | 'apply';
  path: string;
  badge: string | null;
  isArchived: boolean;
  description?: string;
  ownerId?: string | null;
  /**
   * For a document deployed to a tenant organization, the `urlId` of the source document in the parent organization. Only present when the document was deployed from a parent organization. The source document can be a workbook, template, data model, dataset, or report.
   */
  parentSourceUrlId?: string;
  /** The identifier of the user who created this object. */
  createdBy: string;
  /** The identifier of the user or process that last updated this object. */
  updatedBy: string;
  /** When the object was created. */
  createdAt: string;
  /** When the object was last updated. */
  updatedAt: string;
}

/** Response from {@link FilesResource["update"] | update}. */
export interface FilesUpdateResponse {
  id: string;
  urlId: string;
  name: string;
  type:
    | 'workspace'
    | 'folder'
    | 'workbook'
    | 'dataset'
    | 'data-model'
    | 'sql'
    | 'worksheet'
    | 'dashboard'
    | 'template'
    | 'table'
    | 'symlink'
    | 'report';
  parentId: string;
  parentUrlId: string;
  permission:
    'create' | 'annotate' | 'organize' | 'explore' | 'view' | 'edit' | 'apply';
  path: string;
  badge: string | null;
  isArchived: boolean;
  description?: string;
  ownerId?: string | null;
  /**
   * For a document deployed to a tenant organization, the `urlId` of the source document in the parent organization. Only present when the document was deployed from a parent organization. The source document can be a workbook, template, data model, dataset, or report.
   */
  parentSourceUrlId?: string;
  /** The identifier of the user who created this object. */
  createdBy: string;
  /** The identifier of the user or process that last updated this object. */
  updatedBy: string;
  /** When the object was created. */
  createdAt: string;
  /** When the object was last updated. */
  updatedAt: string;
}

/** Response from {@link FilesResource["delete"] | delete}. */
export type FilesDeleteResponse = Record<string, never>;

// ---------------------------------------------------------------------------
// FilesResource
// ---------------------------------------------------------------------------

export class FilesResource {
  constructor(private client: Client<paths>) {}

  /**
   * List files
   *
   * Source docs: https://help.sigmacomputing.com/reference/fileslist
   *
   * List all documents, such as workbooks and folders, accessible from the parent.
   *
   *   ### Which files are returned by this endpoint
   *
   *   The documents and folders accessible through this endpoint match those returned when you search in the Sigma UI. Some documents that you can view in the Sigma UI are not returned by this endpoint.
   *
   *   - Returned documents and folders are limited to those that you have access to, such as through ownership, a document directly shared with you, a document link shared with you that you have opened, or access inherited through a folder or a workspace. This restriction also applies to users granted the Admin account type.
   *   - Newly created files are not returned immediately after creation. Updated files are reflected immediately.
   *   - If no `typeFilters` are set, only workbooks, folders, data models, datasets (deprecated), and reports are returned. To return other file types, such as a shortcut (symlink), specify a file type using the `typeFilters` option.
   *
   *   ### Usage notes
   *
   *   - Use the **parentId** to specify a folder and return details about the nested files and documents:
   *     - Retrieve the ID to use as a **parentId** by calling the [/v2/files](fileslist) endpoint and reviewing the `id` field in the response for files with a `type` of `folder`.
   *     - To use the "My Documents" folder as the parent folder, call the [/v2/members/{memberId}](getmember) endpoint and use the `homeFolderId` included in the response.
   *     - If parentId is not specified, it is assumed to be the root.
   *   - Use the available filters to return files that contain a specific keyword in the name, files with specific permissions granted to the user associated with the API credentials, or files of a specific type.
   *
   * @param query - Query parameters
   * @returns FilesListResponse
   */
  async list(query?: FilesListQuery): Promise<DeepReadonly<FilesListResponse>> {
    const { data, error, response } = await this.client.GET('/v2/files', {
      params: { query },
    });
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List files (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/fileslist
   *
   * List all documents, such as workbooks and folders, accessible from the parent.
   *
   *   ### Which files are returned by this endpoint
   *
   *   The documents and folders accessible through this endpoint match those returned when you search in the Sigma UI. Some documents that you can view in the Sigma UI are not returned by this endpoint.
   *
   *   - Returned documents and folders are limited to those that you have access to, such as through ownership, a document directly shared with you, a document link shared with you that you have opened, or access inherited through a folder or a workspace. This restriction also applies to users granted the Admin account type.
   *   - Newly created files are not returned immediately after creation. Updated files are reflected immediately.
   *   - If no `typeFilters` are set, only workbooks, folders, data models, datasets (deprecated), and reports are returned. To return other file types, such as a shortcut (symlink), specify a file type using the `typeFilters` option.
   *
   *   ### Usage notes
   *
   *   - Use the **parentId** to specify a folder and return details about the nested files and documents:
   *     - Retrieve the ID to use as a **parentId** by calling the [/v2/files](fileslist) endpoint and reviewing the `id` field in the response for files with a `type` of `folder`.
   *     - To use the "My Documents" folder as the parent folder, call the [/v2/members/{memberId}](getmember) endpoint and use the `homeFolderId` included in the response.
   *     - If parentId is not specified, it is assumed to be the root.
   *   - Use the available filters to return files that contain a specific keyword in the name, files with specific permissions granted to the user associated with the API credentials, or files of a specific type.
   *
   * @param query - Query parameters
   * @yields FilesListResponse
   */
  listAll(
    query?: FilesListQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<FilesListResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list({
          ...query,
          page: cursor,
        } as FilesListQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create a file
   *
   * Source docs: https://help.sigmacomputing.com/reference/filescreate
   *
   * Create an empty workspace, folder, workbook, or report in Sigma.
   *
   *   ### Usage notes
   *   - Specify a **parentId** for a folder, workbook, or report to place it within another folder. Retrieve the ID to use as a **parentId** by calling the [/v2/files](fileslist) endpoint and reviewing the `id` field in the response for files with a `type` of `folder`.
   *   - Specify an **ownerId** for a folder, workbook, or report to create it on behalf of another user. Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *
   *   ### Usage scenarios
   *   - **Project onboarding**: Start a new project by creating a workspace and folders to contain the workbooks for the project.
   *
   * @param body - The request body.
   * @returns FilesCreateResponse
   */
  async create(
    body: FilesCreateBody,
  ): Promise<DeepReadonly<FilesCreateResponse>> {
    const { data, error, response } = await this.client.POST('/v2/files', {
      body,
    });
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get file information
   *
   * Source docs: https://help.sigmacomputing.com/reference/filesget
   *
   * Get information about a specific document or folder, such as a workbook, report, or data model.
   *
   *   ### Usage notes
   *   - Retrieve the **inodeId** by calling the [/v2/files](fileslist) endpoint and using the `id` included in the response.
   *   - Retrieve the **inodeId** for a data model by calling the [/v2/members/{memberId}/files/recents](listrecentinodes) endpoint and using the `id` included in the response.
   *
   * @param inodeId
   * @returns FilesGetResponse
   */
  async get(inodeId: string): Promise<DeepReadonly<FilesGetResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/files/{inodeId}',
      { params: { path: { inodeId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Update a file
   *
   * Source docs: https://help.sigmacomputing.com/reference/filesupdate
   *
   * Update a folder or document, such as a workbook, data model, or report.
   *
   *   ### Usage notes
   *   - Retrieve the **inodeId** by calling the [/v2/files](fileslist) endpoint and using the `id` included in the response.
   *   - Specify a **parentId** to place the document within a folder. Retrieve the ID to use as a **parentId** by calling the [/v2/files](fileslist) endpoint and reviewing the `id` field in the response for files with a `type` of `folder`.
   *   - To restore a deleted folder or document, set the **restore** parameter to `true`.
   *
   * @param inodeId
   * @param body - The request body.
   * @returns FilesUpdateResponse
   */
  async update(
    inodeId: string,
    body: FilesUpdateBody,
  ): Promise<DeepReadonly<FilesUpdateResponse>> {
    const { data, error, response } = await this.client.PATCH(
      '/v2/files/{inodeId}',
      { params: { path: { inodeId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete a file
   *
   * Source docs: https://help.sigmacomputing.com/reference/filesdelete
   *
   * Delete a folder or document, such as a workbook, data model, or report.
   *
   *   ### Usage notes
   *   - Retrieve the **inodeId** by calling the [/v2/files](fileslist) endpoint and using the `id` included in the response.
   *
   * @param inodeId
   * @returns FilesDeleteResponse
   */
  async delete(inodeId: string): Promise<DeepReadonly<FilesDeleteResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/files/{inodeId}',
      { params: { path: { inodeId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
