// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { PaginatedAsyncGenerator, DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link GrantsResource["list"] | list}. */
export interface ListGrantsQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
  inodeId?: string;
  teamId?: string;
  userId?: string;
  directGrantsOnly?: boolean;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link GrantsResource["upsert"] | upsert}. */
export interface UpsertGrantBody {
  grantee:
    | {
        memberId: string;
      }
    | {
        teamId: string;
      };
  permission:
    | 'admin'
    | 'annotate'
    | 'update'
    | 'usage'
    | 'writeback'
    | 'create'
    | 'organize'
    | 'explore'
    | 'view'
    | 'edit'
    | 'apply';
  inodeId: string;
  tagId?: string;
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link GrantsResource["list"] | list}. */
export interface ListGrantsResponse {
  /** Array of results returned by the endpoint */
  entries: {
    grantId: string;
    organizationId: string;
    memberId: string | null;
    teamId: string | null;
    permission:
      | 'admin'
      | 'annotate'
      | 'update'
      | 'usage'
      | 'writeback'
      | 'create'
      | 'organize'
      | 'explore'
      | 'view'
      | 'edit'
      | 'apply';
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
    urlId: string;
    inodeType:
      | 'folder'
      | 'customFunction'
      | 'symlink'
      | 'versionTag'
      | 'worksheet'
      | 'block'
      | 'dashboard'
      | 'report'
      | 'table'
      | 'semanticView'
      | 'metricView'
      | 'scope'
      | 'sql'
      | 'workbook'
      | 'template'
      | 'dataset'
      | 'datafile'
      | 'storedProcedure'
      | 'apiConnector'
      | 'apiConnectorAuth'
      | 'mcpConnector'
      | 'warehouseAgent'
      | 'agentSkill'
      | 'tlsProfile';
  }[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link GrantsResource["upsert"] | upsert}. */
export interface UpsertGrantResponse {
  /** The unique identifier of the grant */
  grantId: string;
  /** The unique identifier of the organization */
  organizationId: string;
  /** The unique identifier of the member */
  memberId: string | null;
  /** The unique identifier of the team */
  teamId: string | null;
  /** The permission granted to the member */
  permission:
    | 'admin'
    | 'annotate'
    | 'update'
    | 'usage'
    | 'writeback'
    | 'create'
    | 'organize'
    | 'explore'
    | 'view'
    | 'edit'
    | 'apply';
  /** The identifier of the user who created this grant */
  createdBy: string;
  /** The identifier of the user or process that last updated this grant */
  updatedBy: string;
  /** When the grant was created */
  createdAt: string;
  /** When the grant was last updated */
  updatedAt: string;
  /**
   * Sigma API bug: grant.inodeId returns the URL slug instead of the UUID for all inode types (workbooks, folders, data models, etc.). urlId makes this explicit. Remove when Sigma fixes the inconsistency.
   */
  urlId: string;
  inodeType:
    | 'folder'
    | 'customFunction'
    | 'symlink'
    | 'versionTag'
    | 'worksheet'
    | 'block'
    | 'dashboard'
    | 'report'
    | 'table'
    | 'semanticView'
    | 'metricView'
    | 'scope'
    | 'sql'
    | 'workbook'
    | 'template'
    | 'dataset'
    | 'datafile'
    | 'storedProcedure'
    | 'apiConnector'
    | 'apiConnectorAuth'
    | 'mcpConnector'
    | 'warehouseAgent'
    | 'agentSkill'
    | 'tlsProfile';
}

/** Response from {@link GrantsResource["get"] | get}. */
export interface GetGrantResponse {
  /** The unique identifier of the grant */
  grantId: string;
  /** The unique identifier of the organization */
  organizationId: string;
  /** The unique identifier of the member */
  memberId: string | null;
  /** The unique identifier of the team */
  teamId: string | null;
  /** The permission granted to the member */
  permission:
    | 'admin'
    | 'annotate'
    | 'update'
    | 'usage'
    | 'writeback'
    | 'create'
    | 'organize'
    | 'explore'
    | 'view'
    | 'edit'
    | 'apply';
  /** The identifier of the user who created this grant */
  createdBy: string;
  /** The identifier of the user or process that last updated this grant */
  updatedBy: string;
  /** When the grant was created */
  createdAt: string;
  /** When the grant was last updated */
  updatedAt: string;
  /**
   * Sigma API bug: grant.inodeId returns the URL slug instead of the UUID for all inode types (workbooks, folders, data models, etc.). urlId makes this explicit. Remove when Sigma fixes the inconsistency.
   */
  urlId: string;
  inodeType:
    | 'folder'
    | 'customFunction'
    | 'symlink'
    | 'versionTag'
    | 'worksheet'
    | 'block'
    | 'dashboard'
    | 'report'
    | 'table'
    | 'semanticView'
    | 'metricView'
    | 'scope'
    | 'sql'
    | 'workbook'
    | 'template'
    | 'dataset'
    | 'datafile'
    | 'storedProcedure'
    | 'apiConnector'
    | 'apiConnectorAuth'
    | 'mcpConnector'
    | 'warehouseAgent'
    | 'agentSkill'
    | 'tlsProfile';
}

/** Response from {@link GrantsResource["delete"] | delete}. */
export interface DeleteGrantResponse {
  /** The unique identifier of the grant */
  grantId: string;
  /** The unique identifier of the organization */
  organizationId: string;
  /** The unique identifier of the member */
  memberId: string | null;
  /** The unique identifier of the team */
  teamId: string | null;
  /** The permission granted to the member */
  permission:
    | 'admin'
    | 'annotate'
    | 'update'
    | 'usage'
    | 'writeback'
    | 'create'
    | 'organize'
    | 'explore'
    | 'view'
    | 'edit'
    | 'apply';
  /** The identifier of the user who created this grant */
  createdBy: string;
  /** The identifier of the user or process that last updated this grant */
  updatedBy: string;
  /** When the grant was created */
  createdAt: string;
  /** When the grant was last updated */
  updatedAt: string;
  /**
   * Sigma API bug: grant.inodeId returns the URL slug instead of the UUID for all inode types (workbooks, folders, data models, etc.). urlId makes this explicit. Remove when Sigma fixes the inconsistency.
   */
  urlId: string;
  inodeType:
    | 'folder'
    | 'customFunction'
    | 'symlink'
    | 'versionTag'
    | 'worksheet'
    | 'block'
    | 'dashboard'
    | 'report'
    | 'table'
    | 'semanticView'
    | 'metricView'
    | 'scope'
    | 'sql'
    | 'workbook'
    | 'template'
    | 'dataset'
    | 'datafile'
    | 'storedProcedure'
    | 'apiConnector'
    | 'apiConnectorAuth'
    | 'mcpConnector'
    | 'warehouseAgent'
    | 'agentSkill'
    | 'tlsProfile';
}

// ---------------------------------------------------------------------------
// GrantsResource
// ---------------------------------------------------------------------------

export class GrantsResource {
  constructor(private client: Client<paths>) {}

  /**
   * List grants
   *
   * Source docs: https://help.sigmacomputing.com/reference/listgrants
   *
   * List all grants for a given object.
   *
   *   ### Usage notes
   *
   *   You can specify one of the following:
   *
   *   - A user by userId. Retrieve the **userId** by calling the [/v2/members](listmembers) endpoint and using the `memberId` included in the response.
   *   - A team by teamId. Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *   - A document (such as a workbook, report, data model, or dataset (deprecated)), folder, or workspace by inodeId.
   *     - Retrieve the **inodeId** by calling the [/v2/files](fileslist) endpoint and using the `id` included in the response.
   *     - Retrieve the **inodeId** for a data model by calling the [/v2/dataModels](listdatamodels) endpoint and using the `dataModelId` included in the response.
   *
   *   ### Usage scenarios
   *   - **Manage inherited permissions**: Identify files and folders that have permissions directly granted to them.
   *   - **Review long-lived permissions**: Audit permissions granted more than a year ago and determine if they are still needed.
   *
   * @param query - Query parameters
   * @returns ListGrantsResponse
   *
   * @remarks SDK patch: `urlId` is substituted for `inodeId` in the response. Sigma API bug: grant.inodeId returns the URL slug instead of the UUID for all inode types (workbooks, folders, data models, etc.). urlId makes this explicit. Remove when Sigma fixes the inconsistency.
   */
  async list(
    query?: ListGrantsQuery,
  ): Promise<DeepReadonly<ListGrantsResponse>> {
    const { data, error, response } = await this.client.GET('/v2/grants', {
      params: { query },
    });
    if (error) throw new SigmaApiError(error, response);
    return {
      ...data!,
      entries:
        (data! as any).entries?.map(({ inodeId, ...rest }: any) => {
          if (!/^[A-Za-z0-9]+$/.test(inodeId))
            throw new Error(
              `[SDK patch] inodeId value "${inodeId}" (exposed as urlId) does not match /^[A-Za-z0-9]+$/. The upstream API may have changed — review FIELD_ALIASES in scripts/lib/response-patching.ts.`,
            );
          return { ...rest, urlId: inodeId };
        }) ?? [],
    } as any;
  }

  /**
   * List grants (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listgrants
   *
   * List all grants for a given object.
   *
   *   ### Usage notes
   *
   *   You can specify one of the following:
   *
   *   - A user by userId. Retrieve the **userId** by calling the [/v2/members](listmembers) endpoint and using the `memberId` included in the response.
   *   - A team by teamId. Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *   - A document (such as a workbook, report, data model, or dataset (deprecated)), folder, or workspace by inodeId.
   *     - Retrieve the **inodeId** by calling the [/v2/files](fileslist) endpoint and using the `id` included in the response.
   *     - Retrieve the **inodeId** for a data model by calling the [/v2/dataModels](listdatamodels) endpoint and using the `dataModelId` included in the response.
   *
   *   ### Usage scenarios
   *   - **Manage inherited permissions**: Identify files and folders that have permissions directly granted to them.
   *   - **Review long-lived permissions**: Audit permissions granted more than a year ago and determine if they are still needed.
   *
   * @param query - Query parameters
   * @yields ListGrantsResponse
   *
   * @remarks SDK patch: `urlId` is substituted for `inodeId` in the response. Sigma API bug: grant.inodeId returns the URL slug instead of the UUID for all inode types (workbooks, folders, data models, etc.). urlId makes this explicit. Remove when Sigma fixes the inconsistency.
   */
  listAll(
    query?: ListGrantsQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListGrantsResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list({
          ...query,
          page: cursor,
        } as ListGrantsQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create or update a grant
   *
   * Source docs: https://help.sigmacomputing.com/reference/creategrant
   *
   * Create a grant or update an existing grant on a document, folder, or workspace to a user or a team by ID.
   *
   *   ### Usage notes
   *   - This endpoint can only be used to escalate the level of access that a user has to a document. To remove or reduce a user's access to a specific document, call [/v2/grants/{grantId}](deletegrant) to delete the existing grant and re-grant the desired level of access.
   *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *   - Retrieve the **inodeId** by calling the [/v2/files](fileslist) endpoint and using the `id` included in the response.
   *   - Retrieve the **inodeId** for a data model by calling the [/v2/dataModels](listdatamodels) endpoint and using the `dataModelId` included in the response.
   *   - Optionally specify a **tagId** to associate the permission with a specific version tag of a workbook, dataset (deprecated), or database table. Retrieve the **tagId** by calling the [/v2/tags](listversiontag) endpoint and using the `versionTagId` included in the response.
   *
   * @param body - The request body.
   * @returns UpsertGrantResponse
   *
   * @remarks SDK patch: `urlId` is substituted for `inodeId` in the response. Sigma API bug: grant.inodeId returns the URL slug instead of the UUID for all inode types (workbooks, folders, data models, etc.). urlId makes this explicit. Remove when Sigma fixes the inconsistency.
   */
  async upsert(
    body: UpsertGrantBody,
  ): Promise<DeepReadonly<UpsertGrantResponse>> {
    const { data, error, response } = await this.client.POST('/v2/grants', {
      body,
    });
    if (error) throw new SigmaApiError(error, response);
    const { inodeId, ...rest } = data! as any;
    if (!/^[A-Za-z0-9]+$/.test(inodeId))
      throw new Error(
        `[SDK patch] inodeId value "${inodeId}" (exposed as urlId) does not match /^[A-Za-z0-9]+$/. The upstream API may have changed — review FIELD_ALIASES in scripts/lib/response-patching.ts.`,
      );
    return { ...rest, urlId: inodeId } as any;
  }

  /**
   * Get a grant
   *
   * Source docs: https://help.sigmacomputing.com/reference/getgrant
   *
   * Return a grant object by grant ID.
   *
   *   ### Usage notes
   *
   *   Depending on the grant object that you want to return details about, you can retrieve the grantId in different ways:
   *
   *   - For most documents, you can retrieve the **grantId** by calling the [/v2/grants](listgrants) endpoint with the **inodeId** for the document. For example, use the **workbookId** as the **inodeId**.
   *   - For a dataset (deprecated), you can also retrieve the **grantId** by calling the [/v2/datasets/{datasetId}/grants](listdatasetgrants) endpoint.
   *   - For a connection path, you can retrieve the **grantId** by calling the [/v2/connections/paths/{connectionPathId}/grants](listconnectionpathgrants) endpoint.
   *
   * @param grantId
   * @returns GetGrantResponse
   *
   * @remarks SDK patch: `urlId` is substituted for `inodeId` in the response. Sigma API bug: grant.inodeId returns the URL slug instead of the UUID for all inode types (workbooks, folders, data models, etc.). urlId makes this explicit. Remove when Sigma fixes the inconsistency.
   */
  async get(grantId: string): Promise<DeepReadonly<GetGrantResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/grants/{grantId}',
      { params: { path: { grantId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    const { inodeId, ...rest } = data! as any;
    if (!/^[A-Za-z0-9]+$/.test(inodeId))
      throw new Error(
        `[SDK patch] inodeId value "${inodeId}" (exposed as urlId) does not match /^[A-Za-z0-9]+$/. The upstream API may have changed — review FIELD_ALIASES in scripts/lib/response-patching.ts.`,
      );
    return { ...rest, urlId: inodeId } as any;
  }

  /**
   * Delete a grant
   *
   * Source docs: https://help.sigmacomputing.com/reference/deletegrant
   *
   * Delete a grant by grant ID.
   *
   *   ### Usage notes
   *   Depending on the grant object that you want to delete, you can retrieve the grantId in different ways:
   *
   *   - For most documents, you can retrieve the **grantId** by calling the [/v2/grants](listgrants) endpoint with the **inodeId** for the document. For example, use the **workbookId** as the **inodeId**.
   *   - For a dataset (deprecated), you can also retrieve the **grantId** by calling the [/v2/datasets/{datasetId}/grants](listdatasetgrants) endpoint.
   *   - For a connection path, you can retrieve the **grantId** by calling the [/v2/connections/paths/{connectionPathId}/grants](listconnectionpathgrants) endpoint.
   *
   *   ### Usage scenarios
   *   - **Principle of least privilege**: Revoke unnecessary privileges on a document by removing the grant.
   *
   * @param grantId
   * @returns DeleteGrantResponse
   *
   * @remarks SDK patch: `urlId` is substituted for `inodeId` in the response. Sigma API bug: grant.inodeId returns the URL slug instead of the UUID for all inode types (workbooks, folders, data models, etc.). urlId makes this explicit. Remove when Sigma fixes the inconsistency.
   */
  async delete(grantId: string): Promise<DeepReadonly<DeleteGrantResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/grants/{grantId}',
      { params: { path: { grantId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    const { inodeId, ...rest } = data! as any;
    if (!/^[A-Za-z0-9]+$/.test(inodeId))
      throw new Error(
        `[SDK patch] inodeId value "${inodeId}" (exposed as urlId) does not match /^[A-Za-z0-9]+$/. The upstream API may have changed — review FIELD_ALIASES in scripts/lib/response-patching.ts.`,
      );
    return { ...rest, urlId: inodeId } as any;
  }
}
