// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths, operations, components } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import {
  PaginatedAsyncGenerator,
  DeepReadonly,
  HydratePage,
} from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link MembersResource["list_v2"] | list_v2}. */
export interface List_v2_MembersQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
  /** **[Deprecated]** Use the `email` query parameter instead. */
  search?: string;
  /** Filter by email address. You must URL encode the "@" character as `%40`. */
  email?: string;
  includeArchived?: boolean;
  includeInactive?: boolean;
}

/** Query parameters for {@link MembersResource["create"] | create}. */
export interface CreateMemberQuery {
  /** Whether to send an email invitation for non-embed users. If not included, an email is sent */
  sendInvite?: boolean;
}

/** Query parameters for {@link MembersResource["listAccessibleInodes"] | listAccessibleInodes}. */
export interface ListAccessibleInodesQuery {
  name?: string;
  permissionFilter?: 'view' | 'explore' | 'edit' | 'organize';
  typeFilters?:
    | (
        | 'workspace'
        | 'folder'
        | 'workbook'
        | 'dataset'
        | 'data-model'
        | 'sql'
        | 'worksheet'
        | 'dashboard'
        | 'template'
        | 'table'
        | 'symlink'
        | 'report'
      )[]
    | 'workspace'
    | 'folder'
    | 'workbook'
    | 'dataset'
    | 'data-model'
    | 'sql'
    | 'worksheet'
    | 'dashboard'
    | 'template'
    | 'table'
    | 'symlink'
    | 'report';
  page?: string;
  limit?: number;
  /** Parent folder */
  parentId?: string;
  directChildFilter?: boolean;
}

/** Query parameters for {@link MembersResource["listFavoriteInodes"] | listFavoriteInodes}. */
export interface ListFavoriteInodesQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

/** Query parameters for {@link MembersResource["listRecentInodes"] | listRecentInodes}. */
export interface ListRecentInodesQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
  /** Include explorations in the response. */
  includeExplorations?: 'true' | 'false';
}

/** Query parameters for {@link MembersResource["listSchedules"] | listSchedules}. */
export interface ListMemberSchedulesQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

/** Query parameters for {@link MembersResource["listTeams"] | listTeams}. */
export interface ListMemberTeamsQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

/** Query parameters for {@link MembersResource["list"] | list}. */
export interface ListMembersQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
  /** **[Deprecated]** Use the `email` query parameter instead. */
  search?: string;
  /** Filter by email address. You must URL encode the "@" character as `%40`. */
  email?: string;
  includeArchived?: boolean;
  includeInactive?: boolean;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link MembersResource["create"] | create}. */
export type CreateMemberBody = NonNullable<
  operations['createMember']['requestBody']
>['content']['application/json'];

/** Request body for {@link MembersResource["update"] | update}. */
export interface UpdateMemberBody {
  /** Account type */
  memberType?: string;
  firstName?: string;
  lastName?: string;
  profileImgUrl?: string | null;
  email?: string;
  /** Whether to deactivate a user in Sigma. */
  isArchived?: boolean;
  /** Whether to archive a user with SCIM. */
  isInactive?: boolean;
  userKind?: 'internal' | 'guest' | 'embed';
  newOwnerId?: string;
  /**
   * Archive a user's documents instead of transferring them. Can only be used if either `isArchived` or `isInactive` is set to `true`. Also archives scheduled exports.
   */
  archiveDocuments?: boolean;
  /**
   * Archive a user's scheduled exports instead of transferring them. Can only be used if either `isArchived` or `isInactive` is set to `true`
   */
  archiveScheduledExports?: boolean;
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

export type List_v2_MembersResponse_Variant1 = {
  organizationId: string;
  memberId: string;
  memberType: string;
  firstName: string;
  lastName: string;
  email: string;
  profileImgUrl: string | null;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  homeFolderId: string;
  userKind: string;
  isArchived?: boolean;
  isInactive?: boolean;
}[];

export interface List_v2_MembersResponse_Variant2 {
  entries: {
    organizationId: string;
    memberId: string;
    memberType: string;
    firstName: string;
    lastName: string;
    email: string;
    profileImgUrl: string | null;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
    homeFolderId: string;
    userKind: string;
    isArchived?: boolean;
    isInactive?: boolean;
  }[];
  nextPage: string | null;
}

/** Response from {@link MembersResource["list_v2"] | list_v2}. */
export type List_v2_MembersResponse =
  List_v2_MembersResponse_Variant1 | List_v2_MembersResponse_Variant2;

/** Response from {@link MembersResource["create"] | create}. */
export interface CreateMemberResponse {
  organizationId: string;
  memberId: string;
  memberType: string;
  firstName: string;
  lastName: string;
  email: string;
  profileImgUrl: string | null;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  /** ID of the My Documents folder for the user */
  homeFolderId: string;
  userKind: string;
  /** Whether a user is deactivated in Sigma. */
  isArchived?: boolean;
  /** Whether a user is archived by SCIM. */
  isInactive?: boolean;
}

/** Response from {@link MembersResource["get"] | get}. */
export interface GetMemberResponse {
  organizationId: string;
  memberId: string;
  memberType: string;
  firstName: string;
  lastName: string;
  email: string;
  profileImgUrl: string | null;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  /** ID of the My Documents folder for the user */
  homeFolderId: string;
  userKind: string;
  /** Whether a user is deactivated in Sigma. */
  isArchived?: boolean;
  /** Whether a user is archived by SCIM. */
  isInactive?: boolean;
}

/** Response from {@link MembersResource["update"] | update}. */
export interface UpdateMemberResponse {
  organizationId: string;
  memberId: string;
  memberType: string;
  firstName: string;
  lastName: string;
  email: string;
  profileImgUrl: string | null;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  /** ID of the My Documents folder for the user */
  homeFolderId: string;
  userKind: string;
  /** Whether a user is deactivated in Sigma. */
  isArchived?: boolean;
  /** Whether a user is archived by SCIM. */
  isInactive?: boolean;
}

/** Response from {@link MembersResource["delete"] | delete}. */
export type DeleteMemberResponse = Record<string, never>;

/** Response from {@link MembersResource["listAccessibleInodes"] | listAccessibleInodes}. */
export interface ListAccessibleInodesResponse {
  /** Array of results returned by the endpoint */
  entries: (
    | {
        id: string;
        urlId: string;
        name: string;
        type:
          | 'workspace'
          | 'folder'
          | 'workbook'
          | 'dataset'
          | 'data-model'
          | 'sql'
          | 'worksheet'
          | 'dashboard'
          | 'template'
          | 'table'
          | 'symlink'
          | 'report';
        parentId: string;
        parentUrlId: string;
        permission:
          | 'create'
          | 'annotate'
          | 'organize'
          | 'explore'
          | 'view'
          | 'edit'
          | 'apply';
        path: string;
        badge: string | null;
        isArchived: boolean;
        description?: string;
        ownerId?: string | null;
        parentSourceUrlId?: string;
        createdBy: string;
        updatedBy: string;
        createdAt: string;
        updatedAt: string;
      }
    | {
        code: number;
        message: string;
        requestId: string;
      }
  )[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link MembersResource["listFavoriteInodes"] | listFavoriteInodes}. */
export interface ListFavoriteInodesResponse {
  /** Array of results returned by the endpoint */
  entries: (
    | {
        id: string;
        urlId: string;
        name: string;
        type:
          | 'workspace'
          | 'folder'
          | 'workbook'
          | 'dataset'
          | 'data-model'
          | 'sql'
          | 'worksheet'
          | 'dashboard'
          | 'template'
          | 'table'
          | 'symlink'
          | 'report';
        parentId: string;
        parentUrlId: string;
        permission:
          | 'create'
          | 'annotate'
          | 'organize'
          | 'explore'
          | 'view'
          | 'edit'
          | 'apply';
        path: string;
        badge: string | null;
        isArchived: boolean;
        description?: string;
        ownerId?: string | null;
        parentSourceUrlId?: string;
        createdBy: string;
        updatedBy: string;
        createdAt: string;
        updatedAt: string;
      }
    | {
        code: number;
        message: string;
        requestId: string;
      }
  )[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link MembersResource["listRecentInodes"] | listRecentInodes}. */
export interface ListRecentInodesResponse {
  /** Array of results returned by the endpoint */
  entries: (
    | {
        id: string;
        urlId: string;
        name: string;
        type:
          | 'workspace'
          | 'folder'
          | 'workbook'
          | 'dataset'
          | 'data-model'
          | 'sql'
          | 'worksheet'
          | 'dashboard'
          | 'template'
          | 'table'
          | 'symlink'
          | 'report';
        parentId: string;
        parentUrlId: string;
        permission:
          | 'create'
          | 'annotate'
          | 'organize'
          | 'explore'
          | 'view'
          | 'edit'
          | 'apply';
        path: string;
        badge: string | null;
        isArchived: boolean;
        description?: string;
        ownerId?: string | null;
        parentSourceUrlId?: string;
        createdBy: string;
        updatedBy: string;
        createdAt: string;
        updatedAt: string;
        lastInteractionAt?: string;
      }
    | {
        code: number;
        message: string;
        requestId: string;
      }
  )[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link MembersResource["listSchedules"] | listSchedules}. */
export interface ListMemberSchedulesResponse {
  /** Array of results returned by the endpoint */
  entries: (
    | {
        scheduledNotificationId: string;
        workbookId: string;
        schedule: {
          cronSpec: string;
          timezone: string;
        };
        configV2: {
          title: string;
          messageBody: string;
          notificationAttachments: {
            formatOptions:
              | {
                  type: 'CSV';
                }
              | {
                  type: 'JSON';
                }
              | {
                  type: 'JSONL';
                }
              | {
                  type: 'EXCEL';
                }
              | {
                  type: 'PDF';
                  layout?: 'portrait' | 'landscape';
                  scaleFactor?: number;
                }
              | {
                  type: 'PNG';
                  pixelWidth?: number | null;
                  pixelHeight?: number | null;
                }
              | {
                  type: 'NONE';
                };
            chartId?: string;
            workbookExportSource?:
              | {
                  type: 'element';
                  elementId: string;
                }
              | {
                  type: 'page';
                  pageId: string;
                }
              | {
                  type: 'element';
                  nodeIds: string[];
                }
              | {
                  type: 'page';
                  nodeIds: string[];
                }
              | {
                  type: 'all';
                };
          }[];
          includeLink?: boolean;
          runAsRecipient?: boolean;
          attachmentSettings?: {
            mergePdfAttachments?: boolean;
            zipAttachments?: boolean;
          };
          conditionOptions?:
            | {
                type: 'always';
              }
            | {
                type: 'workbook';
                conditions: (
                  | {
                      type: 'isEmpty';
                      sheetId: string;
                    }
                  | {
                      type: 'isNotEmpty';
                      sheetId: string;
                    }
                  | {
                      type: 'sheetColumn';
                      sheetId: string;
                      mode: 'any' | 'all';
                      columnId: string;
                      op:
                        | 'Equals'
                        | 'GreaterThan'
                        | 'GreaterThanEq'
                        | 'LessThan'
                        | 'LessThanEq'
                        | 'NotEquals'
                        | 'IsNotNull'
                        | 'IsNull'
                        | 'Contains'
                        | 'StartsWith'
                        | 'EndsWith';
                      value?:
                        | {
                            type: 'null';
                          }
                        | {
                            type: 'bool';
                            val: boolean;
                          }
                        | {
                            type: 'number';
                            val: number;
                          }
                        | {
                            type: 'integer';
                            val: string;
                          }
                        | {
                            type: 'string';
                            val: string;
                          }
                        | {
                            type: 'datetime';
                            val: string;
                          }
                        | {
                            type: 'error';
                            val: string;
                          }
                        | {
                            type: 'record';
                            val: Record<string, unknown>;
                          }
                        | {
                            type: 'array';
                            val:
                              | {
                                  type: 'boolArr';
                                  data: (boolean | null)[];
                                }
                              | {
                                  type: 'numberArr';
                                  data: (number | null)[];
                                }
                              | {
                                  type: 'bigintArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'stringArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'datetimeArr';
                                  data: (number | null)[];
                                }
                              | {
                                  type: 'bytesArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'variantArr';
                                  data: (string | null)[];
                                };
                          }
                        | {
                            type: 'variant';
                            val: string;
                          };
                    }
                )[];
              }
            | {
                type: 'worksheet';
                conditions: (
                  | {
                      type: 'isEmpty';
                    }
                  | {
                      type: 'isNotEmpty';
                    }
                  | {
                      type: 'queryColumn';
                      mode: 'any' | 'all';
                      columnId: string;
                      op:
                        | 'Equals'
                        | 'GreaterThan'
                        | 'GreaterThanEq'
                        | 'LessThan'
                        | 'LessThanEq'
                        | 'NotEquals'
                        | 'IsNotNull'
                        | 'IsNull'
                        | 'Contains'
                        | 'StartsWith'
                        | 'EndsWith';
                      value?:
                        | {
                            type: 'null';
                          }
                        | {
                            type: 'bool';
                            val: boolean;
                          }
                        | {
                            type: 'number';
                            val: number;
                          }
                        | {
                            type: 'integer';
                            val: string;
                          }
                        | {
                            type: 'string';
                            val: string;
                          }
                        | {
                            type: 'datetime';
                            val: string;
                          }
                        | {
                            type: 'error';
                            val: string;
                          }
                        | {
                            type: 'record';
                            val: Record<string, unknown>;
                          }
                        | {
                            type: 'array';
                            val:
                              | {
                                  type: 'boolArr';
                                  data: (boolean | null)[];
                                }
                              | {
                                  type: 'numberArr';
                                  data: (number | null)[];
                                }
                              | {
                                  type: 'bigintArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'stringArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'datetimeArr';
                                  data: (number | null)[];
                                }
                              | {
                                  type: 'bytesArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'variantArr';
                                  data: (string | null)[];
                                };
                          }
                        | {
                            type: 'variant';
                            val: string;
                          };
                    }
                )[];
              }
            | {
                type: 'dashboard';
                conditions: (
                  | {
                      type: 'isEmpty';
                      tileId: string;
                    }
                  | {
                      type: 'isNotEmpty';
                      tileId: string;
                    }
                  | {
                      type: 'chartColumn';
                      tileId: string;
                      mode: 'any' | 'all';
                      columnId: string;
                      op:
                        | 'Equals'
                        | 'GreaterThan'
                        | 'GreaterThanEq'
                        | 'LessThan'
                        | 'LessThanEq'
                        | 'NotEquals'
                        | 'IsNotNull'
                        | 'IsNull'
                        | 'Contains'
                        | 'StartsWith'
                        | 'EndsWith';
                      value?:
                        | {
                            type: 'null';
                          }
                        | {
                            type: 'bool';
                            val: boolean;
                          }
                        | {
                            type: 'number';
                            val: number;
                          }
                        | {
                            type: 'integer';
                            val: string;
                          }
                        | {
                            type: 'string';
                            val: string;
                          }
                        | {
                            type: 'datetime';
                            val: string;
                          }
                        | {
                            type: 'error';
                            val: string;
                          }
                        | {
                            type: 'record';
                            val: Record<string, unknown>;
                          }
                        | {
                            type: 'array';
                            val:
                              | {
                                  type: 'boolArr';
                                  data: (boolean | null)[];
                                }
                              | {
                                  type: 'numberArr';
                                  data: (number | null)[];
                                }
                              | {
                                  type: 'bigintArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'stringArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'datetimeArr';
                                  data: (number | null)[];
                                }
                              | {
                                  type: 'bytesArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'variantArr';
                                  data: (string | null)[];
                                };
                          }
                        | {
                            type: 'variant';
                            val: string;
                          };
                    }
                )[];
              };
          alertConfig?: {
            window: 'alltime' | 'daily' | 'weekly' | 'always';
            volume?: number | null;
          };
          notificationName?: string;
          dashboardSettings?: {
            filters?: {
              id: string;
              filterStr: string;
            }[];
            variableValues?: components['schemas']['DashVariables'];
          };
          dynamicExportSettings?: {
            variables?: Record<
              string,
              | {
                  type: 'boolean';
                }
              | {
                  type: 'number';
                }
              | {
                  type: 'text';
                }
              | {
                  type: 'date';
                }
              | {
                  type: 'number-list';
                }
              | {
                  type: 'text-list';
                }
              | {
                  type: 'date-list';
                }
              | {
                  type: 'boolean-list';
                }
              | {
                  type: 'date-range';
                }
              | {
                  type: 'number-range';
                }
              | {
                  type: 'date-null';
                }
              | {
                  type: 'number-null';
                }
              | {
                  type: 'text-null';
                }
              | {
                  type: 'boolean-null';
                }
            >;
          };
          dynamicRecipientSettings?: {
            sourceNodeId: string;
            recipientColumnId: string;
          };
          rowLimit?: number;
          workbookVariant?: {
            tagId?: string;
            exploreKey?: string;
            bookmarkId?: string;
          };
          embedOpts?: {
            embedId?: string;
            evalConnectionId?: string;
          };
          formatting?: {
            pivotHeaderStyle?: 'merged' | 'repeated' | null;
          } | null;
        };
        isSuspended: boolean;
        ownerId: string;
        lastUpdatedByUser: string;
        disabledAt: string | null;
        disabledBy: string | null;
        createdBy: string;
        updatedBy: string;
        createdAt: string;
        updatedAt: string;
      }
    | {
        scheduledNotificationId: string;
        reportId: string;
        schedule: {
          cronSpec: string;
          timezone: string;
        };
        configV2: {
          title: string;
          messageBody: string;
          notificationAttachments: {
            formatOptions:
              | {
                  type: 'PDF';
                  layout?: 'portrait' | 'landscape';
                  scaleFactor?: number;
                }
              | {
                  type: 'NONE';
                };
            workbookExportSource?: {
              type: 'report';
            };
          }[];
          includeLink?: boolean;
          runAsRecipient?: boolean;
          attachmentSettings?: {
            mergePdfAttachments?: boolean;
            zipAttachments?: boolean;
          };
          conditionOptions?:
            | {
                type: 'always';
              }
            | {
                type: 'workbook';
                conditions: (
                  | {
                      type: 'isEmpty';
                      sheetId: string;
                    }
                  | {
                      type: 'isNotEmpty';
                      sheetId: string;
                    }
                  | {
                      type: 'sheetColumn';
                      sheetId: string;
                      mode: 'any' | 'all';
                      columnId: string;
                      op:
                        | 'Equals'
                        | 'GreaterThan'
                        | 'GreaterThanEq'
                        | 'LessThan'
                        | 'LessThanEq'
                        | 'NotEquals'
                        | 'IsNotNull'
                        | 'IsNull'
                        | 'Contains'
                        | 'StartsWith'
                        | 'EndsWith';
                      value?:
                        | {
                            type: 'null';
                          }
                        | {
                            type: 'bool';
                            val: boolean;
                          }
                        | {
                            type: 'number';
                            val: number;
                          }
                        | {
                            type: 'integer';
                            val: string;
                          }
                        | {
                            type: 'string';
                            val: string;
                          }
                        | {
                            type: 'datetime';
                            val: string;
                          }
                        | {
                            type: 'error';
                            val: string;
                          }
                        | {
                            type: 'record';
                            val: Record<string, unknown>;
                          }
                        | {
                            type: 'array';
                            val:
                              | {
                                  type: 'boolArr';
                                  data: (boolean | null)[];
                                }
                              | {
                                  type: 'numberArr';
                                  data: (number | null)[];
                                }
                              | {
                                  type: 'bigintArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'stringArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'datetimeArr';
                                  data: (number | null)[];
                                }
                              | {
                                  type: 'bytesArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'variantArr';
                                  data: (string | null)[];
                                };
                          }
                        | {
                            type: 'variant';
                            val: string;
                          };
                    }
                )[];
              }
            | {
                type: 'worksheet';
                conditions: (
                  | {
                      type: 'isEmpty';
                    }
                  | {
                      type: 'isNotEmpty';
                    }
                  | {
                      type: 'queryColumn';
                      mode: 'any' | 'all';
                      columnId: string;
                      op:
                        | 'Equals'
                        | 'GreaterThan'
                        | 'GreaterThanEq'
                        | 'LessThan'
                        | 'LessThanEq'
                        | 'NotEquals'
                        | 'IsNotNull'
                        | 'IsNull'
                        | 'Contains'
                        | 'StartsWith'
                        | 'EndsWith';
                      value?:
                        | {
                            type: 'null';
                          }
                        | {
                            type: 'bool';
                            val: boolean;
                          }
                        | {
                            type: 'number';
                            val: number;
                          }
                        | {
                            type: 'integer';
                            val: string;
                          }
                        | {
                            type: 'string';
                            val: string;
                          }
                        | {
                            type: 'datetime';
                            val: string;
                          }
                        | {
                            type: 'error';
                            val: string;
                          }
                        | {
                            type: 'record';
                            val: Record<string, unknown>;
                          }
                        | {
                            type: 'array';
                            val:
                              | {
                                  type: 'boolArr';
                                  data: (boolean | null)[];
                                }
                              | {
                                  type: 'numberArr';
                                  data: (number | null)[];
                                }
                              | {
                                  type: 'bigintArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'stringArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'datetimeArr';
                                  data: (number | null)[];
                                }
                              | {
                                  type: 'bytesArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'variantArr';
                                  data: (string | null)[];
                                };
                          }
                        | {
                            type: 'variant';
                            val: string;
                          };
                    }
                )[];
              }
            | {
                type: 'dashboard';
                conditions: (
                  | {
                      type: 'isEmpty';
                      tileId: string;
                    }
                  | {
                      type: 'isNotEmpty';
                      tileId: string;
                    }
                  | {
                      type: 'chartColumn';
                      tileId: string;
                      mode: 'any' | 'all';
                      columnId: string;
                      op:
                        | 'Equals'
                        | 'GreaterThan'
                        | 'GreaterThanEq'
                        | 'LessThan'
                        | 'LessThanEq'
                        | 'NotEquals'
                        | 'IsNotNull'
                        | 'IsNull'
                        | 'Contains'
                        | 'StartsWith'
                        | 'EndsWith';
                      value?:
                        | {
                            type: 'null';
                          }
                        | {
                            type: 'bool';
                            val: boolean;
                          }
                        | {
                            type: 'number';
                            val: number;
                          }
                        | {
                            type: 'integer';
                            val: string;
                          }
                        | {
                            type: 'string';
                            val: string;
                          }
                        | {
                            type: 'datetime';
                            val: string;
                          }
                        | {
                            type: 'error';
                            val: string;
                          }
                        | {
                            type: 'record';
                            val: Record<string, unknown>;
                          }
                        | {
                            type: 'array';
                            val:
                              | {
                                  type: 'boolArr';
                                  data: (boolean | null)[];
                                }
                              | {
                                  type: 'numberArr';
                                  data: (number | null)[];
                                }
                              | {
                                  type: 'bigintArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'stringArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'datetimeArr';
                                  data: (number | null)[];
                                }
                              | {
                                  type: 'bytesArr';
                                  data: (string | null)[];
                                }
                              | {
                                  type: 'variantArr';
                                  data: (string | null)[];
                                };
                          }
                        | {
                            type: 'variant';
                            val: string;
                          };
                    }
                )[];
              };
          alertConfig?: {
            window: 'alltime' | 'daily' | 'weekly' | 'always';
            volume?: number | null;
          };
          notificationName?: string;
          reportSettings?: {
            filters?: {
              id: string;
              filterStr: string;
            }[];
            variableValues?: components['schemas']['DashVariables'];
          };
          dynamicExportSettings?: {
            variables?: Record<
              string,
              | {
                  type: 'boolean';
                }
              | {
                  type: 'number';
                }
              | {
                  type: 'text';
                }
              | {
                  type: 'date';
                }
              | {
                  type: 'number-list';
                }
              | {
                  type: 'text-list';
                }
              | {
                  type: 'date-list';
                }
              | {
                  type: 'boolean-list';
                }
              | {
                  type: 'date-range';
                }
              | {
                  type: 'number-range';
                }
              | {
                  type: 'date-null';
                }
              | {
                  type: 'number-null';
                }
              | {
                  type: 'text-null';
                }
              | {
                  type: 'boolean-null';
                }
            >;
          };
          dynamicRecipientSettings?: {
            sourceNodeId: string;
            recipientColumnId: string;
          };
          rowLimit?: number;
          reportVariant?: {
            tagId?: string;
          };
          embedOpts?: {
            embedId?: string;
            evalConnectionId?: string;
          };
        };
        isSuspended: boolean;
        ownerId: string;
        lastUpdatedByUser: string;
        disabledAt: string | null;
        disabledBy: string | null;
        createdBy: string;
        updatedBy: string;
        createdAt: string;
        updatedAt: string;
      }
  )[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link MembersResource["listTeams"] | listTeams}. */
export interface ListMemberTeamsResponse {
  /** Array of results returned by the endpoint */
  entries: {
    teamId: string;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
    name: string;
    description: string | null;
    visibility: 'public' | 'private' | null;
    isArchived?: boolean;
  }[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link MembersResource["list"] | list}. */
export interface ListMembersResponse {
  /** Array of results returned by the endpoint */
  entries: {
    organizationId: string;
    memberId: string;
    memberType: string;
    firstName: string;
    lastName: string;
    email: string;
    profileImgUrl: string | null;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
    homeFolderId: string;
    userKind: string;
    isArchived?: boolean;
    isInactive?: boolean;
  }[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

// ---------------------------------------------------------------------------
// Sub-resource accessors (hydration)
// ---------------------------------------------------------------------------

/** Sub-resource accessors available on hydrated member entries. */
export interface MemberSubResources {
  accessibleInodes: {
    /**
     * List member files
     *
     * Source docs: https://help.sigmacomputing.com/reference/listaccessibleinodes
     *
     * List all documents and folders accessible to a specific user.
     *
     *   ### Usage notes
     *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
     *   - Filter to documents with specific permissions granted on them, or to specific types of documents like workbooks, workbook templates, data models, datasets (deprecated), reports, workspaces, database tables, and others.
     *
     * @param query - Query parameters
     * @returns ListAccessibleInodesResponse
     */
    list(
      query?: ListAccessibleInodesQuery,
    ): Promise<DeepReadonly<ListAccessibleInodesResponse>>;
    /**
     * List member files (auto-paginate all pages)
     *
     * Source docs: https://help.sigmacomputing.com/reference/listaccessibleinodes
     *
     * List all documents and folders accessible to a specific user.
     *
     *   ### Usage notes
     *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
     *   - Filter to documents with specific permissions granted on them, or to specific types of documents like workbooks, workbook templates, data models, datasets (deprecated), reports, workspaces, database tables, and others.
     *
     * @param query - Query parameters
     * @yields ListAccessibleInodesResponse
     */
    listAll(
      query?: ListAccessibleInodesQuery,
    ): PaginatedAsyncGenerator<DeepReadonly<ListAccessibleInodesResponse>>;
  };
  favoriteInodes: {
    /**
     * List all favorite documents of a member
     *
     * Source docs: https://help.sigmacomputing.com/reference/listfavoriteinodes
     *
     * List the favorite documents for a specific user.
     *
     *   ### Usage notes
     *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
     *
     * @param query - Query parameters
     * @returns ListFavoriteInodesResponse
     */
    list(
      query?: ListFavoriteInodesQuery,
    ): Promise<DeepReadonly<ListFavoriteInodesResponse>>;
    /**
     * List all favorite documents of a member (auto-paginate all pages)
     *
     * Source docs: https://help.sigmacomputing.com/reference/listfavoriteinodes
     *
     * List the favorite documents for a specific user.
     *
     *   ### Usage notes
     *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
     *
     * @param query - Query parameters
     * @yields ListFavoriteInodesResponse
     */
    listAll(
      query?: ListFavoriteInodesQuery,
    ): PaginatedAsyncGenerator<DeepReadonly<ListFavoriteInodesResponse>>;
  };
  recentInodes: {
    /**
     * List recent files for a member
     *
     * Source docs: https://help.sigmacomputing.com/reference/listrecentinodes
     *
     * List all recent documents and folders accessible to a specific user. By default, ignores explorations in the returned list.
     *
     *   ### Usage notes
     *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
     *
     * @param query - Query parameters
     * @returns ListRecentInodesResponse
     */
    list(
      query?: ListRecentInodesQuery,
    ): Promise<DeepReadonly<ListRecentInodesResponse>>;
    /**
     * List recent files for a member (auto-paginate all pages)
     *
     * Source docs: https://help.sigmacomputing.com/reference/listrecentinodes
     *
     * List all recent documents and folders accessible to a specific user. By default, ignores explorations in the returned list.
     *
     *   ### Usage notes
     *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
     *
     * @param query - Query parameters
     * @yields ListRecentInodesResponse
     */
    listAll(
      query?: ListRecentInodesQuery,
    ): PaginatedAsyncGenerator<DeepReadonly<ListRecentInodesResponse>>;
  };
  schedules: {
    /**
     * List scheduled exports for a user
     *
     * Source docs: https://help.sigmacomputing.com/reference/listmemberschedules
     *
     * Retrieve all scheduled exports owned by a specific user across all workbooks and reports that they have access to.
     *
     * ### Usage notes
     * - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
     * - To perform this operation for another user, you must use API credentials owned by a user assigned the Admin account type.
     * - Non-admin users can only retrieve their own schedules.
     * - To retrieve scheduled exports for a specific workbook, call the [/v2/workbooks/{workbookId}/schedules](listworkbookschedules) endpoint.
     *
     * ### Usage scenarios
     * - **User dashboard:** Display all scheduled exports owned by a user in a centralized dashboard.
     * - **Scheduled export management:** Allow users to view and manage all their scheduled exports across different workbooks and reports.
     * - **Audit and compliance:** Review all scheduled exports created by a specific user for governance purposes.
     * - **Cross-user management:** Admins can view and manage schedules on behalf of other users.
     *
     * @param query - Query parameters
     * @returns ListMemberSchedulesResponse
     */
    list(
      query?: ListMemberSchedulesQuery,
    ): Promise<DeepReadonly<ListMemberSchedulesResponse>>;
    /**
     * List scheduled exports for a user (auto-paginate all pages)
     *
     * Source docs: https://help.sigmacomputing.com/reference/listmemberschedules
     *
     * Retrieve all scheduled exports owned by a specific user across all workbooks and reports that they have access to.
     *
     * ### Usage notes
     * - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
     * - To perform this operation for another user, you must use API credentials owned by a user assigned the Admin account type.
     * - Non-admin users can only retrieve their own schedules.
     * - To retrieve scheduled exports for a specific workbook, call the [/v2/workbooks/{workbookId}/schedules](listworkbookschedules) endpoint.
     *
     * ### Usage scenarios
     * - **User dashboard:** Display all scheduled exports owned by a user in a centralized dashboard.
     * - **Scheduled export management:** Allow users to view and manage all their scheduled exports across different workbooks and reports.
     * - **Audit and compliance:** Review all scheduled exports created by a specific user for governance purposes.
     * - **Cross-user management:** Admins can view and manage schedules on behalf of other users.
     *
     * @param query - Query parameters
     * @yields ListMemberSchedulesResponse
     */
    listAll(
      query?: ListMemberSchedulesQuery,
    ): PaginatedAsyncGenerator<DeepReadonly<ListMemberSchedulesResponse>>;
  };
  teams: {
    /**
     * List teams for a member
     *
     * Source docs: https://help.sigmacomputing.com/reference/listmemberteams
     *
     * Retrieve a list of teams for a specific user.
     *
     * ### Usage notes
     * - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
     * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
     *
     * @param query - Query parameters
     * @returns ListMemberTeamsResponse
     */
    list(
      query?: ListMemberTeamsQuery,
    ): Promise<DeepReadonly<ListMemberTeamsResponse>>;
    /**
     * List teams for a member (auto-paginate all pages)
     *
     * Source docs: https://help.sigmacomputing.com/reference/listmemberteams
     *
     * Retrieve a list of teams for a specific user.
     *
     * ### Usage notes
     * - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
     * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
     *
     * @param query - Query parameters
     * @yields ListMemberTeamsResponse
     */
    listAll(
      query?: ListMemberTeamsQuery,
    ): PaginatedAsyncGenerator<DeepReadonly<ListMemberTeamsResponse>>;
  };
}

/** A member entry with sub-resource accessor methods. Response data properties are deeply readonly. */
export type HydratedMember<T> = DeepReadonly<T> & MemberSubResources;

// ---------------------------------------------------------------------------
// MembersResource
// ---------------------------------------------------------------------------

/** @internal Attach sub-resource accessors to a member entry. */
function _hydrateMember<T extends object>(
  entry: T,
  resource: MembersResource,
): HydratedMember<T> {
  return Object.assign(entry, {
    accessibleInodes: {
      list: (query?: ListAccessibleInodesQuery) =>
        resource.listAccessibleInodes((entry as any).memberId, query),
      listAll: (query?: ListAccessibleInodesQuery) =>
        resource.listAccessibleInodesAll((entry as any).memberId, query),
    },
    favoriteInodes: {
      list: (query?: ListFavoriteInodesQuery) =>
        resource.listFavoriteInodes((entry as any).memberId, query),
      listAll: (query?: ListFavoriteInodesQuery) =>
        resource.listFavoriteInodesAll((entry as any).memberId, query),
    },
    recentInodes: {
      list: (query?: ListRecentInodesQuery) =>
        resource.listRecentInodes((entry as any).memberId, query),
      listAll: (query?: ListRecentInodesQuery) =>
        resource.listRecentInodesAll((entry as any).memberId, query),
    },
    schedules: {
      list: (query?: ListMemberSchedulesQuery) =>
        resource.listSchedules((entry as any).memberId, query),
      listAll: (query?: ListMemberSchedulesQuery) =>
        resource.listSchedulesAll((entry as any).memberId, query),
    },
    teams: {
      list: (query?: ListMemberTeamsQuery) =>
        resource.listTeams((entry as any).memberId, query),
      listAll: (query?: ListMemberTeamsQuery) =>
        resource.listTeamsAll((entry as any).memberId, query),
    },
  }) as HydratedMember<T>;
}

export class MembersResource {
  constructor(private client: Client<paths>) {}

  /**
   * List members
   *
   * Source docs: https://help.sigmacomputing.com/reference/listmembers
   *
   *
   *   **Attention**: This endpoint will return only paginated responses starting June 2, 2026. To start returning paginated responses before that date, include the query parameter `limit` in your request.
   *
   *   List all users in Sigma.
   *
   *   ### Usage notes
   *   - Filter your results using the `email` query parameter.
   *   - Using `email` and `search` together is not supported.
   *
   * @param query - Query parameters
   * @returns List_v2_MembersResponse
   */
  async list_v2(
    query?: List_v2_MembersQuery,
  ): Promise<DeepReadonly<List_v2_MembersResponse>> {
    const { data, error, response } = await this.client.GET('/v2/members', {
      params: { query },
    });
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List members (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listmembers
   *
   *
   *   **Attention**: This endpoint will return only paginated responses starting June 2, 2026. To start returning paginated responses before that date, include the query parameter `limit` in your request.
   *
   *   List all users in Sigma.
   *
   *   ### Usage notes
   *   - Filter your results using the `email` query parameter.
   *   - Using `email` and `search` together is not supported.
   *
   * @param query - Query parameters
   * @yields List_v2_MembersResponse
   */
  list_v2All(
    query?: List_v2_MembersQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<List_v2_MembersResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list_v2({
          ...query,
          page: cursor,
        } as List_v2_MembersQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create a member
   *
   * Source docs: https://help.sigmacomputing.com/reference/createmember
   *
   * Create a user.
   *
   *   ### Usage notes
   *   - Creating a user with this endpoint sends an email invitation to the user. Embed users are not sent email invitations.
   *   - Review the account types returned by the [/v2/members](listmembers) endpoint to understand the format of the **memberType** string.
   *   - Retrieve the **teamId**(s) by calling the [/v2/teams](listteams) endpoints.
   *
   * @param body - The request body.
   * @param query - Query parameters
   * @returns CreateMemberResponse
   */
  async create(
    body: CreateMemberBody,
    query?: CreateMemberQuery,
  ): Promise<HydratedMember<CreateMemberResponse>> {
    const { data, error, response } = await this.client.POST('/v2/members', {
      params: { query },
      body,
    });
    if (error) throw new SigmaApiError(error, response);
    return _hydrateMember(data! as any, this);
  }

  /**
   * Get member
   *
   * Source docs: https://help.sigmacomputing.com/reference/getmember
   *
   * Returns a specific user by member ID.
   *
   * ### Usage notes
   * - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *
   * @param memberId
   * @returns GetMemberResponse
   */
  async get(memberId: string): Promise<HydratedMember<GetMemberResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/members/{memberId}',
      { params: { path: { memberId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return _hydrateMember(data! as any, this);
  }

  /**
   * Update member
   *
   * Source docs: https://help.sigmacomputing.com/reference/updatemember
   *
   * Update a specific user by memberId.
   *
   *   ### Usage notes
   *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *   - Review the account types returned by the same endpoint to understand the format of the **memberType** string.
   *   - To deactivate a user and reassign their documents to a specific user, set  `newOwnerId`to the user ID of the desired document owner, and `isArchived` to `True`. For more details, see [Deactivate a user](doc:deactivate-users).
   *
   * @param memberId
   * @param body - The request body.
   * @returns UpdateMemberResponse
   */
  async update(
    memberId: string,
    body: UpdateMemberBody,
  ): Promise<HydratedMember<UpdateMemberResponse>> {
    const { data, error, response } = await this.client.PATCH(
      '/v2/members/{memberId}',
      { params: { path: { memberId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return _hydrateMember(data! as any, this);
  }

  /**
   * Deactivate member
   *
   * Source docs: https://help.sigmacomputing.com/reference/deletemember
   *
   * Deactivate a specific user by memberId. Users cannot be fully deleted, only deactivated. The deactivated user's documents are reassigned to the user associated with the API client credentials. For more information, see [Deactivate users](doc:deactivate-users).
   *
   * ### Usage notes
   * - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   * - The user is directly marked **archived** by this API. See [Deactivate users](doc:deactivate-users) for more details on deactivation.
   *
   * ### Usage scenarios
   * - **User offboarding**: Manage your user base by efficiently offboarding users after they leave your organization.
   *
   * ### Best practices
   * - **Confirm memberId**: Before deactivating a user, make sure the memberId is correct.
   * - Do **not** use this for members provisioned through SCIM.
   *
   * @param memberId
   * @returns DeleteMemberResponse
   */
  async delete(memberId: string): Promise<DeepReadonly<DeleteMemberResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/members/{memberId}',
      { params: { path: { memberId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List member files
   *
   * Source docs: https://help.sigmacomputing.com/reference/listaccessibleinodes
   *
   * List all documents and folders accessible to a specific user.
   *
   *   ### Usage notes
   *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *   - Filter to documents with specific permissions granted on them, or to specific types of documents like workbooks, workbook templates, data models, datasets (deprecated), reports, workspaces, database tables, and others.
   *
   * @param memberId
   * @param query - Query parameters
   * @returns ListAccessibleInodesResponse
   */
  async listAccessibleInodes(
    memberId: string,
    query?: ListAccessibleInodesQuery,
  ): Promise<DeepReadonly<ListAccessibleInodesResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/members/{memberId}/files',
      { params: { path: { memberId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List member files (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listaccessibleinodes
   *
   * List all documents and folders accessible to a specific user.
   *
   *   ### Usage notes
   *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *   - Filter to documents with specific permissions granted on them, or to specific types of documents like workbooks, workbook templates, data models, datasets (deprecated), reports, workspaces, database tables, and others.
   *
   * @param memberId
   * @param query - Query parameters
   * @yields ListAccessibleInodesResponse
   */
  listAccessibleInodesAll(
    memberId: string,
    query?: ListAccessibleInodesQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListAccessibleInodesResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listAccessibleInodes(memberId, {
          ...query,
          page: cursor,
        } as ListAccessibleInodesQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * List all favorite documents of a member
   *
   * Source docs: https://help.sigmacomputing.com/reference/listfavoriteinodes
   *
   * List the favorite documents for a specific user.
   *
   *   ### Usage notes
   *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *
   * @param memberId
   * @param query - Query parameters
   * @returns ListFavoriteInodesResponse
   */
  async listFavoriteInodes(
    memberId: string,
    query?: ListFavoriteInodesQuery,
  ): Promise<DeepReadonly<ListFavoriteInodesResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/members/{memberId}/files/favorites',
      { params: { path: { memberId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List all favorite documents of a member (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listfavoriteinodes
   *
   * List the favorite documents for a specific user.
   *
   *   ### Usage notes
   *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *
   * @param memberId
   * @param query - Query parameters
   * @yields ListFavoriteInodesResponse
   */
  listFavoriteInodesAll(
    memberId: string,
    query?: ListFavoriteInodesQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListFavoriteInodesResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listFavoriteInodes(memberId, {
          ...query,
          page: cursor,
        } as ListFavoriteInodesQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * List recent files for a member
   *
   * Source docs: https://help.sigmacomputing.com/reference/listrecentinodes
   *
   * List all recent documents and folders accessible to a specific user. By default, ignores explorations in the returned list.
   *
   *   ### Usage notes
   *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *
   * @param memberId
   * @param query - Query parameters
   * @returns ListRecentInodesResponse
   */
  async listRecentInodes(
    memberId: string,
    query?: ListRecentInodesQuery,
  ): Promise<DeepReadonly<ListRecentInodesResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/members/{memberId}/files/recents',
      { params: { path: { memberId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List recent files for a member (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listrecentinodes
   *
   * List all recent documents and folders accessible to a specific user. By default, ignores explorations in the returned list.
   *
   *   ### Usage notes
   *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *
   * @param memberId
   * @param query - Query parameters
   * @yields ListRecentInodesResponse
   */
  listRecentInodesAll(
    memberId: string,
    query?: ListRecentInodesQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListRecentInodesResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listRecentInodes(memberId, {
          ...query,
          page: cursor,
        } as ListRecentInodesQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * List scheduled exports for a user
   *
   * Source docs: https://help.sigmacomputing.com/reference/listmemberschedules
   *
   * Retrieve all scheduled exports owned by a specific user across all workbooks and reports that they have access to.
   *
   * ### Usage notes
   * - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   * - To perform this operation for another user, you must use API credentials owned by a user assigned the Admin account type.
   * - Non-admin users can only retrieve their own schedules.
   * - To retrieve scheduled exports for a specific workbook, call the [/v2/workbooks/{workbookId}/schedules](listworkbookschedules) endpoint.
   *
   * ### Usage scenarios
   * - **User dashboard:** Display all scheduled exports owned by a user in a centralized dashboard.
   * - **Scheduled export management:** Allow users to view and manage all their scheduled exports across different workbooks and reports.
   * - **Audit and compliance:** Review all scheduled exports created by a specific user for governance purposes.
   * - **Cross-user management:** Admins can view and manage schedules on behalf of other users.
   *
   * @param memberId
   * @param query - Query parameters
   * @returns ListMemberSchedulesResponse
   */
  async listSchedules(
    memberId: string,
    query?: ListMemberSchedulesQuery,
  ): Promise<DeepReadonly<ListMemberSchedulesResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/members/{memberId}/schedules',
      { params: { path: { memberId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List scheduled exports for a user (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listmemberschedules
   *
   * Retrieve all scheduled exports owned by a specific user across all workbooks and reports that they have access to.
   *
   * ### Usage notes
   * - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   * - To perform this operation for another user, you must use API credentials owned by a user assigned the Admin account type.
   * - Non-admin users can only retrieve their own schedules.
   * - To retrieve scheduled exports for a specific workbook, call the [/v2/workbooks/{workbookId}/schedules](listworkbookschedules) endpoint.
   *
   * ### Usage scenarios
   * - **User dashboard:** Display all scheduled exports owned by a user in a centralized dashboard.
   * - **Scheduled export management:** Allow users to view and manage all their scheduled exports across different workbooks and reports.
   * - **Audit and compliance:** Review all scheduled exports created by a specific user for governance purposes.
   * - **Cross-user management:** Admins can view and manage schedules on behalf of other users.
   *
   * @param memberId
   * @param query - Query parameters
   * @yields ListMemberSchedulesResponse
   */
  listSchedulesAll(
    memberId: string,
    query?: ListMemberSchedulesQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListMemberSchedulesResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listSchedules(memberId, {
          ...query,
          page: cursor,
        } as ListMemberSchedulesQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * List teams for a member
   *
   * Source docs: https://help.sigmacomputing.com/reference/listmemberteams
   *
   * Retrieve a list of teams for a specific user.
   *
   * ### Usage notes
   * - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   *
   * @param memberId
   * @param query - Query parameters
   * @returns ListMemberTeamsResponse
   */
  async listTeams(
    memberId: string,
    query?: ListMemberTeamsQuery,
  ): Promise<DeepReadonly<ListMemberTeamsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/members/{memberId}/teams',
      { params: { path: { memberId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List teams for a member (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listmemberteams
   *
   * Retrieve a list of teams for a specific user.
   *
   * ### Usage notes
   * - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   *
   * @param memberId
   * @param query - Query parameters
   * @yields ListMemberTeamsResponse
   */
  listTeamsAll(
    memberId: string,
    query?: ListMemberTeamsQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListMemberTeamsResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listTeams(memberId, {
          ...query,
          page: cursor,
        } as ListMemberTeamsQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * List members (Paginated)
   *
   * Source docs: https://help.sigmacomputing.com/reference/v2_1_listmembers
   *
   *
   * **Attention:** This API endpoint uses pagination by default.
   *
   * List all users in Sigma.
   *
   * ### Usage notes
   * - Filter your results using the `email` query parameter.
   * - Using `email` and `search` together is not supported.
   *
   * @param query - Query parameters
   * @returns ListMembersResponse
   */
  async list(
    query?: ListMembersQuery,
  ): Promise<HydratePage<ListMembersResponse, MemberSubResources>> {
    const { data, error, response } = await this.client.GET('/v2.1/members', {
      params: { query },
    });
    if (error) throw new SigmaApiError(error, response);
    const result = data! as any;
    if (Array.isArray(result)) {
      return result.map((e: any) => _hydrateMember(e, this)) as any;
    }
    if (result.entries && Array.isArray(result.entries)) {
      result.entries = result.entries.map((e: any) => _hydrateMember(e, this));
    }
    return result;
  }

  /**
   * List members (Paginated) (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/v2_1_listmembers
   *
   *
   * **Attention:** This API endpoint uses pagination by default.
   *
   * List all users in Sigma.
   *
   * ### Usage notes
   * - Filter your results using the `email` query parameter.
   * - Using `email` and `search` together is not supported.
   *
   * @param query - Query parameters
   * @yields ListMembersResponse
   */
  listAll(
    query?: ListMembersQuery,
  ): PaginatedAsyncGenerator<
    HydratePage<ListMembersResponse, MemberSubResources>
  > {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list({
          ...query,
          page: cursor,
        } as ListMembersQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }
}
