// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link OrganizationsResource["updateSettings"] | updateSettings}. */
export interface UpdateOrganizationSettingsBody {
  /** IANA timezone identifier for the organization (e.g. "America/New_York"). */
  timezone?: string;
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link OrganizationsResource["updateSettings"] | updateSettings}. */
export interface UpdateOrganizationSettingsResponse {
  /** Unique identifier of the organization */
  organizationId: string;
  /** Current IANA timezone for the organization */
  timezone?: string;
}

// ---------------------------------------------------------------------------
// OrganizationsResource
// ---------------------------------------------------------------------------

export class OrganizationsResource {
  constructor(private client: Client<paths>) {}

  /**
   * Update organization settings
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateorganizationsettings
   *
   * Update settings for the organization associated with the API credentials.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   * - To update settings for a tenant organization, use [impersonation](doc:impersonate-users) to obtain a token for that tenant, then call this endpoint with that token.
   *
   * @param body - The request body.
   * @returns UpdateOrganizationSettingsResponse
   */
  async updateSettings(
    body: UpdateOrganizationSettingsBody,
  ): Promise<DeepReadonly<UpdateOrganizationSettingsResponse>> {
    const { data, error, response } = await this.client.PATCH(
      '/v2/organizations/settings',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
