// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

export interface DownloadQueryResponse_Variant1 {
  /** Success */
  status: 200;
  /** Download results */
  download: {
    stream: unknown;
    contentType: string;
    filename: string;
  };
}

export interface DownloadQueryResponse_Variant2 {
  /** Queued or running */
  status: 204;
}

export interface DownloadQueryResponse_Variant3 {
  /** Internal server error */
  status: 500;
  /** Error message */
  message: string;
}

/** Response from {@link QueryResource["download"] | download}. */
export type DownloadQueryResponse =
  | DownloadQueryResponse_Variant1
  | DownloadQueryResponse_Variant2
  | DownloadQueryResponse_Variant3;

// ---------------------------------------------------------------------------
// QueryResource
// ---------------------------------------------------------------------------

export class QueryResource {
  constructor(private client: Client<paths>) {}

  /**
   * Download an exported file
   *
   * Source docs: https://help.sigmacomputing.com/reference/downloadquery
   *
   * After making a request to the [/v2/workbooks/{workbookId}/export](exportworkbook) or [/v2/reports/{reportId}/export](exportreport) endpoint, you can use this endpoint to download the exported file using the queryId returned in the response.
   *
   * ### Usage notes
   *
   * - This endpoint is rate limited to 400 requests per minute.
   * - The export must be ready to download before you can download the results. The endpoint returns an error if the query is still processing or if the `queryId` is invalid or expired. Query results are typically available for a limited time, so make sure to download query results while they are available.
   * - Retrieve the **queryId** by making a request to the [/v2/workbooks/{workbookId}/export](exportworkbook) or [/v2/reports/{reportId}/export](exportreport) endpoint.
   * - Specify the file format when you make the export request. You cannot specify the file format when you download the file.
   *
   * ### Usage scenarios
   * - **Scheduled reporting**: Automate the downloading of reports generated on a scheduled basis.
   * - **Data analysis**: Retrieve large sets of data for local analysis in external tools not integrated directly with Sigma.
   *
   * ### Best practices
   * - Monitor the status of the export query before attempting a download to make sure it is ready. For a code example, see [Export to CSV with Date Range Parameters](https://help.sigmacomputing.com/recipes/workbook-export-to-csv-with-date-range-parameters).
   * - Handle errors gracefully in your application, providing users with clear messages regarding the status of their requested downloads.
   *
   * @param queryId
   * @returns DownloadQueryResponse
   */
  async download(
    queryId: string,
  ): Promise<DeepReadonly<DownloadQueryResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/query/{queryId}/download',
      { params: { path: { queryId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
