// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { PaginatedAsyncGenerator, DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link SharedTemplatesResource["listSharedWithYou"] | listSharedWithYou}. */
export interface ListTemplatesSharedWithYouQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
  pending?: boolean;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link SharedTemplatesResource["acceptShare"] | acceptShare}. */
export interface AcceptTemplateShareBody {
  shareId: string;
  sourceSwaps?: Record<
    string,
    | {
        type: 'table';
        newInodeId: string;
        columns: Record<string, string>;
        metrics: Record<string, string>;
      }
    | ({
        type: 'connection';
      } & (
        | {
            newConnectionId: string;
          }
        | {
            newConnectionName: string;
          }
      ))
  >;
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link SharedTemplatesResource["deleteShare"] | deleteShare}. */
export type DeleteExternalShareResponse = Record<string, never>;

/** Response from {@link SharedTemplatesResource["acceptShare"] | acceptShare}. */
export type AcceptTemplateShareResponse = Record<string, never>;

/** Response from {@link SharedTemplatesResource["listSharedWithYou"] | listSharedWithYou}. */
export interface ListTemplatesSharedWithYouResponse {
  entries: {
    providerOrganizationId: string;
    name: string;
    shareId: string;
    createdAt: string;
    description?: string;
    pending?: boolean;
  }[];
  nextPage: string | null;
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

// ---------------------------------------------------------------------------
// SharedTemplatesResource
// ---------------------------------------------------------------------------

export class SharedTemplatesResource {
  constructor(private client: Client<paths>) {}

  /**
   * Delete a template share
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteexternalshare
   *
   * Remove a template shared with your organization.
   *
   *   **Usage notes**
   *   - Retrieve the **shareId** by calling the [/v2/shared_templates/shared_with_you](listtemplatessharedwithyou) endpoint and using the `shareId` included in the response.
   *
   * @param shareId
   * @returns DeleteExternalShareResponse
   */
  async deleteShare(
    shareId: string,
  ): Promise<DeepReadonly<DeleteExternalShareResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/shared_templates/{shareId}',
      { params: { path: { shareId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Accept a pending template share
   *
   * Source docs: https://help.sigmacomputing.com/reference/accepttemplateshare
   *
   * If a workbook template has been shared with your organization but not yet accepted, accept the template share.
   *
   *   ### Usage notes
   *   - Retrieve pending template shares by calling the [/v2/shared_templates/shared_with_you](listtemplatessharedwithyou) endpoint and specifying `pending` as `true`.
   *   - Retrieve the **shareId** by calling the [/v2/shared_templates/shared_with_you](listtemplatessharedwithyou) endpoint and using the `shareId` included in the response.
   *   - Retrieve the **connectionId** by calling the [/v2/connections](listconnections) endpoint.
   *   - Retrieve the **inodeId** for a table by calling the [/v2/connections/{connectionId}/lookup](lookupconnection) endpoint.
   *
   *   - The key of the **sourceSwaps** object is the original id of the table, dataset, or connection in the organization that shared the template
   *
   * @param body - The request body.
   * @returns AcceptTemplateShareResponse
   */
  async acceptShare(
    body: AcceptTemplateShareBody,
  ): Promise<DeepReadonly<AcceptTemplateShareResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/shared_templates/accept',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List templates shared with your organization
   *
   * Source docs: https://help.sigmacomputing.com/reference/listtemplatessharedwithyou
   *
   * Lists all workbook templates shared with your organization.
   *
   *   ### Usage notes
   *   - Use the `pending` parameter to identify templates that have been shared but not yet accepted.
   *
   * @param query - Query parameters
   * @returns ListTemplatesSharedWithYouResponse
   */
  async listSharedWithYou(
    query?: ListTemplatesSharedWithYouQuery,
  ): Promise<DeepReadonly<ListTemplatesSharedWithYouResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/shared_templates/shared_with_you',
      { params: { query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List templates shared with your organization (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listtemplatessharedwithyou
   *
   * Lists all workbook templates shared with your organization.
   *
   *   ### Usage notes
   *   - Use the `pending` parameter to identify templates that have been shared but not yet accepted.
   *
   * @param query - Query parameters
   * @yields ListTemplatesSharedWithYouResponse
   */
  listSharedWithYouAll(
    query?: ListTemplatesSharedWithYouQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListTemplatesSharedWithYouResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listSharedWithYou({
          ...query,
          page: cursor,
        } as ListTemplatesSharedWithYouQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }
}
