// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { PaginatedAsyncGenerator, DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link SourceSwapPoliciesResource["list"] | list}. */
export interface ListSourceSwapPoliciesQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

export interface CreateSourceSwapPolicyBody_ConnectionSwap {
  type: 'connection';
  /** Name of the source swap policy. */
  name: string;
  /** ID of the connection to swap. */
  fromConnectionId: string;
  swaps: {
    connectionSwaps: {
      to: {
        path0:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
        path1:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
        path2?:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
      };
    }[];
  };
}

export interface CreateSourceSwapPolicyBody_DeploymentSwap {
  type: 'deployment';
  /** Name of the source swap policy. */
  name: string;
  /** ID of the connection to swap. */
  fromConnectionId: string;
  swaps: {
    toConnection: {
      swapType: 'attribute';
      userAttributeId: string;
    };
    deploymentSwaps: {
      from: {
        path0:
          | {
              swapType: 'all';
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            };
        path1:
          | {
              swapType: 'all';
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            };
        path2?:
          | {
              swapType: 'all';
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            };
      };
      to: {
        path0:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
        path1:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
        path2?:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
      };
    }[];
  };
}

/** Request body for {@link SourceSwapPoliciesResource["create"] | create}. */
export type CreateSourceSwapPolicyBody =
  | CreateSourceSwapPolicyBody_ConnectionSwap
  | CreateSourceSwapPolicyBody_DeploymentSwap;

/** Connection swap policy */
export interface UpdateSourceSwapPolicyBody_Variant1 {
  type?: 'connection';
  /** Name of the source swap policy. */
  name?: string;
  /** ID of the connection to swap. */
  fromConnectionId?: string;
  swaps?: {
    connectionSwaps: {
      to: {
        path0:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
        path1:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
        path2?:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
      };
    }[];
  };
}

/** Deployment swap policy */
export interface UpdateSourceSwapPolicyBody_Variant2 {
  type?: 'deployment';
  /** Name of the source swap policy. */
  name?: string;
  /** ID of the connection to swap. */
  fromConnectionId?: string;
  swaps?: {
    toConnection: {
      swapType: 'attribute';
      userAttributeId: string;
    };
    deploymentSwaps: {
      from: {
        path0:
          | {
              swapType: 'all';
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            };
        path1:
          | {
              swapType: 'all';
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            };
        path2?:
          | {
              swapType: 'all';
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            };
      };
      to: {
        path0:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
        path1:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
        path2?:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
      };
    }[];
  };
}

/** Request body for {@link SourceSwapPoliciesResource["update"] | update}. */
export type UpdateSourceSwapPolicyBody =
  UpdateSourceSwapPolicyBody_Variant1 | UpdateSourceSwapPolicyBody_Variant2;

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link SourceSwapPoliciesResource["list"] | list}. */
export interface ListSourceSwapPoliciesResponse {
  entries: ((
    | {
        type: 'connection';
        name: string;
        fromConnectionId: string;
        swaps: {
          connectionSwaps: {
            to: {
              path0:
                | {
                    swapType: 'attribute';
                    userAttributeId: string;
                  }
                | {
                    swapType: 'exact';
                    catalogObject: string;
                  }
                | {
                    swapType: 'all';
                  };
              path1:
                | {
                    swapType: 'attribute';
                    userAttributeId: string;
                  }
                | {
                    swapType: 'exact';
                    catalogObject: string;
                  }
                | {
                    swapType: 'all';
                  };
              path2?:
                | {
                    swapType: 'attribute';
                    userAttributeId: string;
                  }
                | {
                    swapType: 'exact';
                    catalogObject: string;
                  }
                | {
                    swapType: 'all';
                  };
            };
          }[];
        };
      }
    | {
        type: 'deployment';
        name: string;
        fromConnectionId: string;
        swaps: {
          toConnection: {
            swapType: 'attribute';
            userAttributeId: string;
          };
          deploymentSwaps: {
            from: {
              path0:
                | {
                    swapType: 'all';
                  }
                | {
                    swapType: 'exact';
                    catalogObject: string;
                  };
              path1:
                | {
                    swapType: 'all';
                  }
                | {
                    swapType: 'exact';
                    catalogObject: string;
                  };
              path2?:
                | {
                    swapType: 'all';
                  }
                | {
                    swapType: 'exact';
                    catalogObject: string;
                  };
            };
            to: {
              path0:
                | {
                    swapType: 'attribute';
                    userAttributeId: string;
                  }
                | {
                    swapType: 'exact';
                    catalogObject: string;
                  }
                | {
                    swapType: 'all';
                  };
              path1:
                | {
                    swapType: 'attribute';
                    userAttributeId: string;
                  }
                | {
                    swapType: 'exact';
                    catalogObject: string;
                  }
                | {
                    swapType: 'all';
                  };
              path2?:
                | {
                    swapType: 'attribute';
                    userAttributeId: string;
                  }
                | {
                    swapType: 'exact';
                    catalogObject: string;
                  }
                | {
                    swapType: 'all';
                  };
            };
          }[];
        };
      }
  ) & {
    policyId: string;
  })[];
  nextPage: string | null;
  total?: number;
}

/** Response from {@link SourceSwapPoliciesResource["create"] | create}. */
export interface CreateSourceSwapPolicyResponse {
  /** Unique identifier of the source swap policy. */
  policyId: string;
}

export interface GetSourceSwapPolicyResponse_ConnectionSwap {
  type: 'connection';
  /** Name of the source swap policy. */
  name: string;
  /** ID of the connection to swap. */
  fromConnectionId: string;
  swaps: {
    connectionSwaps: {
      to: {
        path0:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
        path1:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
        path2?:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
      };
    }[];
  };
  policyId: string;
}

export interface GetSourceSwapPolicyResponse_DeploymentSwap {
  type: 'deployment';
  /** Name of the source swap policy. */
  name: string;
  /** ID of the connection to swap. */
  fromConnectionId: string;
  swaps: {
    toConnection: {
      swapType: 'attribute';
      userAttributeId: string;
    };
    deploymentSwaps: {
      from: {
        path0:
          | {
              swapType: 'all';
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            };
        path1:
          | {
              swapType: 'all';
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            };
        path2?:
          | {
              swapType: 'all';
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            };
      };
      to: {
        path0:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
        path1:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
        path2?:
          | {
              swapType: 'attribute';
              userAttributeId: string;
            }
          | {
              swapType: 'exact';
              catalogObject: string;
            }
          | {
              swapType: 'all';
            };
      };
    }[];
  };
  policyId: string;
}

/** Response from {@link SourceSwapPoliciesResource["get"] | get}. */
export type GetSourceSwapPolicyResponse =
  | GetSourceSwapPolicyResponse_ConnectionSwap
  | GetSourceSwapPolicyResponse_DeploymentSwap;

/** Response from {@link SourceSwapPoliciesResource["update"] | update}. */
export interface UpdateSourceSwapPolicyResponse {
  /** Unique identifier of the source swap policy. */
  policyId: string;
}

/** Response from {@link SourceSwapPoliciesResource["delete"] | delete}. */
export type DeleteSourceSwapPolicyResponse = Record<string, never>;

// ---------------------------------------------------------------------------
// SourceSwapPoliciesResource
// ---------------------------------------------------------------------------

export class SourceSwapPoliciesResource {
  constructor(private client: Client<paths>) {}

  /**
   * List source swap policies (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listsourceswappolicies
   *
   * Get a list of source swap policies.
   *
   *   **Beta**: Getting a list of **Connection** source swap policies is in private beta and must be enabled for your organization. Getting a list of **Deployment** source swap policies is in public beta. This documentation is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * @param query - Query parameters
   * @returns ListSourceSwapPoliciesResponse
   */
  async list(
    query?: ListSourceSwapPoliciesQuery,
  ): Promise<DeepReadonly<ListSourceSwapPoliciesResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/sourceSwapPolicies',
      { params: { query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List source swap policies (Beta) (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listsourceswappolicies
   *
   * Get a list of source swap policies.
   *
   *   **Beta**: Getting a list of **Connection** source swap policies is in private beta and must be enabled for your organization. Getting a list of **Deployment** source swap policies is in public beta. This documentation is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * @param query - Query parameters
   * @yields ListSourceSwapPoliciesResponse
   */
  listAll(
    query?: ListSourceSwapPoliciesQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListSourceSwapPoliciesResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list({
          ...query,
          page: cursor,
        } as ListSourceSwapPoliciesQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create a source swap policy (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/createsourceswappolicy
   *
   * Create a source swap policy.
   *
   *   **Beta**: Creating a **Connection** source swap policy is in private beta and must be enabled for your organization. Creating a **Deployment** source swap policy is in public beta. This documentation is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Retrieve the **connectionId** to use as the **fromConnectionId** by calling the [/v2/connections](listconnections) endpoint.
   *   - Retrieve the **userAttributeId** to use in the **swaps** object by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *
   * @param body - The request body.
   * @returns CreateSourceSwapPolicyResponse
   */
  async create(
    body: CreateSourceSwapPolicyBody,
  ): Promise<DeepReadonly<CreateSourceSwapPolicyResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/sourceSwapPolicies',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get a source swap policy (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/getsourceswappolicy
   *
   * Get a source swap policy by policy ID.
   *
   *   **Beta**: Getting details for a **Connection** source swap policy is in private beta and must be enabled for your organization. Getting details for a **Deployment** source swap policy is in public beta. This documentation is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Retrieve the **policyId** by calling the [/v2/sourceSwapPolicies](listsourceswappolicies) endpoint.
   *
   * @param policyId - Id of the source swap policy.
   * @returns GetSourceSwapPolicyResponse
   */
  async get(
    policyId: string,
  ): Promise<DeepReadonly<GetSourceSwapPolicyResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/sourceSwapPolicies/{policyId}',
      { params: { path: { policyId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Update a source swap policy (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/updatesourceswappolicy
   *
   * Update a source swap policy.
   *
   *   **Beta**: Updating a **Connection** source swap policy is in private beta and must be enabled for your organization. Updating a **Deployment** source swap policy is in public beta. This documentation is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Retrieve the **policyId** by calling the [/v2/sourceSwapPolicies](listsourceswappolicies) endpoint.
   *   - Retrieve the **connectionId** to use as the **fromConnectionId** by calling the [/v2/connections](listconnections) endpoint.
   *   - Retrieve the **userAttributeId** to use in the **swaps** object by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *
   * @param policyId - Id of the source swap policy.
   * @param body - The request body.
   * @returns UpdateSourceSwapPolicyResponse
   */
  async update(
    policyId: string,
    body: UpdateSourceSwapPolicyBody,
  ): Promise<DeepReadonly<UpdateSourceSwapPolicyResponse>> {
    const { data, error, response } = await this.client.PATCH(
      '/v2/sourceSwapPolicies/{policyId}',
      { params: { path: { policyId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete a source swap policy (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/deletesourceswappolicy
   *
   * Delete a source swap policy by policy ID.
   *
   *   **Beta**: Deleting a **Connection** source swap policy is in private beta and must be enabled for your organization. Deleting a **Deployment** source swap policy is in public beta. This documentation is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Retrieve the **policyId** by calling the [/v2/sourceSwapPolicies](listsourceswappolicies) endpoint.
   *
   * @param policyId - Id of the source swap policy.
   * @returns DeleteSourceSwapPolicyResponse
   */
  async delete(
    policyId: string,
  ): Promise<DeepReadonly<DeleteSourceSwapPolicyResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/sourceSwapPolicies/{policyId}',
      { params: { path: { policyId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
