// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import {
  PaginatedAsyncGenerator,
  DeepReadonly,
  HydratePage,
} from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link TeamsResource["list_v2"] | list_v2}. */
export interface List_v2_TeamsQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
  name?: string;
  description?: string;
  visibility?: 'public' | 'private';
}

/** Query parameters for {@link TeamsResource["listMembers"] | listMembers}. */
export interface ListTeamMembersQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

/** Query parameters for {@link TeamsResource["listUserAttributeAssignments"] | listUserAttributeAssignments}. */
export interface ListTeamUserAttributeAssignmentsQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

/** Query parameters for {@link TeamsResource["list"] | list}. */
export interface ListTeamsQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
  name?: string;
  description?: string;
  visibility?: 'public' | 'private';
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link TeamsResource["create"] | create}. */
export interface CreateTeamBody {
  name: string;
  description?: string;
  /** Specify memberIds */
  members?: string[];
  createTeamFolder?: boolean;
  /** Whether to make a public or private team. Defaults to private. */
  visibility?: 'public' | 'private';
}

/** Request body for {@link TeamsResource["update"] | update}. */
export interface UpdateTeamBody {
  name?: string;
  description?: string;
  visibility?: 'public' | 'private';
}

/** Request body for {@link TeamsResource["assignUserAttributesTo"] | assignUserAttributesTo}. */
export interface AssignUserAttributesToTeamBody {
  assignments: {
    userAttributeId: string;
    value: {
      val: string;
      type: 'string';
    };
  }[];
}

/** Request body for {@link TeamsResource["updateMembers"] | updateMembers}. */
export interface UpdateTeamMembersBody {
  /** Members to add by memberId */
  add?: string[];
  /** Members to remove by memberId */
  remove?: string[];
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** One page of results */
export type List_v2_TeamsResponse_SinglePage = {
  teamId: string;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  description: string | null;
  visibility: 'public' | 'private' | null;
  isArchived?: boolean;
}[];

/** Multiple pages of results */
export interface List_v2_TeamsResponse_PaginatedResults {
  entries: {
    teamId: string;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
    name: string;
    description: string | null;
    visibility: 'public' | 'private' | null;
    isArchived?: boolean;
  }[];
  nextPage: string | null;
}

/** Response from {@link TeamsResource["list_v2"] | list_v2}. */
export type List_v2_TeamsResponse =
  List_v2_TeamsResponse_SinglePage | List_v2_TeamsResponse_PaginatedResults;

/** Response from {@link TeamsResource["create"] | create}. */
export interface CreateTeamResponse {
  teamId: string;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  description: string | null;
  visibility: 'public' | 'private' | null;
  isArchived?: boolean;
  members: string[];
  workspaceId: string | null;
}

/** Response from {@link TeamsResource["get"] | get}. */
export interface GetTeamResponse {
  teamId: string;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  description: string | null;
  visibility: 'public' | 'private' | null;
  isArchived?: boolean;
  members: string[];
}

/** Response from {@link TeamsResource["update"] | update}. */
export interface UpdateTeamResponse {
  teamId: string;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  description: string | null;
  visibility: 'public' | 'private' | null;
  isArchived?: boolean;
}

/** Response from {@link TeamsResource["delete"] | delete}. */
export type DeleteTeamResponse = Record<string, never>;

/** Response from {@link TeamsResource["assignUserAttributesTo"] | assignUserAttributesTo}. */
export type AssignUserAttributesToTeamResponse = Record<string, never>;

/** Response from {@link TeamsResource["listMembers"] | listMembers}. */
export interface ListTeamMembersResponse {
  /** Array of results returned by the endpoint */
  entries: {
    userId: string;
    isTeamAdmin: boolean;
    addedBy: string;
  }[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link TeamsResource["updateMembers"] | updateMembers}. */
export type UpdateTeamMembersResponse = Record<string, never>;

/** Response from {@link TeamsResource["listUserAttributeAssignments"] | listUserAttributeAssignments}. */
export interface ListTeamUserAttributeAssignmentsResponse {
  entries: {
    userAttributeId: string;
    userAttributeName: string;
    value: {
      val: string;
      type: 'string';
    };
  }[];
  nextPage: string | null;
  total?: number;
}

/** Response from {@link TeamsResource["list"] | list}. */
export interface ListTeamsResponse {
  /** Array of results returned by the endpoint */
  entries: {
    teamId: string;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
    name: string;
    description: string | null;
    visibility: 'public' | 'private' | null;
    isArchived?: boolean;
  }[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

// ---------------------------------------------------------------------------
// Sub-resource accessors (hydration)
// ---------------------------------------------------------------------------

/** Sub-resource accessors available on hydrated team entries. */
export interface TeamSubResources {
  membersResource: {
    /**
     * List team members
     *
     * Source docs: https://help.sigmacomputing.com/reference/getteammembers
     *
     * Get a paginated list of team members in a specific team.
     *
     *   ### Usage notes
     *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
     *   - Returns the members of the team by `userId`.
     *
     *   ### Usage scenarios
     *   - Identify the admin of a team.
     *
     * @param query - Query parameters
     * @returns ListTeamMembersResponse
     */
    list(
      query?: ListTeamMembersQuery,
    ): Promise<DeepReadonly<ListTeamMembersResponse>>;
    /**
     * List team members (auto-paginate all pages)
     *
     * Source docs: https://help.sigmacomputing.com/reference/getteammembers
     *
     * Get a paginated list of team members in a specific team.
     *
     *   ### Usage notes
     *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
     *   - Returns the members of the team by `userId`.
     *
     *   ### Usage scenarios
     *   - Identify the admin of a team.
     *
     * @param query - Query parameters
     * @yields ListTeamMembersResponse
     */
    listAll(
      query?: ListTeamMembersQuery,
    ): PaginatedAsyncGenerator<DeepReadonly<ListTeamMembersResponse>>;
    /**
     * Update team members
     *
     * Source docs: https://help.sigmacomputing.com/reference/updateteammembers
     *
     * Update the members of a specific team.
     *
     *   ### Usage notes
     *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
     *   - Inactive members cannot be added or removed from a team.
     *
     * @param body - The request body.
     * @returns UpdateTeamMembersResponse
     */
    update(
      body: UpdateTeamMembersBody,
    ): Promise<DeepReadonly<UpdateTeamMembersResponse>>;
  };
  userAttributeAssignments: {
    /**
     * Get team user attributes
     *
     * Source docs: https://help.sigmacomputing.com/reference/getteamuserattributeassignments
     *
     * Get a list of user attributes assigned to a team.
     *
     *   ### Usage notes
     *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
     *
     * @param query - Query parameters
     * @returns ListTeamUserAttributeAssignmentsResponse
     */
    list(
      query?: ListTeamUserAttributeAssignmentsQuery,
    ): Promise<DeepReadonly<ListTeamUserAttributeAssignmentsResponse>>;
    /**
     * Get team user attributes (auto-paginate all pages)
     *
     * Source docs: https://help.sigmacomputing.com/reference/getteamuserattributeassignments
     *
     * Get a list of user attributes assigned to a team.
     *
     *   ### Usage notes
     *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
     *
     * @param query - Query parameters
     * @yields ListTeamUserAttributeAssignmentsResponse
     */
    listAll(
      query?: ListTeamUserAttributeAssignmentsQuery,
    ): PaginatedAsyncGenerator<
      DeepReadonly<ListTeamUserAttributeAssignmentsResponse>
    >;
  };
  /**
   * Assign user attributes to a team
   *
   * Source docs: https://help.sigmacomputing.com/reference/assignuserattributestoteam
   *
   * Assign one or more user attributes to a specific team.
   *
   *   ### Usage notes
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *   - Retrieve a list of available user attributes by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Maximum 100 assignments per request.
   *
   * @param body - The request body.
   * @returns AssignUserAttributesToTeamResponse
   */
  assignUserAttributesTo(
    body: AssignUserAttributesToTeamBody,
  ): Promise<DeepReadonly<AssignUserAttributesToTeamResponse>>;
}

/** A team entry with sub-resource accessor methods. Response data properties are deeply readonly. */
export type HydratedTeam<T> = DeepReadonly<T> & TeamSubResources;

// ---------------------------------------------------------------------------
// TeamsResource
// ---------------------------------------------------------------------------

/** @internal Attach sub-resource accessors to a team entry. */
function _hydrateTeam<T extends object>(
  entry: T,
  resource: TeamsResource,
): HydratedTeam<T> {
  return Object.assign(entry, {
    membersResource: {
      list: (query?: ListTeamMembersQuery) =>
        resource.listMembers((entry as any).teamId, query),
      listAll: (query?: ListTeamMembersQuery) =>
        resource.listMembersAll((entry as any).teamId, query),
      update: (body: UpdateTeamMembersBody) =>
        resource.updateMembers((entry as any).teamId, body),
    },
    userAttributeAssignments: {
      list: (query?: ListTeamUserAttributeAssignmentsQuery) =>
        resource.listUserAttributeAssignments((entry as any).teamId, query),
      listAll: (query?: ListTeamUserAttributeAssignmentsQuery) =>
        resource.listUserAttributeAssignmentsAll((entry as any).teamId, query),
    },
    assignUserAttributesTo: (body: AssignUserAttributesToTeamBody) =>
      resource.assignUserAttributesTo((entry as any).teamId, body),
  }) as HydratedTeam<T>;
}

export class TeamsResource {
  constructor(private client: Client<paths>) {}

  /**
   * List teams
   *
   * Source docs: https://help.sigmacomputing.com/reference/listteams
   *
   *
   *   **Attention**: This endpoint will return only paginated responses starting June 2, 2026. To start returning paginated responses before that date, include the query parameter `limit` in your request.
   *
   *   List all teams in Sigma.
   *
   * @param query - Query parameters
   * @returns List_v2_TeamsResponse
   */
  async list_v2(
    query?: List_v2_TeamsQuery,
  ): Promise<DeepReadonly<List_v2_TeamsResponse>> {
    const { data, error, response } = await this.client.GET('/v2/teams', {
      params: { query },
    });
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List teams (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listteams
   *
   *
   *   **Attention**: This endpoint will return only paginated responses starting June 2, 2026. To start returning paginated responses before that date, include the query parameter `limit` in your request.
   *
   *   List all teams in Sigma.
   *
   * @param query - Query parameters
   * @yields List_v2_TeamsResponse
   */
  list_v2All(
    query?: List_v2_TeamsQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<List_v2_TeamsResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list_v2({
          ...query,
          page: cursor,
        } as List_v2_TeamsQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create a team
   *
   * Source docs: https://help.sigmacomputing.com/reference/createteam
   *
   * Create a Sigma team.
   *
   *   ### Usage notes
   *   - Specify members to add to the team by userId or memberId.
   *   - Retrieve the **memberId** by calling the [/v2/members](listmembers) endpoint.
   *
   * @param body - The request body.
   * @returns CreateTeamResponse
   */
  async create(
    body: CreateTeamBody,
  ): Promise<HydratedTeam<CreateTeamResponse>> {
    const { data, error, response } = await this.client.POST('/v2/teams', {
      body,
    });
    if (error) throw new SigmaApiError(error, response);
    return _hydrateTeam(data! as any, this);
  }

  /**
   * Get a team
   *
   * Source docs: https://help.sigmacomputing.com/reference/getteam
   *
   * Returns details about a team based on team ID. The response includes an array of member IDs that identify the users in the team.
   *
   *   ### Usage notes
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *
   * @param teamId
   * @returns GetTeamResponse
   */
  async get(teamId: string): Promise<HydratedTeam<GetTeamResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/teams/{teamId}',
      { params: { path: { teamId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return _hydrateTeam(data! as any, this);
  }

  /**
   * Update a team
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateteam
   *
   * Update the name, description, and visibility of a team.
   *
   *   ### Usage notes
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *
   * @param teamId
   * @param body - The request body.
   * @returns UpdateTeamResponse
   */
  async update(
    teamId: string,
    body: UpdateTeamBody,
  ): Promise<HydratedTeam<UpdateTeamResponse>> {
    const { data, error, response } = await this.client.PATCH(
      '/v2/teams/{teamId}',
      { params: { path: { teamId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return _hydrateTeam(data! as any, this);
  }

  /**
   * Delete a team
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteteam
   *
   * Delete a specific team.
   *
   *   ### Usage notes
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *
   * @param teamId
   * @returns DeleteTeamResponse
   */
  async delete(teamId: string): Promise<DeepReadonly<DeleteTeamResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/teams/{teamId}',
      { params: { path: { teamId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Assign user attributes to a team
   *
   * Source docs: https://help.sigmacomputing.com/reference/assignuserattributestoteam
   *
   * Assign one or more user attributes to a specific team.
   *
   *   ### Usage notes
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *   - Retrieve a list of available user attributes by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Maximum 100 assignments per request.
   *
   * @param teamId
   * @param body - The request body.
   * @returns AssignUserAttributesToTeamResponse
   */
  async assignUserAttributesTo(
    teamId: string,
    body: AssignUserAttributesToTeamBody,
  ): Promise<DeepReadonly<AssignUserAttributesToTeamResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/teams/{teamId}/assignedUserAttributes',
      { params: { path: { teamId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List team members
   *
   * Source docs: https://help.sigmacomputing.com/reference/getteammembers
   *
   * Get a paginated list of team members in a specific team.
   *
   *   ### Usage notes
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *   - Returns the members of the team by `userId`.
   *
   *   ### Usage scenarios
   *   - Identify the admin of a team.
   *
   * @param teamId
   * @param query - Query parameters
   * @returns ListTeamMembersResponse
   */
  async listMembers(
    teamId: string,
    query?: ListTeamMembersQuery,
  ): Promise<DeepReadonly<ListTeamMembersResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/teams/{teamId}/members',
      { params: { path: { teamId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List team members (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/getteammembers
   *
   * Get a paginated list of team members in a specific team.
   *
   *   ### Usage notes
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *   - Returns the members of the team by `userId`.
   *
   *   ### Usage scenarios
   *   - Identify the admin of a team.
   *
   * @param teamId
   * @param query - Query parameters
   * @yields ListTeamMembersResponse
   */
  listMembersAll(
    teamId: string,
    query?: ListTeamMembersQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListTeamMembersResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listMembers(teamId, {
          ...query,
          page: cursor,
        } as ListTeamMembersQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Update team members
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateteammembers
   *
   * Update the members of a specific team.
   *
   *   ### Usage notes
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *   - Inactive members cannot be added or removed from a team.
   *
   * @param teamId
   * @param body - The request body.
   * @returns UpdateTeamMembersResponse
   */
  async updateMembers(
    teamId: string,
    body: UpdateTeamMembersBody,
  ): Promise<DeepReadonly<UpdateTeamMembersResponse>> {
    const { data, error, response } = await this.client.PATCH(
      '/v2/teams/{teamId}/members',
      { params: { path: { teamId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get team user attributes
   *
   * Source docs: https://help.sigmacomputing.com/reference/getteamuserattributeassignments
   *
   * Get a list of user attributes assigned to a team.
   *
   *   ### Usage notes
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *
   * @param teamId
   * @param query - Query parameters
   * @returns ListTeamUserAttributeAssignmentsResponse
   */
  async listUserAttributeAssignments(
    teamId: string,
    query?: ListTeamUserAttributeAssignmentsQuery,
  ): Promise<DeepReadonly<ListTeamUserAttributeAssignmentsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/teams/{teamId}/user-attributes',
      { params: { path: { teamId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get team user attributes (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/getteamuserattributeassignments
   *
   * Get a list of user attributes assigned to a team.
   *
   *   ### Usage notes
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *
   * @param teamId
   * @param query - Query parameters
   * @yields ListTeamUserAttributeAssignmentsResponse
   */
  listUserAttributeAssignmentsAll(
    teamId: string,
    query?: ListTeamUserAttributeAssignmentsQuery,
  ): PaginatedAsyncGenerator<
    DeepReadonly<ListTeamUserAttributeAssignmentsResponse>
  > {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listUserAttributeAssignments(teamId, {
          ...query,
          page: cursor,
        } as ListTeamUserAttributeAssignmentsQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * List teams (Paginated)
   *
   * Source docs: https://help.sigmacomputing.com/reference/v2_1_listteams
   *
   *
   *   **Attention:** This API endpoint uses pagination by default.
   *
   *   List all teams in Sigma.
   *
   * @param query - Query parameters
   * @returns ListTeamsResponse
   */
  async list(
    query?: ListTeamsQuery,
  ): Promise<HydratePage<ListTeamsResponse, TeamSubResources>> {
    const { data, error, response } = await this.client.GET('/v2.1/teams', {
      params: { query },
    });
    if (error) throw new SigmaApiError(error, response);
    const result = data! as any;
    if (Array.isArray(result)) {
      return result.map((e: any) => _hydrateTeam(e, this)) as any;
    }
    if (result.entries && Array.isArray(result.entries)) {
      result.entries = result.entries.map((e: any) => _hydrateTeam(e, this));
    }
    return result;
  }

  /**
   * List teams (Paginated) (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/v2_1_listteams
   *
   *
   *   **Attention:** This API endpoint uses pagination by default.
   *
   *   List all teams in Sigma.
   *
   * @param query - Query parameters
   * @yields ListTeamsResponse
   */
  listAll(
    query?: ListTeamsQuery,
  ): PaginatedAsyncGenerator<HydratePage<ListTeamsResponse, TeamSubResources>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list({
          ...query,
          page: cursor,
        } as ListTeamsQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }
}
