// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths, operations } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import {
  PaginatedAsyncGenerator,
  DeepReadonly,
  HydratePage,
} from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link TemplatesResource["list"] | list}. */
export interface ListTemplatesQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
  /**
   * Filters results to templates based on their source. Set to internal to only retrieve templates created within your organization. Set to external to only retrieve templates shared to your organization. Do not specify a source to list all templates regardless of their source.
   */
  source?: 'internal' | 'external';
  /** Filter results based on the name of the templates. */
  search?: string;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link TemplatesResource["sourceSwap"] | sourceSwap}. */
export type SourceSwapTemplateBody = NonNullable<
  operations['sourceSwapTemplate']['requestBody']
>['content']['application/json'];

/** Request body for {@link TemplatesResource["saveWorkbookFrom"] | saveWorkbookFrom}. */
export interface SaveWorkbookFromTemplateBody {
  templateId: string;
  folderId: string;
  name?: string;
  description?: string;
  updateAutomatically?: boolean;
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link TemplatesResource["list"] | list}. */
export interface ListTemplatesResponse {
  /** Array of results returned by the endpoint */
  entries: {
    templateId: string;
    templateUrlId: string;
    name: string;
    url: string;
    path: string;
    latestVersion: number;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
    isArchived?: boolean;
    tags?: {
      versionTagId: string;
      name: string;
    }[];
  }[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link TemplatesResource["get"] | get}. */
export interface GetTemplateResponse {
  templateId: string;
  templateUrlId: string;
  name: string;
  url: string;
  path: string;
  latestVersion: number;
  /** The identifier of the user who created this object. */
  createdBy: string;
  /** The identifier of the user or process that last updated this object. */
  updatedBy: string;
  /** When the object was created. */
  createdAt: string;
  /** When the object was last updated. */
  updatedAt: string;
  isArchived?: boolean;
  tags?: {
    versionTagId: string;
    name: string;
  }[];
}

/** Response from {@link TemplatesResource["sourceSwap"] | sourceSwap}. */
export interface SourceSwapTemplateResponse {
  /** IDs of sources in the workbook that were not swapped. */
  unswappedSources: string[];
  /** IDs of custom SQL connections in the workbook that were not swapped. */
  unswappedConnections: string[];
}

/** Response from {@link TemplatesResource["saveWorkbookFrom"] | saveWorkbookFrom}. */
export interface SaveWorkbookFromTemplateResponse {
  workbookId: string;
}

// ---------------------------------------------------------------------------
// Sub-resource accessors (hydration)
// ---------------------------------------------------------------------------

/** Sub-resource accessors available on hydrated template entries. */
export interface TemplateSubResources {
  /**
   * Swap template data sources
   *
   * Source docs: https://help.sigmacomputing.com/reference/sourceswaptemplate
   *
   * Swap the data sources used by a workbook template. You can swap from one connection to another, and/or from one dataset to another.
   *
   *   ### Usage notes
   *   - Retrieve the **templateId** by calling the [/v2/templates](listtemplates) endpoint.
   *   - Retrieve the **connectionId** to use as the **toId** by calling the [/v2/connections](listconnections) endpoint.
   *   - To map the sources of a specific element, you can use the table or dataset ID:
   *
   *     - Retrieve the **fromId** for a specific data element by calling the [/v2/workbooks/{workbookId}/lineage/elements/{elementId}](listlineage) endpoint and using the `source` key from the response, which looks like `inode-2PBoXx3UabchxF1F3l07kE`. The ID is everything after `inode-`.
   *     - Retrieve table and dataset IDs by calling the [/v2/files](fileslist) endpoint. Use the `typeFilters` option to filter for table and dataset files. Use `id` field in the response as the `fromId` or `toId`, as relevant.
   *
   * @param body - The request body.
   * @returns SourceSwapTemplateResponse
   */
  sourceSwap(
    body: SourceSwapTemplateBody,
  ): Promise<DeepReadonly<SourceSwapTemplateResponse>>;
}

/** A template entry with sub-resource accessor methods. Response data properties are deeply readonly. */
export type HydratedTemplate<T> = DeepReadonly<T> & TemplateSubResources;

// ---------------------------------------------------------------------------
// TemplatesResource
// ---------------------------------------------------------------------------

/** @internal Attach sub-resource accessors to a template entry. */
function _hydrateTemplate<T extends object>(
  entry: T,
  resource: TemplatesResource,
): HydratedTemplate<T> {
  return Object.assign(entry, {
    sourceSwap: (body: SourceSwapTemplateBody) =>
      resource.sourceSwap((entry as any).templateId, body),
  }) as HydratedTemplate<T>;
}

export class TemplatesResource {
  constructor(private client: Client<paths>) {}

  /**
   * List templates
   *
   * Source docs: https://help.sigmacomputing.com/reference/listtemplates
   *
   * Returns a list of available templates.
   *
   *   ### Usage notes
   *   - Official Sigma templates are created by SigmaSchedulerRobot.
   *
   * @param query - Query parameters
   * @returns ListTemplatesResponse
   */
  async list(
    query?: ListTemplatesQuery,
  ): Promise<HydratePage<ListTemplatesResponse, TemplateSubResources>> {
    const { data, error, response } = await this.client.GET('/v2/templates', {
      params: { query },
    });
    if (error) throw new SigmaApiError(error, response);
    const result = data! as any;
    if (Array.isArray(result)) {
      return result.map((e: any) => _hydrateTemplate(e, this)) as any;
    }
    if (result.entries && Array.isArray(result.entries)) {
      result.entries = result.entries.map((e: any) =>
        _hydrateTemplate(e, this),
      );
    }
    return result;
  }

  /**
   * List templates (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listtemplates
   *
   * Returns a list of available templates.
   *
   *   ### Usage notes
   *   - Official Sigma templates are created by SigmaSchedulerRobot.
   *
   * @param query - Query parameters
   * @yields ListTemplatesResponse
   */
  listAll(
    query?: ListTemplatesQuery,
  ): PaginatedAsyncGenerator<
    HydratePage<ListTemplatesResponse, TemplateSubResources>
  > {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list({
          ...query,
          page: cursor,
        } as ListTemplatesQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Get template
   *
   * Source docs: https://help.sigmacomputing.com/reference/gettemplate
   *
   * Get a template by template ID.
   *
   *   ### Usage notes
   *   - Retrieve the **templateId** by calling the [/v2/templates](listtemplates) endpoint.
   *
   * @param templateId - Template ID
   * @returns GetTemplateResponse
   */
  async get(
    templateId: string,
  ): Promise<HydratedTemplate<GetTemplateResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/templates/{templateId}',
      { params: { path: { templateId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return _hydrateTemplate(data! as any, this);
  }

  /**
   * Swap template data sources
   *
   * Source docs: https://help.sigmacomputing.com/reference/sourceswaptemplate
   *
   * Swap the data sources used by a workbook template. You can swap from one connection to another, and/or from one dataset to another.
   *
   *   ### Usage notes
   *   - Retrieve the **templateId** by calling the [/v2/templates](listtemplates) endpoint.
   *   - Retrieve the **connectionId** to use as the **toId** by calling the [/v2/connections](listconnections) endpoint.
   *   - To map the sources of a specific element, you can use the table or dataset ID:
   *
   *     - Retrieve the **fromId** for a specific data element by calling the [/v2/workbooks/{workbookId}/lineage/elements/{elementId}](listlineage) endpoint and using the `source` key from the response, which looks like `inode-2PBoXx3UabchxF1F3l07kE`. The ID is everything after `inode-`.
   *     - Retrieve table and dataset IDs by calling the [/v2/files](fileslist) endpoint. Use the `typeFilters` option to filter for table and dataset files. Use `id` field in the response as the `fromId` or `toId`, as relevant.
   *
   * @param templateId - Template ID
   * @param body - The request body.
   * @returns SourceSwapTemplateResponse
   */
  async sourceSwap(
    templateId: string,
    body: SourceSwapTemplateBody,
  ): Promise<DeepReadonly<SourceSwapTemplateResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/templates/{templateId}/swapSources',
      { params: { path: { templateId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Create workbook from template
   *
   * Source docs: https://help.sigmacomputing.com/reference/saveworkbookfromtemplate
   *
   * Create a workbook by saving it from a template.
   *
   *   ### Usage notes
   *   - Retrieve the **templateId** by calling the [/v2/templates](listtemplates) endpoint.
   *   - Retrieve the **folderId** by calling the [/v2/files](fileslist) endpoint and reviewing the `id` field in the response for files with a `type` of `folder`. To use the "My Documents" folder as the destination folder, call the [/v2/members/{memberId}](getmember) endpoint and use the `homeFolderId` included in the response.
   *   - If you leave the name or description options blank, the workbook created inherits the values of the template.
   *
   * @param body - The request body.
   * @returns SaveWorkbookFromTemplateResponse
   */
  async saveWorkbookFrom(
    body: SaveWorkbookFromTemplateBody,
  ): Promise<DeepReadonly<SaveWorkbookFromTemplateResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/templates/save_workbook',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
