// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { PaginatedAsyncGenerator, DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link TenantsResource["list"] | list}. */
export interface ListTenantsQuery {
  /**
   * Use to specify the next set of results with the string returned in the `nextPageToken` field of the previous response.
   */
  pageToken?: string;
  /** Number of results to return per page, with a maximum of 1000. Defaults to 50. */
  pageSize?: number;
  /** Field to sort the results by */
  key?: 'createdAt' | 'createdBy' | 'name' | 'url';
  /** Sort order for the results */
  order?: 'asc' | 'desc';
  /** Search term to filter tenant organizations by slug or creator */
  search?: string;
}

/** Query parameters for {@link TenantsResource["listDeploymentCapabilities"] | listDeploymentCapabilities}. */
export interface ListTenantDeploymentCapabilitiesQuery {
  /**
   * Use to specify the next set of results with the string returned in the `nextPageToken` field of the previous response.
   */
  pageToken?: string;
  /** Number of results to return per page, with a maximum of 1000. Defaults to 50. */
  pageSize?: number;
}

/** Query parameters for {@link TenantsResource["getWorkbook"] | getWorkbook}. */
export interface GetTenantWorkbookQuery {
  /**
   * Unique identifier of the workbook in the parent organization. For version-tagged deployments, this can be either the source workbook ID or the version-tagged workbook ID.
   */
  parentWorkbookId?: string;
  /** The ID of the deployment policy that contains the workbook */
  deploymentPolicyId?: string;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link TenantsResource["create"] | create}. */
export interface CreateTenantBody {
  /** Name of the tenant organization to create */
  tenantOrganizationName: string;
  /** URL identifier for the tenant organization */
  tenantOrganizationSlug: string;
  /**
   * Cloud provider to create the tenant organization in. Defaults to the same cloud provider as the parent organization
   */
  cloudProvider?:
    | 'aws'
    | 'aws-au'
    | 'aws-ca'
    | 'aws-eu'
    | 'aws-uk'
    | 'aws-us-a'
    | 'azure-ca'
    | 'azure-eu'
    | 'azure-uk'
    | 'azure-us'
    | 'gcp'
    | 'gcp-us';
}

/** Request body for {@link TenantsResource["patch"] | patch}. */
export interface PatchTenantBody {
  /** New name for the tenant organization */
  tenantOrganizationName?: string;
  /** New URL identifier for the tenant organization */
  tenantOrganizationSlug?: string;
}

/** Request body for {@link TenantsResource["addDeploymentCapabilities"] | addDeploymentCapabilities}. */
export interface AddTenantDeploymentCapabilitiesBody {
  /** The tenant organizations that this tenant can deploy to. */
  deployToTenantOrganizationIds: string[];
}

/** Request body for {@link TenantsResource["removeDeploymentCapabilities"] | removeDeploymentCapabilities}. */
export interface RemoveTenantDeploymentCapabilitiesBody {
  /** The tenant organizations that this tenant can no longer deploy to */
  deployToTenantOrganizationIds: string[];
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link TenantsResource["list"] | list}. */
export interface ListTenantsResponse {
  /** Array of results returned by the endpoint */
  entries: ({
    tenantOrganizationId: string;
    parentOrganizationId: string;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
    tenantOrganizationName: string;
    tenantOrganizationSlug: string;
    sharedAt?: string;
    tenantCloudProvider?: string;
    tenantRegion?: string;
    tenantApiUrl?: string;
  } | null)[];
  /**
   * A string that can be passed to the `pageToken` parameter in the next request to fetch the next page of results. Not present in the last page of results.
   * **Must be treated as an opaque string.**
   */
  nextPageToken?: string;
}

/** Response from {@link TenantsResource["create"] | create}. */
export interface CreateTenantResponse {
  /** Unique identifier of the tenant organization */
  tenantOrganizationId: string;
  /** Unique identifier of the tenant's parent organization */
  parentOrganizationId: string;
  /** Unique identifier of the user who created the tenant organization */
  createdBy: string;
  /** Unique identifier of the user who last updated the tenant organization */
  updatedBy: string;
  /** Timestamp when the tenant organization was created. Format: ISO 8601 timestamp */
  createdAt: string;
  /** Timestamp when the tenant organization was last updated. Format: ISO 8601 timestamp */
  updatedAt: string;
  /** Name of the tenant organization to create */
  tenantOrganizationName: string;
  /** URL identifier for the tenant organization */
  tenantOrganizationSlug: string;
  /** Timestamp when the tenant organization was shared, if applicable. Format: ISO 8601 timestamp */
  sharedAt?: string;
  /** Cloud provider the tenant organization is hosted on */
  tenantCloudProvider?: string;
  /** Region the tenant organization is hosted in */
  tenantRegion?: string;
  /** Base URL for accessing the tenant organization API */
  tenantApiUrl?: string;
}

/** Response from {@link TenantsResource["get"] | get}. */
export interface GetTenantResponse {
  /** Unique identifier of the tenant organization */
  tenantOrganizationId: string;
  /** Unique identifier of the tenant's parent organization */
  parentOrganizationId: string;
  /** Unique identifier of the user who created the tenant organization */
  createdBy: string;
  /** Unique identifier of the user who last updated the tenant organization */
  updatedBy: string;
  /** Timestamp when the tenant organization was created. Format: ISO 8601 timestamp */
  createdAt: string;
  /** Timestamp when the tenant organization was last updated. Format: ISO 8601 timestamp */
  updatedAt: string;
  /** Name of the tenant organization to create */
  tenantOrganizationName: string;
  /** URL identifier for the tenant organization */
  tenantOrganizationSlug: string;
  /** Timestamp when the tenant organization was shared, if applicable. Format: ISO 8601 timestamp */
  sharedAt?: string;
  /** Cloud provider the tenant organization is hosted on */
  tenantCloudProvider?: string;
  /** Region the tenant organization is hosted in */
  tenantRegion?: string;
  /** Base URL for accessing the tenant organization API */
  tenantApiUrl?: string;
}

/** Response from {@link TenantsResource["patch"] | patch}. */
export interface PatchTenantResponse {
  /** Unique identifier of the tenant organization */
  tenantOrganizationId: string;
  /** Unique identifier of the tenant's parent organization */
  parentOrganizationId: string;
  /** Unique identifier of the user who created the tenant organization */
  createdBy: string;
  /** Unique identifier of the user who last updated the tenant organization */
  updatedBy: string;
  /** Timestamp when the tenant organization was created. Format: ISO 8601 timestamp */
  createdAt: string;
  /** Timestamp when the tenant organization was last updated. Format: ISO 8601 timestamp */
  updatedAt: string;
  /** Name of the tenant organization to create */
  tenantOrganizationName: string;
  /** URL identifier for the tenant organization */
  tenantOrganizationSlug: string;
  /** Timestamp when the tenant organization was shared, if applicable. Format: ISO 8601 timestamp */
  sharedAt?: string;
  /** Cloud provider the tenant organization is hosted on */
  tenantCloudProvider?: string;
  /** Region the tenant organization is hosted in */
  tenantRegion?: string;
  /** Base URL for accessing the tenant organization API */
  tenantApiUrl?: string;
}

/** Response from {@link TenantsResource["delete"] | delete}. */
export type DeleteTenantResponse = Record<string, never>;

/** Response from {@link TenantsResource["listDeploymentCapabilities"] | listDeploymentCapabilities}. */
export interface ListTenantDeploymentCapabilitiesResponse {
  /** Array of results returned by the endpoint */
  entries: {
    tenantOrganizationId: string;
  }[];
  /**
   * A string that can be passed to the `pageToken` parameter in the next request to fetch the next page of results. Not present in the last page of results.
   * **Must be treated as an opaque string.**
   */
  nextPageToken?: string;
}

/** Response from {@link TenantsResource["addDeploymentCapabilities"] | addDeploymentCapabilities}. */
export interface AddTenantDeploymentCapabilitiesResponse {
  capabilities: {
    tenantOrganizationId: string;
  }[];
}

/** Response from {@link TenantsResource["removeDeploymentCapabilities"] | removeDeploymentCapabilities}. */
export type RemoveTenantDeploymentCapabilitiesResponse = Record<string, never>;

/** Response from {@link TenantsResource["getWorkbook"] | getWorkbook}. */
export interface GetTenantWorkbookResponse {
  /** Unique identifier of the workbook deployed to the tenant organization */
  workbookId: string;
  /** URL to access the workbook in the tenant organization */
  workbookUrl: string;
}

// ---------------------------------------------------------------------------
// TenantsResource
// ---------------------------------------------------------------------------

export class TenantsResource {
  constructor(private client: Client<paths>) {}

  /**
   * List tenant organizations (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listtenants
   *
   * Retrieve a paginated list of tenant organizations with optional filtering and sorting.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   * - Use **pageToken** and **pageSize** parameters to manage paginated responses.
   * - Use **search** to filter results by organization slug or ID of the user who created the tenant.
   * - Use **key** and **order** to sort results by creation date, ID of the user who created the tenant, name, or URL.
   *
   * @param query - Query parameters
   * @returns ListTenantsResponse
   */
  async list(
    query?: ListTenantsQuery,
  ): Promise<DeepReadonly<ListTenantsResponse>> {
    const { data, error, response } = await this.client.GET('/v2/tenants', {
      params: { query },
    });
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List tenant organizations (Beta) (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listtenants
   *
   * Retrieve a paginated list of tenant organizations with optional filtering and sorting.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   * - Use **pageToken** and **pageSize** parameters to manage paginated responses.
   * - Use **search** to filter results by organization slug or ID of the user who created the tenant.
   * - Use **key** and **order** to sort results by creation date, ID of the user who created the tenant, name, or URL.
   *
   * @param query - Query parameters
   * @yields ListTenantsResponse
   */
  listAll(
    query?: ListTenantsQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListTenantsResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list({
          ...query,
          pageToken: cursor,
        } as ListTenantsQuery);
        yield page;
        cursor = (page as { nextPageToken?: string | null })[
          'nextPageToken'
        ] as string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create a tenant organization (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/createtenant
   *
   * Create a new tenant organization with the specified name and organization slug to be used in the URL.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   * - The **tenantOrganizationName** is displayed as the organization name in the Sigma interface.
   * - The **tenantOrganizationSlug** must be unique and is used in URLs to identify the tenant organization.
   *
   * @param body - The request body.
   * @returns CreateTenantResponse
   */
  async create(
    body: CreateTenantBody,
  ): Promise<DeepReadonly<CreateTenantResponse>> {
    const { data, error, response } = await this.client.POST('/v2/tenants', {
      body,
    });
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get details for a tenant organization (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/gettenant
   *
   * Retrieve details of a specific tenant organization by tenantOrganizationId.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   * - Retrieve the **tenantOrganizationId** by calling the [/v2/tenants](listtenants) endpoint.
   *
   * @param tenantOrganizationId
   * @returns GetTenantResponse
   */
  async get(
    tenantOrganizationId: string,
  ): Promise<DeepReadonly<GetTenantResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/tenants/{tenantOrganizationId}',
      { params: { path: { tenantOrganizationId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Update details of a tenant organization (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/patchtenant
   *
   * Update the details of an existing tenant organization. The organization name and slug can be updated through this endpoint.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   * - Retrieve the **tenantOrganizationId** by calling the [/v2/tenants](listtenants) endpoint.
   *
   * @param tenantOrganizationId
   * @param body - The request body.
   * @returns PatchTenantResponse
   */
  async patch(
    tenantOrganizationId: string,
    body: PatchTenantBody,
  ): Promise<DeepReadonly<PatchTenantResponse>> {
    const { data, error, response } = await this.client.PATCH(
      '/v2/tenants/{tenantOrganizationId}',
      { params: { path: { tenantOrganizationId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete a tenant organization (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/deletetenant
   *
   * Delete a tenant organization by tenantOrganizationId.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   * - Retrieve the **tenantOrganizationId** by calling the [/v2/tenants](listtenants) endpoint.
   * - This action permanently removes the tenant organization and cannot be undone.
   *
   * @param tenantOrganizationId
   * @returns DeleteTenantResponse
   */
  async delete(
    tenantOrganizationId: string,
  ): Promise<DeepReadonly<DeleteTenantResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/tenants/{tenantOrganizationId}',
      { params: { path: { tenantOrganizationId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List tenant deployment capabilities (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listtenantdeploymentcapabilities
   *
   * Retrieve a paginated list of tenant organizations that the specified tenant organization can deploy to.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   * - Retrieve the **tenantOrganizationId** by calling the [/v2/tenants](listtenants) endpoint.
   * - Use **pageToken** and **pageSize** to paginate results.
   *
   * @param tenantOrganizationId - Unique identifier of the tenant organization whose deployment capabilities are being managed.
   * @param query - Query parameters
   * @returns ListTenantDeploymentCapabilitiesResponse
   */
  async listDeploymentCapabilities(
    tenantOrganizationId: string,
    query?: ListTenantDeploymentCapabilitiesQuery,
  ): Promise<DeepReadonly<ListTenantDeploymentCapabilitiesResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/tenants/{tenantOrganizationId}/capabilities/deployments',
      { params: { path: { tenantOrganizationId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List tenant deployment capabilities (Beta) (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listtenantdeploymentcapabilities
   *
   * Retrieve a paginated list of tenant organizations that the specified tenant organization can deploy to.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   * - Retrieve the **tenantOrganizationId** by calling the [/v2/tenants](listtenants) endpoint.
   * - Use **pageToken** and **pageSize** to paginate results.
   *
   * @param tenantOrganizationId - Unique identifier of the tenant organization whose deployment capabilities are being managed.
   * @param query - Query parameters
   * @yields ListTenantDeploymentCapabilitiesResponse
   */
  listDeploymentCapabilitiesAll(
    tenantOrganizationId: string,
    query?: ListTenantDeploymentCapabilitiesQuery,
  ): PaginatedAsyncGenerator<
    DeepReadonly<ListTenantDeploymentCapabilitiesResponse>
  > {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listDeploymentCapabilities(
          tenantOrganizationId,
          {
            ...query,
            pageToken: cursor,
          } as ListTenantDeploymentCapabilitiesQuery,
        );
        yield page;
        cursor = (page as { nextPageToken?: string | null })[
          'nextPageToken'
        ] as string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Add deployment capabilities to a tenant (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/addtenantdeploymentcapabilities
   *
   * Grant a tenant organization the capability to deploy to other tenant organizations.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   * - Retrieve **tenantOrganizationId** values by calling the [/v2/tenants](listtenants) endpoint.
   *
   * @param tenantOrganizationId - Unique identifier of the tenant organization whose deployment capabilities are being managed.
   * @param body - The request body.
   * @returns AddTenantDeploymentCapabilitiesResponse
   */
  async addDeploymentCapabilities(
    tenantOrganizationId: string,
    body: AddTenantDeploymentCapabilitiesBody,
  ): Promise<DeepReadonly<AddTenantDeploymentCapabilitiesResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/tenants/{tenantOrganizationId}/capabilities/deployments:batchAdd',
      { params: { path: { tenantOrganizationId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Remove deployment capabilities from a tenant (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/removetenantdeploymentcapabilities
   *
   * Revoke a tenant organization's capability to deploy to one or more tenant organizations.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   * - Retrieve **tenantOrganizationId** values by calling the [/v2/tenants](listtenants) endpoint.
   * - Existing deployments from this tenant organization to the specified tenant organizations will be removed.
   *
   * @param tenantOrganizationId - Unique identifier of the tenant organization whose deployment capabilities are being managed.
   * @param body - The request body.
   * @returns RemoveTenantDeploymentCapabilitiesResponse
   */
  async removeDeploymentCapabilities(
    tenantOrganizationId: string,
    body: RemoveTenantDeploymentCapabilitiesBody,
  ): Promise<DeepReadonly<RemoveTenantDeploymentCapabilitiesResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/tenants/{tenantOrganizationId}/capabilities/deployments:batchRemove',
      { params: { path: { tenantOrganizationId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get deployed workbook in tenant organization (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/gettenantworkbook
   *
   * Retrieve the workbook ID for a workbook deployed to a tenant organization for a given parent workbook and deployment policy.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   * - The parent workbook must be part of the specified deployment policy.
   * - The workbook must be deployed to the specified tenant organization.
   * - Retrieve the **tenantOrganizationId** by calling the [/v2/tenants](listtenants) endpoint.
   * - Retrieve the **deploymentPolicyId** by calling the [/v2/deploymentPolicies](listdeployments) endpoint.
   * - Retrieve the **parentWorkbookId** by calling the [/v2/deploymentPolicies/{deploymentPolicyId}/files](listinodesfordeployment) endpoint and using the `workbookId` included in the response.
   * - For version-tagged deployment policies, you may pass either the source workbook ID or the version-tagged workbook ID as the **parentWorkbookId**.
   *
   * @param tenantOrganizationId
   * @param query - Query parameters
   * @returns GetTenantWorkbookResponse
   */
  async getWorkbook(
    tenantOrganizationId: string,
    query?: GetTenantWorkbookQuery,
  ): Promise<DeepReadonly<GetTenantWorkbookResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/tenants/{tenantOrganizationId}/workbooks',
      { params: { path: { tenantOrganizationId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
