// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { PaginatedAsyncGenerator, DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link TranslationsResource["listOrgLocales"] | listOrgLocales}. */
export interface ListOrgLocalesQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link TranslationsResource["createOrg"] | createOrg}. */
export interface CreateOrgTranslationBody {
  /** The locale identifier corresponding to the language of the translation. */
  lng: string;
  /** The name of the custom translation variant, if applicable */
  lng_variant?: string | null;
  /** A JSON object with phrases as keys and their translations as values */
  translations?: Record<string, string>;
}

/** Request body for {@link TranslationsResource["updateOrg"] | updateOrg}. */
export interface UpdateOrgTranslationBody {
  /** A JSON object with phrases as keys and their translations as values */
  translations: Record<string, string>;
}

/** Request body for {@link TranslationsResource["updateOrgWithVariant"] | updateOrgWithVariant}. */
export interface UpdateOrgTranslationWithVariantBody {
  /** A JSON object with phrases as keys and their translations as values */
  translations: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link TranslationsResource["listOrgLocales"] | listOrgLocales}. */
export interface ListOrgLocalesResponse {
  /** Array of results returned by the endpoint */
  entries: {
    lng: string;
    locale: string;
    lng_variant: string | null;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
  }[];
  /**
   * Returns a string that can be used as the `page` parameter in the next request to fetch the next page of results. The last page of results returns `null`.
   */
  nextPage: string | null;
  /** Total number of results. Useful to determine if there is a need to paginate. */
  total?: number;
  /** **[Deprecated]** Indicates whether more results are available. */
  hasMore?: boolean;
}

/** Response from {@link TranslationsResource["createOrg"] | createOrg}. */
export type CreateOrgTranslationResponse = Record<string, never>;

/** Response from {@link TranslationsResource["getOrg"] | getOrg}. */
export interface GetOrgTranslationsResponse {
  /** A JSON object with phrases as keys and their translations as values */
  translations: Record<string, string>;
}

/** Response from {@link TranslationsResource["updateOrg"] | updateOrg}. */
export type UpdateOrgTranslationResponse = Record<string, never>;

/** Response from {@link TranslationsResource["deleteOrg"] | deleteOrg}. */
export type DeleteOrgTranslationResponse = Record<string, never>;

/** Response from {@link TranslationsResource["getOrgWithVariant"] | getOrgWithVariant}. */
export interface GetOrgTranslationsWithVariantResponse {
  /** A JSON object with phrases as keys and their translations as values */
  translations: Record<string, string>;
}

/** Response from {@link TranslationsResource["updateOrgWithVariant"] | updateOrgWithVariant}. */
export type UpdateOrgTranslationWithVariantResponse = Record<string, never>;

/** Response from {@link TranslationsResource["deleteOrgWithVariant"] | deleteOrgWithVariant}. */
export type DeleteOrgTranslationWithVariantResponse = Record<string, never>;

// ---------------------------------------------------------------------------
// TranslationsResource
// ---------------------------------------------------------------------------

export class TranslationsResource {
  constructor(private client: Client<paths>) {}

  /**
   * List organization translation files
   *
   * Source docs: https://help.sigmacomputing.com/reference/listorglocales
   *
   * This paginated endpoint lists all the translation files that have been defined at the organization level.
   *
   * ### Usage notes
   * This endpoint requires no parameters for basic requests but supports query parameters for pagination and response limit.
   *
   * #### Pagination
   *
   * This endpoint supports pagination, which lets you retrieve large sets of data in manageable segments. The response includes pagination details as follows:
   *
   * - hasMore: A boolean value indicating whether there are more pages of data available beyond the current page.
   * - total: The total number of entries available across all pages.
   * - nextPage: An identifier or token that you can use in a subsequent request to retrieve the next page of data.
   *
   * #### Example response for pagination
   * {
   *   "hasMore": true,
   *   "total": 104,
   *   "nextPage": "50"
   * }
   *
   * To request additional pages, include the `nextPage` option in your followup request according to the endpoint's parameter requirements. This process can be repeated until `nextPage` is `null`.
   *
   * @param query - Query parameters
   * @returns ListOrgLocalesResponse
   */
  async listOrgLocales(
    query?: ListOrgLocalesQuery,
  ): Promise<DeepReadonly<ListOrgLocalesResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/translations/organization',
      { params: { query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * List organization translation files (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listorglocales
   *
   * This paginated endpoint lists all the translation files that have been defined at the organization level.
   *
   * ### Usage notes
   * This endpoint requires no parameters for basic requests but supports query parameters for pagination and response limit.
   *
   * #### Pagination
   *
   * This endpoint supports pagination, which lets you retrieve large sets of data in manageable segments. The response includes pagination details as follows:
   *
   * - hasMore: A boolean value indicating whether there are more pages of data available beyond the current page.
   * - total: The total number of entries available across all pages.
   * - nextPage: An identifier or token that you can use in a subsequent request to retrieve the next page of data.
   *
   * #### Example response for pagination
   * {
   *   "hasMore": true,
   *   "total": 104,
   *   "nextPage": "50"
   * }
   *
   * To request additional pages, include the `nextPage` option in your followup request according to the endpoint's parameter requirements. This process can be repeated until `nextPage` is `null`.
   *
   * @param query - Query parameters
   * @yields ListOrgLocalesResponse
   */
  listOrgLocalesAll(
    query?: ListOrgLocalesQuery,
  ): PaginatedAsyncGenerator<DeepReadonly<ListOrgLocalesResponse>> {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listOrgLocales({
          ...query,
          page: cursor,
        } as ListOrgLocalesQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create organization translation file
   *
   * Source docs: https://help.sigmacomputing.com/reference/createorgtranslation
   *
   * This endpoint creates a new organization translation file for the specified locale, containing the translation key-value pairs, if provided. You can also use this endpoint to create custom translations for a locale.
   * Entering common phrases and their translations used in workbooks across your organization ensures consistent translations for all users.
   *
   * ### Usage Notes
   * - Retrieve the supported locale identifiers to use for **lng** from [Supported languages and locales](doc:manage-workbook-localization#supported-languages-and-locales).
   *
   * @param body - The request body.
   * @returns CreateOrgTranslationResponse
   */
  async createOrg(
    body: CreateOrgTranslationBody,
  ): Promise<DeepReadonly<CreateOrgTranslationResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/translations/organization',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get organization translation file
   *
   * Source docs: https://help.sigmacomputing.com/reference/getorgtranslations
   *
   * This endpoint returns a JSON file containing the translations for a specified locale (**lng**) without custom translations.
   *
   * ### Usage notes
   * - Retrieve the **lng** by calling the [/v2/translations/organization](listorglocales) endpoint.
   *
   * @param lng - The locale identifier corresponding to the language of the translation.
   * @returns GetOrgTranslationsResponse
   */
  async getOrg(lng: string): Promise<DeepReadonly<GetOrgTranslationsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/translations/organization/{lng}',
      { params: { path: { lng } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Update organization translation file
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateorgtranslation
   *
   * This endpoint updates the translation file for a specified locale (**lng**) without custom translations.
   *
   * ### Usage notes
   * - Retrieve the **lng** by calling the [/v2/translations/organization](listorglocales) endpoint.
   *
   * @param lng - The locale identifier corresponding to the language of the translation.
   * @param body - The request body.
   * @returns UpdateOrgTranslationResponse
   */
  async updateOrg(
    lng: string,
    body: UpdateOrgTranslationBody,
  ): Promise<DeepReadonly<UpdateOrgTranslationResponse>> {
    const { data, error, response } = await this.client.PUT(
      '/v2/translations/organization/{lng}',
      { params: { path: { lng } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete organization translation file
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteorgtranslation
   *
   * This endpoint deletes the translation file for the specified locale (**lng**) without any custom translations.
   *
   * ### Usage notes
   * - Retrieve the **lng** by calling the [/v2/translations/organization](listorglocales) endpoint.
   *
   * @param lng - The locale identifier corresponding to the language of the translation.
   * @returns DeleteOrgTranslationResponse
   */
  async deleteOrg(
    lng: string,
  ): Promise<DeepReadonly<DeleteOrgTranslationResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/translations/organization/{lng}',
      { params: { path: { lng } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get organization translation file with variant
   *
   * Source docs: https://help.sigmacomputing.com/reference/getorgtranslationswithvariant
   *
   * This endpoint returns a JSON file containing the translations and custom translations (**lng_variant**) for a locale (**lng**).
   *
   * ### Usage notes
   * - Retrieve the **lng** and **lng_variant** by calling the [/v2/translations/organization](listorglocales) endpoint.
   *
   * @param lng - The locale identifier corresponding to the language of the translation.
   * @param lng_variant - The name of the custom translation variant
   * @returns GetOrgTranslationsWithVariantResponse
   */
  async getOrgWithVariant(
    lng: string,
    lng_variant: string,
  ): Promise<DeepReadonly<GetOrgTranslationsWithVariantResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/translations/organization/{lng}/{lng_variant}',
      { params: { path: { lng, lng_variant } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Update organization translation file with variant
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateorgtranslationwithvariant
   *
   * This endpoint updates the translation file for the specified custom translation (**lng_variant**) for a locale (**lng**).
   *
   * ### Usage notes
   * - Retrieve the **lng** and **lng_variant** by calling the [/v2/translations/organization](listorglocales) endpoint.
   *
   * @param lng - The locale identifier corresponding to the language of the translation.
   * @param lng_variant - The name of the custom translation variant
   * @param body - The request body.
   * @returns UpdateOrgTranslationWithVariantResponse
   */
  async updateOrgWithVariant(
    lng: string,
    lng_variant: string,
    body: UpdateOrgTranslationWithVariantBody,
  ): Promise<DeepReadonly<UpdateOrgTranslationWithVariantResponse>> {
    const { data, error, response } = await this.client.PUT(
      '/v2/translations/organization/{lng}/{lng_variant}',
      { params: { path: { lng, lng_variant } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete organization translation file with variant
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteorgtranslationwithvariant
   *
   * This endpoint deletes the translation file for the specified custom translation (**lng_variant**) for a locale (**lng**).
   *
   * ### Usage notes
   * - Retrieve the **lng** and **lng_variant** by calling the [/v2/translations/organization](listorglocales) endpoint.
   *
   * @param lng - The locale identifier corresponding to the language of the translation.
   * @param lng_variant - The name of the custom translation variant
   * @returns DeleteOrgTranslationWithVariantResponse
   */
  async deleteOrgWithVariant(
    lng: string,
    lng_variant: string,
  ): Promise<DeepReadonly<DeleteOrgTranslationWithVariantResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/translations/organization/{lng}/{lng_variant}',
      { params: { path: { lng, lng_variant } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
