// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import {
  PaginatedAsyncGenerator,
  DeepReadonly,
  HydratePage,
} from '../pagination';

// ---------------------------------------------------------------------------
// Query parameter interfaces
// ---------------------------------------------------------------------------

/** Query parameters for {@link UserAttributesResource["list"] | list}. */
export interface ListUserAttributesQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
  /** Search filter for the name of the user attribute. */
  name?: string;
}

/** Query parameters for {@link UserAttributesResource["listTeamAssignments"] | listTeamAssignments}. */
export interface ListUserAttributeTeamAssignmentsQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

/** Query parameters for {@link UserAttributesResource["listTenantAssignments"] | listTenantAssignments}. */
export interface ListUserAttributeTenantAssignmentsQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

/** Query parameters for {@link UserAttributesResource["listUserAssignments"] | listUserAssignments}. */
export interface ListUserAttributeUserAssignmentsQuery {
  /** Use to specify further pages using the string returned in the nextPage portion of the response. */
  page?: string;
  /**
   * Number of results to return per page, with a maximum of 1,000 per request. Use the `page` option in subsequent requests to retrieve the next set of results.
   */
  limit?: number;
}

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link UserAttributesResource["create"] | create}. */
export interface CreateUserAttributeBody {
  /** Name of the user attribute. */
  name: string;
  /** Description of the user attribute. */
  description?: string;
  /** Default value of the user attribute. */
  defaultValue?: {
    val: string;
    type: 'string';
  };
}

/** Request body for {@link UserAttributesResource["setForTeams"] | setForTeams}. */
export interface SetUserAttributeForTeamsBody {
  assignments: {
    teamId: string;
    value: {
      val: string;
      type: 'string';
    };
  }[];
}

/** Request body for {@link UserAttributesResource["updateForTeams"] | updateForTeams}. */
export interface UpdateUserAttributeForTeamsBody {
  /** The teams whose assignments are to be revoked. */
  delete: {
    teamId: string;
  }[];
}

/** Request body for {@link UserAttributesResource["setForTenants"] | setForTenants}. */
export interface SetUserAttributeForTenantsBody {
  assignments: {
    tenantOrganizationId: string;
    value: {
      val: string;
      type: 'string';
    };
  }[];
}

/** Request body for {@link UserAttributesResource["updateForTenants"] | updateForTenants}. */
export interface UpdateUserAttributeForTenantsBody {
  /** The tenants whose assignments are to be revoked. */
  delete: {
    tenantOrganizationId: string;
  }[];
}

/** Request body for {@link UserAttributesResource["setForUsers"] | setForUsers}. */
export interface SetUserAttributeForUsersBody {
  assignments: {
    userId: string;
    value: {
      val: string;
      type: 'string';
    };
  }[];
}

/** Request body for {@link UserAttributesResource["updateForUsers"] | updateForUsers}. */
export interface UpdateUserAttributeForUsersBody {
  /** The users whose assignments are to be revoked. */
  delete: {
    userId: string;
  }[];
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link UserAttributesResource["list"] | list}. */
export interface ListUserAttributesResponse {
  entries: {
    userAttributeId: string;
    name: string;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
    description?: string | null;
    defaultValue?: {
      val: string;
      type: 'string';
    } | null;
  }[];
  nextPage: string | null;
  total?: number;
}

/** Response from {@link UserAttributesResource["create"] | create}. */
export interface CreateUserAttributeResponse {
  /** Unique identifier of the user attribute. */
  userAttributeId: string;
  /** Name of the user attribute. */
  name: string;
  /** The identifier of the user who created this object. */
  createdBy: string;
  /** The identifier of the user or process that last updated this object. */
  updatedBy: string;
  /** When the object was created. */
  createdAt: string;
  /** When the object was last updated. */
  updatedAt: string;
  /** Description of the user attribute. */
  description?: string | null;
  /** Default value of the user attribute. */
  defaultValue?: {
    val: string;
    type: 'string';
  } | null;
}

/** Response from {@link UserAttributesResource["get"] | get}. */
export interface GetUserAttributeResponse {
  /** Unique identifier of the user attribute. */
  userAttributeId: string;
  /** Name of the user attribute. */
  name: string;
  /** The identifier of the user who created this object. */
  createdBy: string;
  /** The identifier of the user or process that last updated this object. */
  updatedBy: string;
  /** When the object was created. */
  createdAt: string;
  /** When the object was last updated. */
  updatedAt: string;
  /** Description of the user attribute. */
  description?: string | null;
  /** Default value of the user attribute. */
  defaultValue?: {
    val: string;
    type: 'string';
  } | null;
}

/** Response from {@link UserAttributesResource["delete"] | delete}. */
export type DeleteUserAttributeResponse = Record<string, never>;

/** Response from {@link UserAttributesResource["listTeamAssignments"] | listTeamAssignments}. */
export interface ListUserAttributeTeamAssignmentsResponse {
  entries: {
    teamId: string;
    value: {
      val: string;
      type: 'string';
    };
    priority: number;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
  }[];
  nextPage: string | null;
  total?: number;
}

/** Response from {@link UserAttributesResource["setForTeams"] | setForTeams}. */
export type SetUserAttributeForTeamsResponse = Record<string, never>;

/** Response from {@link UserAttributesResource["updateForTeams"] | updateForTeams}. */
export type UpdateUserAttributeForTeamsResponse = Record<string, never>;

/** Response from {@link UserAttributesResource["deleteForTeam"] | deleteForTeam}. */
export type DeleteUserAttributeForTeamResponse = Record<string, never>;

/** Response from {@link UserAttributesResource["listTenantAssignments"] | listTenantAssignments}. */
export interface ListUserAttributeTenantAssignmentsResponse {
  entries: {
    tenantOrganizationId: string;
    value: {
      val: string;
      type: 'string';
    };
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
  }[];
  nextPage: string | null;
  total?: number;
}

/** Response from {@link UserAttributesResource["setForTenants"] | setForTenants}. */
export type SetUserAttributeForTenantsResponse = Record<string, never>;

/** Response from {@link UserAttributesResource["updateForTenants"] | updateForTenants}. */
export type UpdateUserAttributeForTenantsResponse = Record<string, never>;

/** Response from {@link UserAttributesResource["deleteForTenant"] | deleteForTenant}. */
export type DeleteUserAttributeForTenantResponse = Record<string, never>;

/** Response from {@link UserAttributesResource["listUserAssignments"] | listUserAssignments}. */
export interface ListUserAttributeUserAssignmentsResponse {
  entries: {
    userId: string;
    value: {
      val: string;
      type: 'string';
    };
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
  }[];
  nextPage: string | null;
  total?: number;
}

/** Response from {@link UserAttributesResource["setForUsers"] | setForUsers}. */
export type SetUserAttributeForUsersResponse = Record<string, never>;

/** Response from {@link UserAttributesResource["updateForUsers"] | updateForUsers}. */
export type UpdateUserAttributeForUsersResponse = Record<string, never>;

/** Response from {@link UserAttributesResource["deleteForUser"] | deleteForUser}. */
export type DeleteUserAttributeForUserResponse = Record<string, never>;

// ---------------------------------------------------------------------------
// Sub-resource accessors (hydration)
// ---------------------------------------------------------------------------

/** Sub-resource accessors available on hydrated userattribute entries. */
export interface UserAttributeSubResources {
  teamAssignments: {
    /**
     * Get teams for a user attribute
     *
     * Source docs: https://help.sigmacomputing.com/reference/getuserattributeteamassignments
     *
     * Get a list of teams that have a specific user attribute defined, and the assigned value for the user attribute.
     *
     *   ### Usage notes
     *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
     *
     * @param query - Query parameters
     * @returns ListUserAttributeTeamAssignmentsResponse
     */
    list(
      query?: ListUserAttributeTeamAssignmentsQuery,
    ): Promise<DeepReadonly<ListUserAttributeTeamAssignmentsResponse>>;
    /**
     * Get teams for a user attribute (auto-paginate all pages)
     *
     * Source docs: https://help.sigmacomputing.com/reference/getuserattributeteamassignments
     *
     * Get a list of teams that have a specific user attribute defined, and the assigned value for the user attribute.
     *
     *   ### Usage notes
     *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
     *
     * @param query - Query parameters
     * @yields ListUserAttributeTeamAssignmentsResponse
     */
    listAll(
      query?: ListUserAttributeTeamAssignmentsQuery,
    ): PaginatedAsyncGenerator<
      DeepReadonly<ListUserAttributeTeamAssignmentsResponse>
    >;
  };
  tenantAssignments: {
    /**
     * Get tenants for a user attribute
     *
     * Source docs: https://help.sigmacomputing.com/reference/getuserattributetenantassignments
     *
     * Get a list of tenants that have a specific user attribute defined, and the assigned value for the user attribute.
     *
     *   ### Usage notes
     *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
     *
     * @param query - Query parameters
     * @returns ListUserAttributeTenantAssignmentsResponse
     */
    list(
      query?: ListUserAttributeTenantAssignmentsQuery,
    ): Promise<DeepReadonly<ListUserAttributeTenantAssignmentsResponse>>;
    /**
     * Get tenants for a user attribute (auto-paginate all pages)
     *
     * Source docs: https://help.sigmacomputing.com/reference/getuserattributetenantassignments
     *
     * Get a list of tenants that have a specific user attribute defined, and the assigned value for the user attribute.
     *
     *   ### Usage notes
     *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
     *
     * @param query - Query parameters
     * @yields ListUserAttributeTenantAssignmentsResponse
     */
    listAll(
      query?: ListUserAttributeTenantAssignmentsQuery,
    ): PaginatedAsyncGenerator<
      DeepReadonly<ListUserAttributeTenantAssignmentsResponse>
    >;
  };
  userAssignments: {
    /**
     * Get users for a user attribute
     *
     * Source docs: https://help.sigmacomputing.com/reference/getuserattributeuserassignments
     *
     * Get a list of users that have a specific user attribute defined, and the assigned value for the user attribute.
     *
     *   ### Usage notes
     *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
     *
     * @param query - Query parameters
     * @returns ListUserAttributeUserAssignmentsResponse
     */
    list(
      query?: ListUserAttributeUserAssignmentsQuery,
    ): Promise<DeepReadonly<ListUserAttributeUserAssignmentsResponse>>;
    /**
     * Get users for a user attribute (auto-paginate all pages)
     *
     * Source docs: https://help.sigmacomputing.com/reference/getuserattributeuserassignments
     *
     * Get a list of users that have a specific user attribute defined, and the assigned value for the user attribute.
     *
     *   ### Usage notes
     *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
     *
     * @param query - Query parameters
     * @yields ListUserAttributeUserAssignmentsResponse
     */
    listAll(
      query?: ListUserAttributeUserAssignmentsQuery,
    ): PaginatedAsyncGenerator<
      DeepReadonly<ListUserAttributeUserAssignmentsResponse>
    >;
  };
  /**
   * Set a user attribute for teams
   *
   * Source docs: https://help.sigmacomputing.com/reference/setuserattributeforteams
   *
   * Assign and set the value of a specific user attribute for one or more teams.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *
   * @param body - The request body.
   * @returns SetUserAttributeForTeamsResponse
   */
  setForTeams(
    body: SetUserAttributeForTeamsBody,
  ): Promise<DeepReadonly<SetUserAttributeForTeamsResponse>>;
  /**
   * Update a user attribute for teams
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateuserattributeforteams
   *
   * Update a user attribute for one or more teams. Currently, this endpoint only supports deleting a user attribute assignment.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *
   * @param body - The request body.
   * @returns UpdateUserAttributeForTeamsResponse
   */
  updateForTeams(
    body: UpdateUserAttributeForTeamsBody,
  ): Promise<DeepReadonly<UpdateUserAttributeForTeamsResponse>>;
  /**
   * Delete a user attribute for a team
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteuserattributeforteam
   *
   * Delete a specific user attribute for a specific team.
   *
   * ### Usage notes
   * - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   * - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *
   * @param teamId - Unique identifier of the team.
   * @returns DeleteUserAttributeForTeamResponse
   */
  deleteForTeam(
    teamId: string,
  ): Promise<DeepReadonly<DeleteUserAttributeForTeamResponse>>;
  /**
   * Set a user attribute for tenants (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/setuserattributefortenants
   *
   * Assign and set the value of a specific user attribute for one or more tenants.
   *
   *   **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Specify one or more tenant by tenantOrganizationId. Retrieve the **tenantOrganizationId** by calling the [/v2/tenants](listTenants) endpoint and using the `tenantOrganizationId` included in the response.
   *
   * @param body - The request body.
   * @returns SetUserAttributeForTenantsResponse
   */
  setForTenants(
    body: SetUserAttributeForTenantsBody,
  ): Promise<DeepReadonly<SetUserAttributeForTenantsResponse>>;
  /**
   * Update a user attribute for tenants (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateuserattributefortenants
   *
   * Update a user attribute for one or more tenants. Currently, this endpoint only supports deleting a user attribute assignment.
   *
   *   **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Specify one or more tenants by tenantOrganizationId. Retrieve the **tenantOrganizationId** by calling the [/v2/tenants](listtenants) endpoint and using the `tenantOrganizationId` included in the response.
   *
   * @param body - The request body.
   * @returns UpdateUserAttributeForTenantsResponse
   */
  updateForTenants(
    body: UpdateUserAttributeForTenantsBody,
  ): Promise<DeepReadonly<UpdateUserAttributeForTenantsResponse>>;
  /**
   * Delete a user attribute for a tenant (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteuserattributefortenant
   *
   * Delete a specific user attribute for a specific tenant.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](lisuserattributes) endpoint.
   *   - Retrieve the **tenantOrganizationId** by calling the [/v2/tenants](listenants) endpoint and using the `tenantOrganizationId` included in the response.
   *
   * @param tenantOrganizationId - Unique identifier of the tenant.
   * @returns DeleteUserAttributeForTenantResponse
   */
  deleteForTenant(
    tenantOrganizationId: string,
  ): Promise<DeepReadonly<DeleteUserAttributeForTenantResponse>>;
  /**
   * Set a user attribute for users
   *
   * Source docs: https://help.sigmacomputing.com/reference/setuserattributeforusers
   *
   * Assign and set the value of a specific user attribute for one or more users.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Specify one or more users by userId. Retrieve the **userId** by calling the [/v2/members](listmembers) endpoint and using the `memberId` included in the response.
   *
   * @param body - The request body.
   * @returns SetUserAttributeForUsersResponse
   */
  setForUsers(
    body: SetUserAttributeForUsersBody,
  ): Promise<DeepReadonly<SetUserAttributeForUsersResponse>>;
  /**
   * Update a user attribute for users
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateuserattributeforusers
   *
   * Update a user attribute for one or more users. Currently, this endpoint only supports deleting a user attribute assignment.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Specify one or more users by userId. Retrieve the **userId** by calling the [/v2/members](listmembers) endpoint and using the `memberId` included in the response.
   *
   * @param body - The request body.
   * @returns UpdateUserAttributeForUsersResponse
   */
  updateForUsers(
    body: UpdateUserAttributeForUsersBody,
  ): Promise<DeepReadonly<UpdateUserAttributeForUsersResponse>>;
  /**
   * Delete a user attribute for a user
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteuserattributeforuser
   *
   * Delete a specific user attribute for a specific user.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Retrieve the **userId** by calling the [/v2/members](listmembers) endpoint and using the `memberId` included in the response.
   *
   * @param userId - Unique identifier of the user.
   * @returns DeleteUserAttributeForUserResponse
   */
  deleteForUser(
    userId: string,
  ): Promise<DeepReadonly<DeleteUserAttributeForUserResponse>>;
}

/** A userattribute entry with sub-resource accessor methods. Response data properties are deeply readonly. */
export type HydratedUserAttribute<T> = DeepReadonly<T> &
  UserAttributeSubResources;

// ---------------------------------------------------------------------------
// UserAttributesResource
// ---------------------------------------------------------------------------

/** @internal Attach sub-resource accessors to a userattribute entry. */
function _hydrateUserAttribute<T extends object>(
  entry: T,
  resource: UserAttributesResource,
): HydratedUserAttribute<T> {
  return Object.assign(entry, {
    teamAssignments: {
      list: (query?: ListUserAttributeTeamAssignmentsQuery) =>
        resource.listTeamAssignments((entry as any).userAttributeId, query),
      listAll: (query?: ListUserAttributeTeamAssignmentsQuery) =>
        resource.listTeamAssignmentsAll((entry as any).userAttributeId, query),
    },
    tenantAssignments: {
      list: (query?: ListUserAttributeTenantAssignmentsQuery) =>
        resource.listTenantAssignments((entry as any).userAttributeId, query),
      listAll: (query?: ListUserAttributeTenantAssignmentsQuery) =>
        resource.listTenantAssignmentsAll(
          (entry as any).userAttributeId,
          query,
        ),
    },
    userAssignments: {
      list: (query?: ListUserAttributeUserAssignmentsQuery) =>
        resource.listUserAssignments((entry as any).userAttributeId, query),
      listAll: (query?: ListUserAttributeUserAssignmentsQuery) =>
        resource.listUserAssignmentsAll((entry as any).userAttributeId, query),
    },
    setForTeams: (body: SetUserAttributeForTeamsBody) =>
      resource.setForTeams((entry as any).userAttributeId, body),
    updateForTeams: (body: UpdateUserAttributeForTeamsBody) =>
      resource.updateForTeams((entry as any).userAttributeId, body),
    deleteForTeam: (teamId: string) =>
      resource.deleteForTeam((entry as any).userAttributeId, teamId),
    setForTenants: (body: SetUserAttributeForTenantsBody) =>
      resource.setForTenants((entry as any).userAttributeId, body),
    updateForTenants: (body: UpdateUserAttributeForTenantsBody) =>
      resource.updateForTenants((entry as any).userAttributeId, body),
    deleteForTenant: (tenantOrganizationId: string) =>
      resource.deleteForTenant(
        (entry as any).userAttributeId,
        tenantOrganizationId,
      ),
    setForUsers: (body: SetUserAttributeForUsersBody) =>
      resource.setForUsers((entry as any).userAttributeId, body),
    updateForUsers: (body: UpdateUserAttributeForUsersBody) =>
      resource.updateForUsers((entry as any).userAttributeId, body),
    deleteForUser: (userId: string) =>
      resource.deleteForUser((entry as any).userAttributeId, userId),
  }) as HydratedUserAttribute<T>;
}

export class UserAttributesResource {
  constructor(private client: Client<paths>) {}

  /**
   * List user attributes
   *
   * Source docs: https://help.sigmacomputing.com/reference/listuserattributes
   *
   * Get a list of available user attributes, values, and owners.
   *
   * @param query - Query parameters
   * @returns ListUserAttributesResponse
   */
  async list(
    query?: ListUserAttributesQuery,
  ): Promise<
    HydratePage<ListUserAttributesResponse, UserAttributeSubResources>
  > {
    const { data, error, response } = await this.client.GET(
      '/v2/user-attributes',
      { params: { query } },
    );
    if (error) throw new SigmaApiError(error, response);
    const result = data! as any;
    if (Array.isArray(result)) {
      return result.map((e: any) => _hydrateUserAttribute(e, this)) as any;
    }
    if (result.entries && Array.isArray(result.entries)) {
      result.entries = result.entries.map((e: any) =>
        _hydrateUserAttribute(e, this),
      );
    }
    return result;
  }

  /**
   * List user attributes (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/listuserattributes
   *
   * Get a list of available user attributes, values, and owners.
   *
   * @param query - Query parameters
   * @yields ListUserAttributesResponse
   */
  listAll(
    query?: ListUserAttributesQuery,
  ): PaginatedAsyncGenerator<
    HydratePage<ListUserAttributesResponse, UserAttributeSubResources>
  > {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.list({
          ...query,
          page: cursor,
        } as ListUserAttributesQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Create a user attribute
   *
   * Source docs: https://help.sigmacomputing.com/reference/createuserattribute
   *
   * Create a new user attribute. An optional description and default value can be provided.
   *
   * @param body - The request body.
   * @returns CreateUserAttributeResponse
   */
  async create(
    body: CreateUserAttributeBody,
  ): Promise<HydratedUserAttribute<CreateUserAttributeResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/user-attributes',
      { body },
    );
    if (error) throw new SigmaApiError(error, response);
    return _hydrateUserAttribute(data! as any, this);
  }

  /**
   * Get a user attribute
   *
   * Source docs: https://help.sigmacomputing.com/reference/getuserattribute
   *
   * Get details for a specific user attribute.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @returns GetUserAttributeResponse
   */
  async get(
    userAttributeId: string,
  ): Promise<HydratedUserAttribute<GetUserAttributeResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/user-attributes/{userAttributeId}',
      { params: { path: { userAttributeId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return _hydrateUserAttribute(data! as any, this);
  }

  /**
   * Delete a user attribute
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteuserattribute
   *
   * Delete a user attribute.
   *
   * ### Usage notes
   * - To perform this operation, you must use API credentials owned by a user assigned the Admin account type.
   * - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   * - This action permanently removes the user attribute from the organization and cannot be undone.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @returns DeleteUserAttributeResponse
   */
  async delete(
    userAttributeId: string,
  ): Promise<DeepReadonly<DeleteUserAttributeResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/user-attributes/{userAttributeId}',
      { params: { path: { userAttributeId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get teams for a user attribute
   *
   * Source docs: https://help.sigmacomputing.com/reference/getuserattributeteamassignments
   *
   * Get a list of teams that have a specific user attribute defined, and the assigned value for the user attribute.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param query - Query parameters
   * @returns ListUserAttributeTeamAssignmentsResponse
   */
  async listTeamAssignments(
    userAttributeId: string,
    query?: ListUserAttributeTeamAssignmentsQuery,
  ): Promise<DeepReadonly<ListUserAttributeTeamAssignmentsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/user-attributes/{userAttributeId}/teams',
      { params: { path: { userAttributeId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get teams for a user attribute (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/getuserattributeteamassignments
   *
   * Get a list of teams that have a specific user attribute defined, and the assigned value for the user attribute.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param query - Query parameters
   * @yields ListUserAttributeTeamAssignmentsResponse
   */
  listTeamAssignmentsAll(
    userAttributeId: string,
    query?: ListUserAttributeTeamAssignmentsQuery,
  ): PaginatedAsyncGenerator<
    DeepReadonly<ListUserAttributeTeamAssignmentsResponse>
  > {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listTeamAssignments(userAttributeId, {
          ...query,
          page: cursor,
        } as ListUserAttributeTeamAssignmentsQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Set a user attribute for teams
   *
   * Source docs: https://help.sigmacomputing.com/reference/setuserattributeforteams
   *
   * Assign and set the value of a specific user attribute for one or more teams.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param body - The request body.
   * @returns SetUserAttributeForTeamsResponse
   */
  async setForTeams(
    userAttributeId: string,
    body: SetUserAttributeForTeamsBody,
  ): Promise<DeepReadonly<SetUserAttributeForTeamsResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/user-attributes/{userAttributeId}/teams',
      { params: { path: { userAttributeId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Update a user attribute for teams
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateuserattributeforteams
   *
   * Update a user attribute for one or more teams. Currently, this endpoint only supports deleting a user attribute assignment.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param body - The request body.
   * @returns UpdateUserAttributeForTeamsResponse
   */
  async updateForTeams(
    userAttributeId: string,
    body: UpdateUserAttributeForTeamsBody,
  ): Promise<DeepReadonly<UpdateUserAttributeForTeamsResponse>> {
    const { data, error, response } = await this.client.PATCH(
      '/v2/user-attributes/{userAttributeId}/teams',
      { params: { path: { userAttributeId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete a user attribute for a team
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteuserattributeforteam
   *
   * Delete a specific user attribute for a specific team.
   *
   * ### Usage notes
   * - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   * - Retrieve the **teamId** by calling the [/v2/teams](listteams) endpoint.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param teamId - Unique identifier of the team.
   * @returns DeleteUserAttributeForTeamResponse
   */
  async deleteForTeam(
    userAttributeId: string,
    teamId: string,
  ): Promise<DeepReadonly<DeleteUserAttributeForTeamResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/user-attributes/{userAttributeId}/teams/{teamId}',
      { params: { path: { userAttributeId, teamId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get tenants for a user attribute
   *
   * Source docs: https://help.sigmacomputing.com/reference/getuserattributetenantassignments
   *
   * Get a list of tenants that have a specific user attribute defined, and the assigned value for the user attribute.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param query - Query parameters
   * @returns ListUserAttributeTenantAssignmentsResponse
   */
  async listTenantAssignments(
    userAttributeId: string,
    query?: ListUserAttributeTenantAssignmentsQuery,
  ): Promise<DeepReadonly<ListUserAttributeTenantAssignmentsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/user-attributes/{userAttributeId}/tenants',
      { params: { path: { userAttributeId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get tenants for a user attribute (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/getuserattributetenantassignments
   *
   * Get a list of tenants that have a specific user attribute defined, and the assigned value for the user attribute.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param query - Query parameters
   * @yields ListUserAttributeTenantAssignmentsResponse
   */
  listTenantAssignmentsAll(
    userAttributeId: string,
    query?: ListUserAttributeTenantAssignmentsQuery,
  ): PaginatedAsyncGenerator<
    DeepReadonly<ListUserAttributeTenantAssignmentsResponse>
  > {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listTenantAssignments(userAttributeId, {
          ...query,
          page: cursor,
        } as ListUserAttributeTenantAssignmentsQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Set a user attribute for tenants (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/setuserattributefortenants
   *
   * Assign and set the value of a specific user attribute for one or more tenants.
   *
   *   **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Specify one or more tenant by tenantOrganizationId. Retrieve the **tenantOrganizationId** by calling the [/v2/tenants](listTenants) endpoint and using the `tenantOrganizationId` included in the response.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param body - The request body.
   * @returns SetUserAttributeForTenantsResponse
   */
  async setForTenants(
    userAttributeId: string,
    body: SetUserAttributeForTenantsBody,
  ): Promise<DeepReadonly<SetUserAttributeForTenantsResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/user-attributes/{userAttributeId}/tenants',
      { params: { path: { userAttributeId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Update a user attribute for tenants (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateuserattributefortenants
   *
   * Update a user attribute for one or more tenants. Currently, this endpoint only supports deleting a user attribute assignment.
   *
   *   **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Specify one or more tenants by tenantOrganizationId. Retrieve the **tenantOrganizationId** by calling the [/v2/tenants](listtenants) endpoint and using the `tenantOrganizationId` included in the response.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param body - The request body.
   * @returns UpdateUserAttributeForTenantsResponse
   */
  async updateForTenants(
    userAttributeId: string,
    body: UpdateUserAttributeForTenantsBody,
  ): Promise<DeepReadonly<UpdateUserAttributeForTenantsResponse>> {
    const { data, error, response } = await this.client.PATCH(
      '/v2/user-attributes/{userAttributeId}/tenants',
      { params: { path: { userAttributeId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete a user attribute for a tenant (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteuserattributefortenant
   *
   * Delete a specific user attribute for a specific tenant.
   *
   * **Beta**: This documentation describes a public beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](lisuserattributes) endpoint.
   *   - Retrieve the **tenantOrganizationId** by calling the [/v2/tenants](listenants) endpoint and using the `tenantOrganizationId` included in the response.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param tenantOrganizationId - Unique identifier of the tenant.
   * @returns DeleteUserAttributeForTenantResponse
   */
  async deleteForTenant(
    userAttributeId: string,
    tenantOrganizationId: string,
  ): Promise<DeepReadonly<DeleteUserAttributeForTenantResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/user-attributes/{userAttributeId}/tenants/{tenantOrganizationId}',
      { params: { path: { userAttributeId, tenantOrganizationId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get users for a user attribute
   *
   * Source docs: https://help.sigmacomputing.com/reference/getuserattributeuserassignments
   *
   * Get a list of users that have a specific user attribute defined, and the assigned value for the user attribute.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param query - Query parameters
   * @returns ListUserAttributeUserAssignmentsResponse
   */
  async listUserAssignments(
    userAttributeId: string,
    query?: ListUserAttributeUserAssignmentsQuery,
  ): Promise<DeepReadonly<ListUserAttributeUserAssignmentsResponse>> {
    const { data, error, response } = await this.client.GET(
      '/v2/user-attributes/{userAttributeId}/users',
      { params: { path: { userAttributeId }, query } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Get users for a user attribute (auto-paginate all pages)
   *
   * Source docs: https://help.sigmacomputing.com/reference/getuserattributeuserassignments
   *
   * Get a list of users that have a specific user attribute defined, and the assigned value for the user attribute.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param query - Query parameters
   * @yields ListUserAttributeUserAssignmentsResponse
   */
  listUserAssignmentsAll(
    userAttributeId: string,
    query?: ListUserAttributeUserAssignmentsQuery,
  ): PaginatedAsyncGenerator<
    DeepReadonly<ListUserAttributeUserAssignmentsResponse>
  > {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const resource = this;
    async function* gen() {
      let cursor: string | undefined;
      do {
        const page = await resource.listUserAssignments(userAttributeId, {
          ...query,
          page: cursor,
        } as ListUserAttributeUserAssignmentsQuery);
        yield page;
        cursor = (page as { nextPage?: string | null })['nextPage'] as
          string | undefined;
      } while (cursor);
    }
    return new PaginatedAsyncGenerator(gen());
  }

  /**
   * Set a user attribute for users
   *
   * Source docs: https://help.sigmacomputing.com/reference/setuserattributeforusers
   *
   * Assign and set the value of a specific user attribute for one or more users.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Specify one or more users by userId. Retrieve the **userId** by calling the [/v2/members](listmembers) endpoint and using the `memberId` included in the response.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param body - The request body.
   * @returns SetUserAttributeForUsersResponse
   */
  async setForUsers(
    userAttributeId: string,
    body: SetUserAttributeForUsersBody,
  ): Promise<DeepReadonly<SetUserAttributeForUsersResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/user-attributes/{userAttributeId}/users',
      { params: { path: { userAttributeId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Update a user attribute for users
   *
   * Source docs: https://help.sigmacomputing.com/reference/updateuserattributeforusers
   *
   * Update a user attribute for one or more users. Currently, this endpoint only supports deleting a user attribute assignment.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Specify one or more users by userId. Retrieve the **userId** by calling the [/v2/members](listmembers) endpoint and using the `memberId` included in the response.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param body - The request body.
   * @returns UpdateUserAttributeForUsersResponse
   */
  async updateForUsers(
    userAttributeId: string,
    body: UpdateUserAttributeForUsersBody,
  ): Promise<DeepReadonly<UpdateUserAttributeForUsersResponse>> {
    const { data, error, response } = await this.client.PATCH(
      '/v2/user-attributes/{userAttributeId}/users',
      { params: { path: { userAttributeId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }

  /**
   * Delete a user attribute for a user
   *
   * Source docs: https://help.sigmacomputing.com/reference/deleteuserattributeforuser
   *
   * Delete a specific user attribute for a specific user.
   *
   *   ### Usage notes
   *   - Retrieve the **userAttributeId** by calling the [/v2/user-attributes](listuserattributes) endpoint.
   *   - Retrieve the **userId** by calling the [/v2/members](listmembers) endpoint and using the `memberId` included in the response.
   *
   * @param userAttributeId - Unique identifier of the user attribute.
   * @param userId - Unique identifier of the user.
   * @returns DeleteUserAttributeForUserResponse
   */
  async deleteForUser(
    userAttributeId: string,
    userId: string,
  ): Promise<DeepReadonly<DeleteUserAttributeForUserResponse>> {
    const { data, error, response } = await this.client.DELETE(
      '/v2/user-attributes/{userAttributeId}/users/{userId}',
      { params: { path: { userAttributeId, userId } } },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
