// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Request body types
// ---------------------------------------------------------------------------

/** Request body for {@link WebhooksResource["send"] | send}. */
export type WebhooksBody = Record<string, never>;

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link WebhooksResource["send"] | send}. */
export type WebhooksResponse = Record<string, never>;

// ---------------------------------------------------------------------------
// WebhooksResource
// ---------------------------------------------------------------------------

export class WebhooksResource {
  constructor(private client: Client<paths>) {}

  /**
   * Send to a webhook (Beta)
   *
   * Source docs: https://help.sigmacomputing.com/reference/webhooks
   *
   * Post data to a webhook endpoint. The request body must match the configured webhook specification configured in Sigma.
   *
   * **Beta**: This documentation describes a private beta feature and is subject to the [Beta features](doc:sigma-product-releases#beta-features) disclaimer.
   *
   * ### Usage notes
   * - Retrieve the webhook URL by creating a webhook through the Sigma UI. The URL will be formatted as `/v2/webhooks/{workbookId}/{sequenceId}`.
   *
   * @param workbookId - The unique identifier of the workbook.
   * @param sequenceId - The unique identifier of the sequence.
   * @param body - The request body.
   * @returns WebhooksResponse
   */
  async send(
    workbookId: string,
    sequenceId: string,
    body: WebhooksBody,
  ): Promise<DeepReadonly<WebhooksResponse>> {
    const { data, error, response } = await this.client.POST(
      '/v2/webhooks/{workbookId}/{sequenceId}',
      { params: { path: { workbookId, sequenceId } }, body },
    );
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
