// AUTO-GENERATED by scripts/generate-resources.ts -- DO NOT EDIT
import type { Client } from 'openapi-fetch';
import type { paths } from '../generated/openapi';
import { SigmaApiError } from '../errors';
import { DeepReadonly } from '../pagination';

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/** Response from {@link WhoamiResource["get"] | get}. */
export interface WhoAmIResponse {
  userId: string;
  organizationId: string;
}

// ---------------------------------------------------------------------------
// WhoamiResource
// ---------------------------------------------------------------------------

export class WhoamiResource {
  constructor(private client: Client<paths>) {}

  /**
   * Get current user
   *
   * Source docs: https://help.sigmacomputing.com/reference/whoami
   *
   * Get the identity and authentication status of the current user.
   *
   *   ### Usage notes
   *   Call this endpoint after authenticating to retrieve user details. It does not require any parameters other than the user's valid session or authentication token included in the request headers.
   *
   *   ### Usage scenarios
   *   - **Session validation:** Quickly confirm user authentication and retrieve session-specific details at the start of a new session.
   *   - **User configuration:** Retrieve settings or configurations specific to the user, allowing for a customized application experience based on user roles and permissions.
   *
   *   ### Best practices
   *   - Call this endpoint at the beginning of each session to ensure that the user's credentials are still valid and have not been revoked.
   *   - Use the information provided by this endpoint to tailor the user interface and functionality accessible to the user, enhancing security and user experience.
   * @returns WhoAmIResponse
   */
  async get(): Promise<DeepReadonly<WhoAmIResponse>> {
    const { data, error, response } = await this.client.GET('/v2/whoami');
    if (error) throw new SigmaApiError(error, response);
    return data!;
  }
}
